import type { SpainEssayBlock } from "@/components/SpainEssayPage";

export const SPAIN10_BLOCKS: SpainEssayBlock[] = [
  { type: "img", src: "spain38.jpg", width: 600, height: 445, alt: "Art Tour" },
  { type: "p", text: "The Pavilion of Spain offers visitors a complete and exceptional sample of the history of Spanish Art. Thirty centuries of artistic creation, from the Tartessian Treasure, the Visigothic Jewels and the Romanesque to the new art of 1965, have produced the masterpieces which on this unique occasion can be admired in the art galleries of the Pavilion. Three great landmarks of artistic creation can be seen in these halls. The unique works of Catalan Romanesque (panels, sculptures, canvases) and Visigothic jewels; the insuperable mastery of El Greco, Zurbaran, Ribera, Velazques and Goya in a miraculous synthesis only comparable to the ancient Spanish School of Painting; and the revolutionary and inexhaustible production of Pablo Picasso and his endless school of converts, now masters of contemporary universal art. This great present-day painting of which Spain has such outstanding creators is represented in the Pavilion by 28 works of Pancho Cossio's, to be followed by a monographic exhibition devoted to the Spanish landscape with all the great modern masters of the speciality: Palencia, Vazquez Dias, Vaquero Palacios..., and the most outstanding of the contemporary school. This fine artistic itinerary is rounded off by the bust of the Emperor Charles V by Leoni, drawings by Garcia Lorca and Gregorio Prieto, sculptures by Dali and Comendador, and the works of art that form part and parcel of the very architecture of the Pavilion of Spain: the railing by Amadeo Bavino, the sculptures by Serrano and Jose Luis Sanchez, the lattices by Labra, the stained glass windows by Molezun and the large murals by Vaquero Turcios." },
  { type: "h2", text: "DESCRIPTION" },
  { type: "p", text: "8. Museum Hall. Triptych The Painter and his Model, by Pablo Picasso. The Dollar Apotheosis, by Salvador Dali, Painting by Miro, Symbolic Compositions (rommanesque art). St. Anne, Virgin and child (Anonymous)." },
  { type: "img", src: "spain55.jpg", width: 150, height: 158, alt: "Pablo Picasso" },
  { type: "caption", text: "Picasso: The painter and his model." },
  { type: "img", src: "spain52.jpg", width: 200, height: 109, alt: "The Painter and his Model" },
  { type: "img", src: "spain56.jpg", width: 150, height: 145, alt: "Miro" },
  { type: "caption", text: "Miro: Fragment of a ceramic mural." },
  { type: "img", src: "spain53.jpg", width: 200, height: 112, alt: "Ceramic Mural" },
  { type: "img", src: "spain57.jpg", width: 150, height: 160, alt: "Dali" },
  { type: "caption", text: "Dali: Jewel." },
  { type: "img", src: "spain54.jpg", width: 200, height: 201, alt: "Dali Jewel" },
  { type: "p", text: "3. Discovery Hall. Giant murals by Vaquero Turcios, depicting Spanish faith, culture and the evangelization of the Americas, decorate the walls. Armours s. XVI; Horse's Harnesses; Navigation Instruments; The Story of the Conquest of Mexico by Hernan Cortes; Geographical Summary, by Fernandez de Enciso; busts of Pizarro and Hernan Cortes. The caravel Santa Maria; two maps of America." },
  { type: "p", text: "For many centuries Spanish arms and armour have had the reputation of being unsurpassed in both the Old World and the New. The Army Museum in Madrid has lent for exhibition in the Pavilion of Spain a collection of typical examples of the Spanish art of making steel weapons." },
  { type: "img", src: "spain49.jpg", width: 200, height: 268, alt: "Helmet" },
  { type: "caption", text: "Above: Helmet. Below: Head-piece for a horse." },
  { type: "img", src: "spain50.jpg", width: 200, height: 276, alt: "Horse Armour" },
  { type: "caption", text: "Gauntlet with six joints." },
  { type: "img", src: "spain51.jpg", width: 200, height: 103, alt: "Gauntlet" },
  { type: "p", text: "9. The Small Prado Museum. Paintings by five immortal artists are on display: El Greco: The Annunciation; The Baptism of Christ; Ribera: Martyrdom of St. Bartolomew; Zurbaran: St. Carmelo; Still Life of Metais; Velazquez: Portrait of the Cardinal Princess, Goya: The Crockery Dealers; Lady and the cloaked Men; Portrait of Cabarrus." },
  { type: "caption", text: "El Greco: The Annunciation, Balaguer Museum, Villanueva y Geltru." },
  { type: "img", src: "spain39.jpg", width: 200, height: 349, alt: "The Annuciation" },
  { type: "caption", text: "Zurbaran: Metals Still-life, Col. Bertran Guell." },
  { type: "img", src: "spain40.jpg", width: 200, height: 166, alt: "Metals Still-life" },
  { type: "caption", text: "Rivera: Martyrdom of St. Bartholemew, Prado Museum." },
  { type: "img", src: "spain41.jpg", width: 200, height: 183, alt: "Martyrdom of St. Bartholemew" },
  { type: "caption", text: "Velazquez: The Infante Cardinal, Prado Museum." },
  { type: "img", src: "spain42.jpg", width: 200, height: 369, alt: "The Infante Cardinal" },
  { type: "p", text: "Goya: The crockery seller, Prado Museum" },
  { type: "img", src: "spain43.jpg", width: 200, height: 180, alt: "The Crockery Seller" },
  { type: "p", text: "10. Museum of Romanesque Art. Calvary. Crowned Crucifix. St. Anne. Virgin and Child. Calvary Virgin. Bishop and Deacon. St. Peter. Crowning of St. Peter. The Immaculate Conception." },
  { type: "img", src: "spain63.jpg", width: 200, height: 355, alt: "Romanesque Art" },
  { type: "caption", text: "Romanesque Art." },
  { type: "img", src: "spain62.jpg", width: 200, height: 192, alt: "Romanesque Art" },
  { type: "p", text: "5. Hall of Honor. Mural of the Iberian peoples. Bust of the Emperor Charles V, by Leone Leoni. Tartessian Treasure of Carambolo and Visigothic Jewels of Guarrazar; Casuble of Cardinal Cisneros. Duran Codex, Sword of Charles V." },
  { type: "p", text: "Leoni: Silver Bust of the Caesar, Charles V. The Santa Cruz Museum, Toledo." },
  { type: "img", src: "spain47.jpg", width: 200, height: 325, alt: "Bust of Charles V" },
  { type: "caption", text: "Detail of the Armour." },
  { type: "img", src: "spain48.jpg", width: 200, height: 138, alt: "Armour Detail" },
  { type: "p", text: "The treasure of Guarrazar (Toledo)" },
  { type: "img", src: "spain44.jpg", width: 200, height: 192, alt: "Visigoth Treasure" },
  { type: "p", text: "The treasure is one of the best examples of the art of the Visigoths that spread throughout Spain until the Moorish invasion. The originals of this treasure, which are on show at the Archaeological Museum of Madrid, were found in 1858 in the same way as other jewels of Visigothic craftsmanship hidden at the time the Arabs swept through the land in the year 709." },
  { type: "img", src: "spain45.jpg", width: 200, height: 194, alt: "Visigoth Treasure" },
  { type: "img", src: "spain46.jpg", width: 200, height: 202, alt: "Visigoth Treasure" },
  { type: "h2", text: "6. The Spanish Peoples Salon. Craftsmanship, silver and goldwork, ceramic, china, miniatures..." },
  { type: "img", src: "spain60.jpg", width: 200, height: 155, alt: "Spanish Craftsmanship" },
  { type: "caption", text: "Spanish People's Salon." },
  { type: "img", src: "spain61.jpg", width: 200, height: 168, alt: "Spanish Craftsmanship" },
  { type: "h2", text: "Mural-collage. Restaurant Granada, by Francisco Ferraras and R. Domingo." },
  { type: "caption", text: "The Cuadrillas, by Daniel Vazquez Diaz, private dining room of the Commissioner." },
  { type: "caption", text: "Drawings by Garcia Lorca and Gregorio Prieto." },
  { type: "caption", text: "Garcia Lorca: Drawing." },
  { type: "img", src: "spain58.jpg", width: 200, height: 151, alt: "Garcia Lorca Drawing" },
  { type: "p", text: "The Adelantado of Florida, Hernando de Soto. Statue by Perez Comendador. outside courtyard." },
  { type: "caption", text: "Photographs by Gyenes." },
  { type: "caption", text: "Gyenes: Andres Segovia." },
  { type: "img", src: "spain59.jpg", width: 200, height: 200, alt: "Gyenes Photograph of Segovia" },
  { type: "caption", text: "45 minutes." },
  { type: "caption", text: "Length of tour: Approximately." },
  { type: "caption", text: "Hours: 10 a. m. 10 p. m." },
  { type: "img", src: "spain11.jpg", width: 91, height: 150, alt: "Guide Cover" },
];
