import type { SpainEssayBlock } from "@/components/SpainEssayPage";

export const SPAIN13_BLOCKS: SpainEssayBlock[] = [
  { type: "img", src: "spain66.jpg", width: 600, height: 298, alt: "Brochure Cover" },
  { type: "img", src: "spain68.jpg", width: 48, height: 72, alt: "T" },
  { type: "img", src: "spain69.jpg", width: 241, height: 30, alt: "" },
  { type: "p", text: "Pavilion as the most outstanding of the international pavilions at the New York World's Fair of 1964-65." },
  { type: "p", text: "The beautiful design of the leading Spanish architect, Javier Carajal, immediately captured the imagination of Fair visitors and eventually won several coveted prizes as a commodious expression of the best in contemporary European styling." },
  { type: "p", text: "The Spanish International Pavilion is unlike any other building in the world . . . a truly unique asset for a city unlike any other. Its exterior lines are clean, classic, and unadorned. Rough, white closed-in walls form a play of contrasting masses with a balancing series of gray blocks enclosing the second level." },
  { type: "p", text: "The various rooms of the Pavilion open onto a courtyard, full of plants and flowers, offering a surprise in space that provides a refreshing interlude of relaxation from the excitement within." },
  { type: "p", text: "The interior design of the Pavilion is a blend of the most ingenious present-day architecture with native Spanish traditionalism. The gift of the building to Saint Louis includes a treasure of stained glass, and paint, ceramic and collage murals. From the 364,000 unusual Flemish pine blocks that form the Moorish ceilings to the design of glass, cutlery and table services, every aspect of the Pavilion achieves a unity and a perfection that is truly as deeply satisfying as a fine jewel." },
  { type: "img", src: "spain67.jpg", width: 600, height: 301, alt: "Illustrated Pavilion Model" },
  { type: "img", src: "spain70.jpg", width: 200, height: 101, alt: "The Spanish Pavilion and YOU" },
  { type: "p", text: "The Spanish International Pavilion belongs to you as a citizen of the Saint Louis area in a special sense. For you and your neighbors have thus far volunteered more than 17,000 individual donations to help bring the Pavilion to Saint Louis." },
  { type: "p", text: "The Pavilion is the result of a spontaneous outpouring of civic enthusiasm -- the dimes and dollars of the people of Greater Saint Louis given to a non-profit project of permanent and growing value to the community. No tax money will be used, either to reconstructed or operate the Pavilion. The Pavilion will earn its own way in tourist dollars, and new tax revenue to Saint Louis." },
  { type: "p", text: "Each of us in the Saint Louis area . . . in the City and adjoining counties and on both sides of the Mississippi . . . has had a rich, new dimension added to our lives through this wondrous acquisition." },
  { type: "p", text: "Suddenly, The Spanish International Pavilion, with its theatre and library, restaurants and patios, shops and art galleries, becomes a part of our city . . . generating culture, education, and entertainment for all the people." },
  { type: "p", text: "No other city can equal it and it belongs to you. it must have your support. You can help make the pavilion a debt-free, self-supporting entity that, after 33 years, will be turned over to the City as a revenue-producing enterprise. Your contribution, which is tax-deductible, will help the Pavilion to earn its way to a free and clear status more quickly. Write your check to The Spanish International Pavilion Foundation, 408 Olive, St. Louis, 63102." },
  { type: "p", text: "The Spanish international Pavilion forms the final third of the fabulous combination that is focusing the eyes of the world on Saint Louis . . . The \"Tourist Triangle,\" formed by The Gateway Arch, The Busch Memorial Sports Stadium, and, now, the Pavilion." },
  { type: "p", text: "No other city in the world can claim three such singular attractions in an area of a few blocks: the breathtaking architectural and engineering triumph of Eero Saarinen and the tallest U.S. national monument; the magnificent setting of the Sports Stadium for the excitement of year 'round sporting events; and the coveted architectural prize of this decade which only one city could have . . . the Spanish International Pavilion." },
  { type: "p", text: "Travelers from throughout the world will be drawn to the \"Tourist Triangle\" as it becomes a \"must\" on every tour of America that dares to be called complete. The Chamber of Commerce of Metropolitan Saint Louis and Economic Research Associates, have estimated that the Spanish International Pavilion alone will create an annual gross income of $6,000,000. No one can predict the total economic impact of the \"Tourist Triangle\" upon this area. But there can be little doubt that the final measure of benefits . . . cultural, educational, recreational and economic . . . will be astronomical." },
  { type: "img", src: "spain72.jpg", width: 150, height: 219, alt: "the TOURIST TRIANGLE" },
  { type: "img", src: "spain71.jpg", width: 250, height: 285, alt: "Tourist Triangle Illustrated" },
  { type: "img", src: "spain73.jpg", width: 360, height: 76, alt: "The Arch & The Pomegranate" },
  { type: "caption", text: "The main lobby of the Spanish International Pavilion." },
  { type: "p", text: "The symbol of The Spanish International Pavilion Foundation is a stylized pomegranate enclosed within a Gateway Arch. The pomegranate, a traditional part of Spain's Coat of Arms, is rich in historical significance for both America and Spain. The Spanish for pomegranate is \"granda\". It was the victory over the Moors in the City of Granada that made possible the birth of the Spanish Nation." },
  { type: "p", text: "The year was 1492 and the triumphant Queen Isabella granted Christopher Columbus her commission to explore the New World. The meeting took place in Granada just after the victory. So it can be said that in the City of the Pomegranate were formed the beginnings of two great nations whose common heritage and friendship finds modern expression today in our Spanish International Pavilion." },
  { type: "img", src: "spain74.jpg", width: 230, height: 236, alt: "Lobby" },
  { type: "caption", text: "The Theatre Lobby Bar." },
  { type: "img", src: "spain76.jpg", width: 230, height: 169, alt: "Theatre Lobby Bar" },
  { type: "p", text: "Spanish entertainment will be frequently featured in the Pavilion and the flexible facilities will accommodate a variety of other cultural and theatrical events." },
  { type: "img", src: "spain75.jpg", width: 350, height: 213, alt: "Spanish Entertainment" },
  { type: "img", src: "spain77.jpg", width: 200, height: 192, alt: "Restaurant View" },
  { type: "p", text: "One of the elegant restaurants that grace the Pavilion" },
  { type: "p", text: "Daylight streaming into the Pavilion's inner courtyard highlights the pomegranate symbol on the textured walls. Pablo Serrano's statue of Fray Junipero Serra stands beside the fountain and shrubbery of this serene area." },
  { type: "img", src: "spain78.jpg", width: 290, height: 233, alt: "Courtyard View" },
  { type: "img", src: "spain79.jpg", width: 290, height: 183, alt: "Courtyard View" },
  { type: "img", src: "spain80.jpg", width: 200, height: 146, alt: "Turcios Mural" },
  { type: "p", text: "A mural depicting the religious contribution of Spain to the New World by artist Joaquin Vaquero Turcios." },
  { type: "img", src: "spain81.jpg", width: 290, height: 208, alt: "Bravo! World's Fair Gold Medal" },
  { type: "p", text: "Citation as The Most Outstanding Building of its Kind in 1964 . . . New York Chapter, American Institute of Architects" },
  { type: "source", text: "Source: Fund Raising Brochure for the Spanish International Pavilion in Saint Louis" },
  { type: "img", src: "spain82.jpg", width: 600, height: 297, alt: "Brochure Back Page" },
];
