import type { SpainEssayBlock } from "@/components/SpainEssayPage";

export const SPAIN05_BLOCKS: SpainEssayBlock[] = [
  {
    type: "img",
    src: "spain03.jpg",
    width: 595,
    height: 381,
    alt: "Cover of the Pavilion of Spain Groundbreaking brochure",
  },
  {
    type: "lead",
    text: "The dominant theme of the Pavilion of Spain will be Spain's influence in the discovery, colonization and independence of America. The pavilion will feature art galleries, fashion shows, concerts, three restaurants and a wine cave. Francisco Javier Caravajal Ferrer of Madrid is the architect and Kelly and Gruzen of New York are consulting architects.",
  },
  {
    type: "source",
    text: "Source: Groundbreaking Brochure, The Pavilion of Spain",
  },
  { type: "h2", text: "Excerpts from transcription of remarks made by Spanish and World's Fair officials at the groundbreaking ceremonies for the Pavilion of Spain, New York World's Fair. Tuesday, June 18, 1963." },
  { type: "h2", text: "DR. ROBERTO DE MENDOZA [Deputy Chief of Protocol]" },
  { type: "p", text: "Excellencies, Mr. Commissioner General, Mr. Moses, Governor Poletti, distinguished guests, ladies and gentlemen. We are here this morning for a very important ceremony -- the laying of the cornerstone for the Pavilion of Spain. This pavilion will bring to Flushing Meadow the essence of Spain -- its history and culture, its achievements and aspirations, its art and folklore, the beauty and fascination of its great cities, resorts, hamlets and countryside, and above all, the happy, gay, stalwart spirit of its people." },
  { type: "p", text: "The first speaker has recently returned with happy memories of Spain, which he loves and has visited often. it is my pleasure to present Governor Poletti, vice president of International Affairs and Exhibits for the New York World's Fair." },
  { type: "h2", text: "GOVERNOR CHARLES POLETTI" },
  { type: "p", text: "Mr. Ambassador, friends. We're getting together for what we believe is a significant purpose: to expand the friendship that we of the World's Fair have formed with the Ambassador, the Commissioner General, the Consul General and all the officials of the Government of Spain ... to expand that friendship into the hearts of millions of Americans. We think it important that the American people, especially the new generations, learn of the great and unique contributions that Spain has made through the centuries, contributions to the civilization of Europe, to our own, to the Far East, to the whole world. We trust that this pavilion, which will be a handsome and attractive and big one, will give the American people a deeper appreciation of the tremendous contributions made in the past by Spain, and an admiration for its people; and more than that, an appreciation of what Span has achieved in the past two decades. Spain has had a stable government, a solid government, a government that has shown great progress, and we Americans are happy to be associated with the people of Spain, not only in this World's Fair, but to be associated with them in achieving our common desires: justice and peace and friendship throughout the world." },
  { type: "p", text: "I thank you all for coming here and I know that we're going to have a very successful Pavilion of Spain. I'm delighted to join you all. Thank you." },
  { type: "h2", text: "DR. DE MENDOZA" },
  { type: "p", text: "Thank you, Governor Poletti. Our next speaker seems to be an extremely young man to have had such a very active and varied career. A member of the Spanish Parliament during the last nine years, he has lectured on international affairs in the Middle and Far East. He is president and cofounder of the International Press Club of Spain. He has headed various Spanish economic and industrial missions to foreign countries. He has twice been a member of the Spanish delegation to the United Nations and was Commissioner General for the Pavilion of Spain at the Brussels World's Fair in 1958. I have the pleasure to present The Honorable Miguel Garcia De Saez, Commissioner General for the Pavilion of Spain at the New York World's Fair." },
  { type: "h2", text: "THE HONORABLE MIGUEL GARCIA DE SAEZ, COMMISSIONER GENERAL OF SPAIN" },
  { type: "p", text: "It is a real pleasure for me to be here today at the cornerstone laying ceremony for our Spanish Pavilion. I would say that it is more than a pleasure -- it is a proud feeling of a man who has been given the opportunity to devote all his activities, his full energy and his enthusiasm to a worthy cause." },
  { type: "p", text: "Spain could not have missed the World's Fair. We could not miss it for two important reasons. The first reason is of a sentimental nature. America is the heart of Spain. The feeling is not new, it comes from the days when Spain had a queen named Isabella, who sold her jewels, who pledge her own property in order that a new world be discovered. Thanks to this queen, in 1492 three small Spanish ships bringing wealth and civilization and culture landed in this wonderful hemisphere. Since then we have always viewed with joy every great American achievement which serves as an additional proof of the magnitude of its people." },
  { type: "p", text: "This Fair is one more of these achievements -- for this one something connected with 1492 had to come to these Fairgrounds. I could not think of anything better than to bring from Spain to this pavilion an historical stone, part of the colossal monument where the glorious queen is resting." },
  { type: "p", text: "The second reason is even more important. Everyone knows how deeply emotions are rooted in our Latin hearts. In spite of this I say that the second of our reasons to attend this Fair is more important than the first and it is so because of the impact that the Fair will have on mankind. We could not resist the purpose of the Fair: Peace through Understanding. I congratulate the leaders of the Fair who have laid down such an inspiring program. When we think of the seventy million visitors viewing the most outstanding developments in every field and epoch of the nations of the world, we are deeply impressed by the admirable progress that will be made along the road of understanding and, perforce, of peace." },
  { type: "p", text: "We are here today for something more than the mere laying of a cornerstone for a new pavilion in new Fair. Our ceremony is more significant than this. We are here to pledge our support to the leaders of the New York World's Fair and to assure them that the Pavilion of Spain enthusiastically adheres to its purpose and will be devoted to the great cause of promoting understanding among the peoples of the world, especially between these two great peoples, the Spaniards and the Americans. Thank you." },
  {
    type: "img",
    src: "spain06.jpg",
    width: 600,
    height: 376,
    alt: "Antonio Garrigues at the groundbreaking",
  },
  { type: "h2", text: "DR. DE MENDOZA" },
  { type: "p", text: "Thank you, Senor Garcia De Saez. Our next speaker also recently returned from Spain with very happy memories. I give you The Honorable Robert Moses, president of the New York World's Fair Corporation." },
  { type: "h2", text: "MR. ROBERT MOSES" },
  { type: "p", text: "Ambassador Garrigues, Commissioner General De Saez, friends. The Government of Spain has placed in the hands of exceptionally able, attractive and enthusiastic representatives the task of planning, building and equipping of a pavilion of surpassing ingenuity, with superb evidences of Spanish genius, culture and enterprise. You speak for a civilization which has placed its seal indelibly upon half the people of this continent. Here at Flushing Meadow you embrace an opportunity to impress the image of the new Spain upon the whole world. Here you will make a profound impression of what is at once an old and a new Iberian civilization. We extend to you from the Fair the sincere hand of friendship and our pledge of fullest cooperation." },
  { type: "h2", text: "DR. DE MENDOZA" },
  { type: "p", text: "Thank you, Mr. Moses. Before presenting our next speaker I should like to introduce some prominent and very distinguished Spanish visitors who are honoring us with their presence today. First, the architect for the Pavilion of Spain, Senor Francisco Javier Carvajal Ferrer; Senor Manuel Ortuno, executive director of the Pavilion of Spain; Senor Joaquin Gutierrez Cano, a director of the World Bank; Senor Fernando Escribano, Commercial Attache of the Spanish Embassy; el Excelentisimo Senor Jaime de Pinies, Deputy Permanent Representative and Charge d' Affaires ad interim to the United Nations; el Excelentisimo Senor Angel Sanz-Briz, Consul General of Sapin; Senor Rafael Heredia, engineer." },
  { type: "p", text: "Our next speaker is a very distinguished diplomat and renowned attorney. He is former Assistant Attorney General and during World War II was legal advisor to the Allied Purchasing Commission in Spain. As a specialist in international finance he has represented very important foreign banking and investment firms in Spain. He has taken a very active and decisive part in negotiations between Spain and the Export-Import Bank, the International Finance Corporation and the Agency for International Development." },
  { type: "p", text: "At the same time he has found time to become a very well-known author and has written many books and articles, published in Spain and abroad, on legal, economic, political and financial subjects. It is my high honor to introduce the Ambassador of Spain, His Excellency Antonio Garrigues." },
  {
    type: "img",
    src: "spain07.jpg",
    width: 600,
    height: 400,
    alt: "Garcia De Saez, Garrigues, Moses and Poletti at the cornerstone laying",
  },
  { type: "h2", text: "HIS EXCELLENCY ANTONIO GARRIGUES, AMBASSADOR OF SPAIN" },
  { type: "p", text: "President Moses, Governor Poletti, distinguished guests and ladies and gentlemen. It is for me a great occasion and a great honor to be here today with so distinguished a gathering and I thank each of you most sincerely for being here. It is a most important occasion for Spain, and your very presence reminds us of our tremendous responsibility in this Fair." },
  { type: "p", text: "I want to express and emphasize, on this occasion, the great friendship between our two countries. We Spaniards are proud of this friendship and we ask that God grant it will always remain and that both countries will always strive for the same goals -- to defend our civilization, to defend our freedom, to defend the values in which both countries so deeply believe." },
  { type: "p", text: "I know that you look forward to a great Pavilion of Spain where a true representation of the very essence of our country is to be displayed. You are expecting to see and hear those things for which we are best known: our works of art, dances which have been handed down from generation to generation and our vibrant music. These are the words of the universal language that the people of all nations understand, and that contribute strongly to a feeling of friendship among countries." },
  { type: "p", text: "I am sure that you are interested not only in our great past, but also in our present achievements in the fields of economics, agriculture, industry, commerce, social security and all the equally important sectors which will be on exhibit to show how Spain is keeping pace with the modern world. This is what you expect to see and I can assure you that you will not be disappointed." },
  { type: "p", text: "It is a comforting thing to know that with this great task before us, we have the magnificent cooperation of Mr. Moses, the Fair's president, of Governor Poletti and of every member of the Fair Corporation. The New York World's Fair presents an excellent opportunity to work towards peace and good will among men and nations. Here, through these exhibits, each country can express its most salient characteristics and make them known to the millions of visitors who will view them. We pledge ourselves to do our utmost to make this Fair a success in every sense of the world. Thank you." },
  { type: "h2", text: "DR. DE MENDOZA" },
  { type: "p", text: "Thank you, Mr. Ambassador. Ladies and gentlemen, the Ambassador of Spain and Mr. Moses will now lay the cornerstone for the Pavilion of Spain." },
  {
    type: "source",
    text: "Source: Portland Cement Association Booklet: Concrete at the Fair",
  },
  {
    type: "img",
    src: "spain130.jpg",
    width: 600,
    height: 298,
    alt: "Architectural rendering of the Pavilion of Spain",
  },
  { type: "h2", text: "Pavilion of Spain" },
  {
    type: "p",
    text: "ARCHITECT: JAVIER CARVAJAL, CONSULTING ARCHITECTS: KELLY & GRUZEN",
  },
  {
    type: "p",
    text: "ENGINEER: LEV ZETLIN ASSOCIATES, PRECAST PANELS BY PLASTICRETE CORPORATION",
  },
  {
    type: "p",
    text: "The precise geometry of the Spanish Pavilion is reminiscent of the early international style of architecture which found great favor with architects on the continent. The pavilion's appearance is enhanced by the projecting pre-cast wall panels which completely enclose the main structure. Some of the exposed-aggregate panels are simple flat rectangles, four feet wide and seven to nine feet high.",
  },
  {
    type: "p",
    text: "The striking shape and scale of the main structural wall units, with their clean shape arises and uniform surface texture, provide a nicely-balanced contrast to the lower walls and interior partitions. Most of the latter are concrete or concrete masonry, and all are covered with portland cement stucco finished in the uneven surface typical of the Spanish style. Inside and out, the Pavilion of Spain will be a delight to see and a treat to visit this summer.",
  },
  {
    type: "img",
    src: "spain131.jpg",
    width: 300,
    height: 76,
    alt: "Concrete at the Fair",
  },
];
