/** Sub-exhibitors from legacy democr05.html. Legacy spellings preserved. */

export const EXHIBITORS_LEFT: string[] = [
  "American Board of Missions to the Jews",
  "American Carpet Institute",
  "Anaconda Aluminum Company",
  "A Nation's Heritage",
  "Art Gallery '64",
  "Michael P. Berk",
  "Book House for Children",
  "Brunswick Corporation",
  "Burrowes Manfuacturing Corporation",
  "Carter's Ink Company",
  "Civic Education Service, Inc.",
  "Collegiate Cap & Gown Company",
  "Confraternity of Christian Doctrine",
  "Contract Hardware",
  "Dawn Bible Students Assoc.",
  "Dunbar Book Company",
  "Edmund Scientific Company",
  "Electronic Directory Processing",
  "Encyclopedia Britannica, Inc.",
  "Endicott Johnson Company",
  "Fedders Corporation",
  "F. E. Compton & Company",
  "Healthway, Inc.",
  "Hamelin-Harvard Assoc. Co.",
  "Jewish Information Society of America",
  "Johnson Service Company",
  "McFadden-Bartell Corporation",
  "Merkons L'Inyonel Cnuch, Inc.",
];

export const EXHIBITORS_RIGHT: string[] = [
  "Metracar, Inc.",
  "Miro Pen Corporation",
  "Newcastle Products (Modernfold)",
  "New York Bible Society",
  "Noble & Noble",
  "Owens Corning Fiberglas",
  "Oxford Furniture Company",
  "Paperbacks at the Fair",
  "Pepsi-Cola Company",
  "Peter Alpi, Incorporated",
  "Phillips & Volcano",
  "Podiatry Society of New York",
  "Portland Cement Assocaition",
  "Regina Products",
  "Seaway Association, Inc.",
  "Shorewood Publishers",
  "Sportservice Corporation",
  "Halsey W. Taylor Comnpany",
  "Torjesen, Inc.",
  "Union of Orthodox Jewish Congreations of America",
  "Universal Educational Enterprises",
  "U. S. Rubber",
  "Paul Venze Assoc, Inc.",
  "Visual Electronics",
  "Wff'n Proof",
  "Wilkie Foundation",
  "Workshop Galler, Inc.",
];
