export type ExhibitorLine = string | { indent: true; text: string };

export const EXHIBITORS_1964_LEFT: ExhibitorLine[] = [
    'Acoustic Research, Inc.',
    'Alfa International Corp.',
    'American Biltrite Rubber Co.',
    'Borden Company',
    'Charles Bloom, Inc.',
    'California Artificial Flower Company',
    'Caloric Corp.',
    'Canada Dry Corporation',
    'Cape Coral Homes',
    'Charles of the Ritz',
    'Coca-Cola Company',
    'Collier & Son Corp., P. F.',
    'Compton & Co., F. E.',
    'Corn Products Co.',
    'Denver Chicago Trucking Co., Inc.',
    'Dorothy Draper Enterprises, Inc.',
    'Dunbar Furniture',
    'Eljer Plumbingware',
    'Encyclopedia Americana',
    'Encyclopedia Britannica',
    'Fieldcrest Mills, Inc.',
    'Fischer & Co.',
    'Gadjo Corporation',
    'Gem Stone Arts Co.',
    'Great Books',
    'Grolier Society, Inc.',
    'Henredon Furniture Co.',
    'Hilton Hotels International',
    'J. R. Williston & Beane, Inc.',
    'Jenn-Air Corporation',
    'Johns-Mansville Corporation',
];

export const EXHIBITORS_1964_RIGHT: ExhibitorLine[] = [
'K & N Demonstrators',
    'Kemper Brothers, Inc.',
    'Kohler Company',
    'Kimball Co., W. W.',
    'Lay-Cee Corp.',
    'Lovable Company, The',
    'Mohasco Industries, Inc.',
    'Morgan Jones, Inc.',
    'National Industries for the Blind',
    'Niagara Therapy Manufacturing Co.',
    'North American Philips',
    'NuTone, Inc.',
    'Oxford Furniture Co. & Fortune Enterprises',
    'Pittsburgh Corning Corp.',
    'Relax-4-Life Company',
    'Resources Council of American',
    { indent: true, text: 'Institute of Designers' },
    'Rockwell Mnaufacturing Company',
    'Schumacher & Co., F.',
    'Stock Manufacturing Corp., A. H.',
    'Schick, Inc.',
    'Spencer Press',
    'Sunshine Biscuits, Inc.',
    'Syracuse China Corp.',
    'Tappan Company',
    'Thermotronics Corporation',
    'U. S. Plywood Corporation',
    'Vent-Air Contact Lens Laboratories',
    'Walston & Co.',
    'Wellington Sears Co.',
    'Westinghouse Electric Corporation',
    'W. T. F. M. (Friendly Frost, Inc.)',
];

export const EXHIBITORS_1965_LEFT: ExhibitorLine[] = [
'Acoustic Research, Inc.',
    'Admiral Corporation',
    'AIDE, Inc.',
    'Alfa International Corp.',
    'America House',
    'American Art Clay Co.',
    'American Biltrite Rubbber Co.',
    'American Knitware & Emblem',
    'American Massage Sales & Mfg. Corp.',
    'American Realty & Petroleum Corp.',
    'American Thread Co.',
    'Anchor Hocking Glass Corp.',
    'Anderson Corporation',
    'Arco Lighting',
    'Automotive After-Market Exposition, Inc.',
    'A. S. Barnes & Co.',
    'Bar-Zim Toy Mfg. Co., Inc.',
    'Beech-Nut Life Savers, Inc.',
    'Berkshire International',
    'Better Living Building Assoc.',
    'Birge Co., Inc., The',
    'Bissell, Inc.',
    'Charles Bloom, Inc.',
    'Book-of-the-Month Club, Inc.',
    'The Borden Company',
    'Suzy Brooks, Inc.',
    'Burnham & Morrill Company',
    'Calart (California Artificial Flower Co.)',
    'California Fashion Creators',
    'Caloric Corporation',
    'Canada Dry Corporation',
    'Mary Carter Paint Company',
    'Charles of the Ritz, Inc.',
    'Clavos, Inc.',
    'Claxton Bakery, Inc.',
    'Coastal Construction Company',
    'The Coca-Cola Company',
    'Coleccion Toledo-House of Spain, Inc.',
    'P.F. Collier, Inc.',
    'F.E. Compton & Company',
    'Congoleum-Nairn Inc.',
    'Consolidated Cigar Corporation',
    'Contour Chair-Lounge Corporation',
    'Culligan, Inc.',
    'Data Patterns, Inc.',
    'Dawson\'s English Pub',
    'Daystrom Furniture',
    'Denver Chicago Trucking Co., Inc.',
    'Dial-O-Matic & Chopper Combination',
    'Dodge Cork Co., Inc.',
    'Dorothy Draper Enterprises, Inc.',
    'Dunbar Furniture Company',
    'E. I. du Pont de Nemours & Company',
    'Eden & Company',
    'Eljer Plumbingware',
    'Encyclopedia Americana',
    'Encyclopedia Britannica, Inc.',
    'Encyclopedia International',
    'Fieldcrest Mills, Inc.',
    'R. A. Fischer & Company',
    'Fortune Enterprises',
    'Fidelis Biblical Guild',
    'Gadjo Corporation',
    'Gartner Enterprises, Ltd.',
    'General Foods Corporation',
    'Giant Umbrella Company',
    'Gift-O-Rama, Inc.',
    'Gilson Uniformas, Inc.',
    'Great Books',
    'The Grolier Society (Book of Knowledge)',
    'Gulf American Land Corporation',
    { indent: true, text: '(Paul Venze Assoc., Inc.)' },
    'Harmon, Eloise',
    'Haskett, Elaine',
    'Hendredon Furniture Company',
    'Hershey Chocolate Corporation',
    'Hobart Manufacturing Company',
    'Hupp Corporation',
    'Industry Serves Youth, Inc.',
    'Institute of High Fidelity',
    'International Telephone & Telegraph',
    'Isabel Scott Fabrics Corp.',
    'I-XL Furniture Company, Inc.',
    'Jaeger & Franzman',
    'Jenn-Air Corporation',
    'Johns Manville Sales Corporation',
    'K & N Demonstrators',
    'Keezer Manufacturing Comnpany',
    'Kemper Brothers, Inc.',
];

export const EXHIBITORS_1965_RIGHT: ExhibitorLine[] = [
'Kenmore Artists, Inc.',
    'Kimball, W. W. Company',
    'Kirk Samuel & Son',
    'L\'Aiglon Apparel, Inc.',
    'Lake Ceramic Studio',
    'Landers, Frary & Clark',
    'Lay Cee Corporation',
    'Lea & Perrins, Inc.',
    'Lilli-Ann Corporation',
    'Loper, Don, Inc.',
    'Lovable Company',
    'Leisure Exhibits, Inc.',
    'Loto, Inc.',
    'Manpower Management Service, Inc.',
    'Margro Jewelry, Inc. (Dyna-Gem)',
    'Marsh Wall Products, Inc.',
    'Mason Candies',
    'Meridian Brick Corporation of New York',
    'Mikado Pearl Corporation',
    'Miller Howard Clock Company',
    'Mohawk Carpet Mills',
    'Monogram Models, Inc.',
    'Morgan-Jones, Inc.',
    'Morton Salt Company',
    'National Documents Committee',
    'National Industries for the Blind',
    'Natural Foods, Inc.',
    'Nevamar Company',
    'Niagra Therapy Corporation',
    'North America Philips Company, Inc.',
    { indent: true, text: '(Norelco)' },
    'NuTone, Inc.',
    'Old Guildford Forge, Inc.',
    'Orfeo-Sonic Corporation',
    'Oster Corporation of Milwaukee, Inc.',
    'Leo J. Overtoom',
    'Oxford Furniture Distributing Company',
    'Pet Milk Company',
    'Pierce & Stevens Chemical Corporation',
    'Pioneer Plastics Corporation',
    'Pittsburg Corning Corporation',
    'Planned Parenthood World Population',
    'Purex Corporation',
    'Relax-4-Life Company',
    'Guy Richardson & Associates, Ltd.',
    'Richelieu Corporation',
    'Ritter Brothers, Inc.',
    'Rockwell Manufacturing Company',
    'Ronkonkoma Wall Paper Corporation',
    'Ronson Corporation',
    'Roux Laboratories, Inc.',
    'Rosenau Brothers, Inc. & Nannette',
    { indent: true, text: 'Manufacturing Company' },
    'Resources Council',
    'Sardeau inc.',
    'Schick Inc.',
    'Schlumberger, Ltd. (Daystrom)',
    'F. Schumacker & Co. (Waverly Fabrics)',
    'Ship & Shore',
    'Spencer Press',
    'A. H. Stock Manufacturing Company',
    'Thomas Strahan Company',
    'Structural Clay Products Institute',
    'Sunbeam Corporation',
    'Sunshine Biscuit, Inc.',
    'Syracuse China Corporation',
    'Syra-Dam Corporation',
    'Tara-San',
    'Taylor Provisions Company, T',
    'Tri-Chemical, Inc.',
    'Tupperware Home Parties',
    'Tycora Textured Yarn Company, The',
    'Union Carbide Corporation',
    'U. S. Automation, Inc.',
    'U. S. Ceramic Tile Company',
    'U. S. Plywood Corporation',
    'Vent Air Contact Lens Company',
    'Waste King Corporation',
    'Wellington Sears company',
    'Westinghouse Electric Company',
    'Whirlpool Corporation',
    'Wiggs, Herbert L.',
    'Wilmar Company, Inc.',
    'Wisconsin Dairyland Fudge Company',
    'World Jewelry Corporation',
    'WTFM Broadcasting Division',
    { indent: true, text: '(Friendly Frost, Inc.)' },
    'Yale & Towne Manufacturing Company',
    'R. E. Yarbrough & Company',
];
