export type MusicSection =
  | { name: string; mode: "composer"; items: { title: string; composer: string }[] }
  | { name: string; mode: "songs"; songs: string[] };

export const FOUNTAIN_SHOW_MUSIC: MusicSection[] = [
  {
    name: "GREAT MASTERS",
    mode: "composer",
    items: [
      { title: "Romeo & Juliet (Our Love)", composer: "Tchaikowsky" },
      { title: "Fifth Symphony (Can This Be Moon Love)", composer: "Tchaikowsky" },
      { title: "Piano Concerto (Tonight we Love)", composer: "Tchaikowsky" },
      { title: "Liebestraum", composer: "Liszt" },
      { title: "Notturno from II String Quartet (Kismet-This is My Beloved)", composer: "Borodin" },
      { title: "Polonaise in A (Til the End of Time)", composer: "Chopin" },
      { title: "Claire de Lune", composer: "Debussy" },
      { title: "Polovetzian Dances from \"Prince Igor\" (Kismet-Stranger in paradise)", composer: "Borodin" },
      { title: "Waltz of the Flowers -- from the Nutcracker Suite", composer: "Tchaikowsky" },
      { title: "Moonlight Sonata", composer: "Beethoven" },
      { title: "Minute Waltz", composer: "Chopin" },
      { title: "\"Ride of the Valkyries\"", composer: "Wagner" }
    ],
  },
  {
    name: "BROADWAY",
    mode: "composer",
    items: [
      { title: "No Business Like Show Business", composer: "Irving Berlin" },
      { title: "Always", composer: "Irving Berlin" },
      { title: "I Love a Piano", composer: "Irving Berlin" },
      { title: "Alexander's Ragtime Band", composer: "Irving Berlin" },
      { title: "Tea For Two", composer: "Vincent Youmans" },
      { title: "Rose Marie", composer: "Rudolf Friml" },
      { title: "Ol' Man River", composer: "Jerome Kern" },
      { title: "Make Believe", composer: "Jerome Kern" },
      { title: "Smoke Gets in Your Eyes", composer: "Jerome kern" },
      { title: "Hallelujah", composer: "Vincent Youmans" },
      { title: "I 've Got Rythm", composer: "George Gershwin" },
      { title: "Fascinating Rhythm", composer: "George Gershwin" },
      { title: "Lady Be Good", composer: "George Gershwin" },
      { title: "Falling In Love", composer: "Rodgers and Hart" },
      { title: "Dancing in Dark", composer: "Arthur Schwartz" },
      { title: "Easy to Love", composer: "Cole Porter" },
      { title: "Without a Song", composer: "Vincent Youmans" },
      { title: "With A Song in My Heart", composer: "Rodgers and Hart" },
      { title: "Strike Up the Band", composer: "George Gershwin" },
      { title: "Over the Rainbow", composer: "Harold Arlen" },
      { title: "Someone to Watch Over Me", composer: "George Gershwin" },
      { title: "They Say That Falling in Love is Wonderful", composer: "Irving Berlin" },
      { title: "Around the World in 80 Days", composer: "Victor Young" },
      { title: "You and the Night and the Music", composer: "Arthur Schwartz" },
      { title: "Begin the Beguine", composer: "Cole Porter" },
      { title: "Night and Day", composer: "Cole Porter" },
      { title: "What a Beautiful Morning", composer: "Rodgers and Hammerstein" },
      { title: "Some Enchanted Evening", composer: "Rodgers and Hammerstein" },
      { title: "If I Loved You", composer: "Rodgers and Hammerstein" },
      { title: "Rhapsody in Blue", composer: "George Gershwin" }
    ],
  },
  {
    name: "FAMILIAR MELODIES",
    mode: "composer",
    items: [
      { title: "Prelude - \"Lohengrin\"", composer: "Wagner" },
      { title: "New World Symphony", composer: "Dvorak" },
      { title: "Lost Chord", composer: "Sir Arthur Sullivan" },
      { title: "Evening Star - Tannhauser", composer: "Wagner" },
      { title: "Meditation from \"Thais\"", composer: "Massenet" },
      { title: "Scherzo from 6th Symphony", composer: "Tchaikowsky" },
      { title: "Traumerei", composer: "Schumann" },
      { title: "Pastorale Symphony", composer: "Beethoven" },
      { title: "Finlandia", composer: "Sibelius" },
      { title: "Symphony No. 1", composer: "Brahms" },
      { title: "Arioso", composer: "Bach" },
      { title: "Pilgrim's Chrous - \"Tannhauser\"", composer: "Wagner" }
    ],
  },
  {
    name: "COLLEGE SHOW",
    mode: "songs",
    songs: [
      "Gaudeamus Igitur",
      "Go U. Northwestern",
      "Tavern in the Town",
      "Lord Goeffery Amherst",
      "Aura Lee",
      "Notre Dame Victory March",
      "Stein Song",
      "On Wisconsin",
      "Whiffenpoof Song",
      "The Palisades",
      "Rambling Wreck from Georgia Tech",
      "Roar Lion Roar",
      "Sweetheart of Sigma Chi",
      "Roll on Tulane",
      "Boola Boola",
      "Song of Troy",
      "Across the Field",
      "Michigan Victors",
      "The Cannon Song",
      "Eyes of Texas Are Upon You",
      "The Ram Song",
      "Far Above Cayuga's Waters",
      "Fair Harvard"
    ],
  },
  {
    name: "PATRIOTIC SHOW",
    mode: "songs",
    songs: [
      "Yankee Doodle",
      "Mademoiselle from Armentiers",
      "Spirt of '76",
      "Madelon",
      "Hail Columbia",
      "Keep the Home Fires Burning",
      "Washington's March",
      "How I Hate to Get Up in the Morning",
      "Hail to the Chief",
      "It's a Long Way to Tipperary",
      "Columbia, the Gem of the Ocean",
      "Over There",
      "Johnny Comes Marching Home",
      "American Patrol",
      "Yellow Rose of Texas",
      "Semper Fidelis",
      "Tramp, Tramp, Tramp",
      "National Emblem",
      "Dixie",
      "Stars & Stripes Forever",
      "Glory, Glroy, Halleluljiah",
      "Halls of Montezuma",
      "Yankee Doodle Dandy",
      "Caissons Go Rolling Along",
      "It's a Grand Old Flag",
      "Anchors Aweigh",
      "Rose of Picardy",
      "Semper Paratis",
      "K-K-K-Katy",
      "Wide Blue Yonder",
      "Long, Long Trail",
      "My Land, Your Land",
      "There are Smiles",
      "God Bless America",
      "Pack Up Your Troubles"
    ],
  },
];
