export type ScriptBlock =
  | { kind: "cue"; text: string }
  | { kind: "speech"; text: string }
  | { kind: "song"; lines: string[] };

export const SCRIPT_1964: ScriptBlock[] = [
  { kind: "cue", text: "Voice of Hal Holbrook, Narrator:" },
  {
    kind: "speech",
    text: "Please hook your seat straps. The speakers on either side of you are movable. Please adjust them so that you can hear clearly. Settle back. Make yourself comfortable. Thank you.",
  },
  {
    kind: "speech",
    text: "The 700,000 men and women of the Bell System welcome you aboard. We're very happy to have you with us and we hope you'll enjoy your trip.",
  },
  { kind: "cue", text: "The Bell System Chorus (sung):" },
  {
    kind: "song",
    lines: [
      "Wherever you live,",
      "Whoever you are,",
      "Sing Oh! Hello!",
      "Hello there. Hello!",
      "I float on the sea.",
      "I drift on a star.",
      "Hello! Hello there. Hello.",
      "Out of your county and city and state.",
      "North from the Gulf to the Bering Straits.",
      "Atlantic. Midwest. The Golden Gate.",
      "Hello. Hello there! Hello!",
      "Yes, Hello.",
      "How are you?",
      "From Miami to Omaha.",
      "Raleigh to Wichita.",
      "Call San Diego, El Paso and Buffalo",
      "on to Chicago to say,",
      "Hello!",
    ],
  },
  { kind: "cue", text: "Voice of Hal Holbrook, Narrator:" },
  {
    kind: "speech",
    text: "You know this ride you're taking never ends. At least, the story it tells never ends and it seems it never will. We don't even know exactly when the story began but we know where: in the restless, seeking human spirit which in all times takes on the gigantic task of changing the world for the better.",
  },
  {
    kind: "speech",
    text: "The story is a search for secrets buried deep in nature long before time. Secrets hidden, dark and silent, beyond the reach of man's limited senses. Secrets magical enough to make mountains, deserts, oceans, vanish! Powerful enough to shatter the barriers of time and distance that separate man.",
  },
  {
    kind: "speech",
    text: "Now, let's meet the hero of the story: you. Yes, you! People. Everybody. Mankind. And this fellow you're looking at now, him, is going to be you, mankind, in this story. You have put the world at your fingertips. Whenever you please, you can come as close as a whisper to anyone. Anywhere.",
  },
  {
    kind: "speech",
    text: "But only a moment ago, as nature tells time, you were not so tall. In the ancient wilderness the sound of man is only man-sized. Finding food is not a sport. Survival depends on sharing it. Life is living together. Life is reaching others. Life is communication.",
  },
  {
    kind: "speech",
    text: "By accident you discover a language that talks louder than your loudest shout. And because you can think, you think out other, better, farther-reaching languages. You are beginning to shrink the world. There are things you want remembered. So crudely and laboriously, you go on record with a language you copy from nature. You invent history and art.",
  },
  {
    kind: "speech",
    text: "Being human you're not content and you worry and twist and squeeze your picture language into a shorthand with a symbol for ideas and things. You achieve the marvel of the written word. Words carved with a chisel. Beaten into clay. Words on wax. Parchment. Paper. Words to read. Words that can be fit into a private, personal package, a letter, and sent as far and as fast as two feet can carry them.",
  },
  {
    kind: "speech",
    text: "But hand-made words take too long. There's too much to say. To tell. To be remembered. You figure out machine-made words printed into books. Knowledge you can send anywhere. Everywhere.",
  },
  {
    kind: "speech",
    text: "And still another language: the no-mistake language you learned from your ten fingers. The language of plus and minus and equals. Numbers. Mathematics that can take the measure of the world.",
  },
  {
    kind: "speech",
    text: "Your private messages go as far and as fast as four feet can gallop. You know more, but it's not enough. It's never enough. You learn to read the language of nature's laws. You invent science. To question, to answer, to question, etc. etc.",
  },
  {
    kind: "speech",
    text: 'Man-sized becomes big enough to take a fierce and hostile power by the tail. You domesticate electricity to carry your messages in the language of "short and long".',
  },
  {
    kind: "speech",
    text: 'You study how your voice speaks and how your ear hears and you teach electricity to speak. Speak your voice. Speak Alexander Graham Bell\'s seven simple words, "Mr. Watson. Come Here! I want you!" Only seven words, but enough to change the world forever. Enough to achieve the telephone.',
  },
  {
    kind: "speech",
    text: "From these seven seed words have grown the nerve system of our nation linking people instantly together on many-laned highways of cables and microwaves. From home-to-home. Office-to-office. From person-to-person, in privacy.",
  },
  {
    kind: "speech",
    text: "A network which echoes those first seven words in television and radio programs and in the dialogue of data machines.",
  },
  {
    kind: "speech",
    text: "Today that first short wire has been stretched long enough to reach under oceans to other lands and your voice circles the globe high above the skies on radio waves, tying the far-places of the earth together. Drawing men toward understanding. Toward the hope of peace.",
  },
  {
    kind: "speech",
    text: "Yes. You have the world at your fingertips. It's been cut down to man-sized. But you're only human. You can't help looking farther than here and now. You can't help reaching for tomorrow. Up to *Telstar* and beyond.",
  },
  {
    kind: "speech",
    text: "You have come a long, hard way out of the deep, dark valleys of the past. But the end, the stopping place, is not yet. Is not ever. The heart knows no horizon. The human journey is always changing and always the same. Yesterday's mountain peaks, once attained, become today's valleys. And from this high valley we have gained today we look up toward tomorrow.",
  },
  { kind: "cue", text: "The Bell System Chorus (sung):" },
  {
    kind: "song",
    lines: [
      "Come, gather the world of voices,",
      "riding out over the sea.",
      "Through time and space and ages",
      "building the golden years.",
      "Sing out! Beyond all the valleys.",
      "Sing out your hymns and songs.",
      "To call all the lands and nations.",
      "To speak with friendly tongue.",
      "To speak with friendly tongue.",
      "",
      "Come up from the valley children",
      "Out of the shadows of night.",
      "Come up with love and longing",
      "into the place of light.",
      "Come up! Come up from the valleys.",
      "Come up from doubt and care.",
      "Come up from the valley children",
      "and breathe the morning air.",
      "And breathe the morning air.",
      "",
      "Oh beautiful, for spacious skies.",
      "For amber waves of grain.",
      "For purple mountains majesty",
      "above the fruited plain.",
      "America! America!",
      "God shed his grace on thee.",
      "And crown thy good",
      "with brotherhood",
      "from sea to shining sea.",
    ],
  },
  { kind: "cue", text: "Voice of Hal Holbrook, Narrator:" },
  {
    kind: "speech",
    text: '"Tomorrow" is a promise we make to our children. Given in love. Received in faith. A pledge to give them a better, fuller, richer life than ours.',
  },
  {
    kind: "speech",
    text: "To the promise of bright tomorrows for all children, we are all dedicated. For us in the Bell System the future has already begun because our only job is to serve you better today and even better tomorrow.",
  },
  { kind: "cue", text: "The Bell System Chorus (sung):" },
  {
    kind: "song",
    lines: [
      "Whoever you are,",
      "Whatever you do,",
      "Sing Oh! Hello!",
      "Hello there. Hello!",
      "Arabia, Guam,",
      "Alaska, Peru.",
      "Hello! Hello there. Hello.",
      "[Greetings are sung in many languages]",
      "Hello. Hello there! Hello!",
      "Yes, Hello.",
      "How are you?",
      "[Greetings are sung in many languages]",
      "Hello!",
    ],
  },
  { kind: "cue", text: "Voice of Hal Holbrook, Narrator:" },
  {
    kind: "speech",
    text: "Thank you for being with us. We hope you've enjoyed the trip. There's more to see downstairs. We invite you to join us there.",
  },
];

export const SCRIPT_1965: ScriptBlock[] = [
  { kind: "cue", text: "Voice of the Telephone Operator:" },
  {
    kind: "speech",
    text: "Hello. Please hook your seat belt. Notice the speakers left and right? They're movable! Just move them where you can hear best, OK? Now settle back and get comfortable.",
  },
  {
    kind: "speech",
    text: 'More than three-quarters of a million men and women in the Bell System welcome you aboard. Different view of the Fair from here, isn\'t it? While you\'re looking it over you\'ll be riding up a gentle incline, around a corner. The lights will dim and you\'ll travel into our show at the speed of ... well ... about 20,000 years a minute -- "story" time that is! We\'re happy to have you with us and we hope you enjoy your ride.',
  },
  { kind: "cue", text: "The Bell System Chorus (sung):" },
  {
    kind: "song",
    lines: [
      "Wherever you live,",
      "Whoever you are,",
      "Sing Oh! Hello!",
      "Hello there. Hello!",
      "I float on the sea.",
      "I drift on a star.",
      "Hello! Hello there. Hello.",
      "Out of your county and city and state.",
      "North from the Gulf to the Bering Straits.",
      "Atlantic. Midwest. The Golden Gate.",
      "Hello. Hello there! Hello!",
      "Yes, Hello.",
      "How are you?",
      "From Miami to Omaha.",
      "Raleigh to Wichita.",
      "Call San Diego, El Paso and Buffalo",
      "on to Chicago to say,",
      "Hello!",
    ],
  },
  { kind: "cue", text: "Voice of Narrator:" },
  {
    kind: "speech",
    text: 'You ought to know this ride you\'re on never ends. Everybody\'s in the dark about how the story\'ll end. Your guess is as good as any. It\'s a "To be continued" "Adventure" "Mystery" "Detective" story about how in the world the world got to fit into your backyard!',
  },
  {
    kind: "speech",
    text: "Some of the clues were always there in all the sights and sounds of nature right under everybody's nose and eyes and ears. Others were hidden deep and dark before time began. We're still looking for them. Anyway, nobody knew a clue was a clue until ... well, but that comes later.",
  },
  {
    kind: "speech",
    text: "First, meet our hero. Right there in front of you. Look familiar? Yes, you. People. Now, say hello to this happy fellow who's taking your place. He's going to be all you heroes in this story. Today, you have the world at your fingertips. A touch. A turn. And you're close as a whisper to anyone. Anywhere.",
  },
  {
    kind: "speech",
    text: "But go back only a moment ago, as nature tells time. The best you can do is a skimpy \"whoop and a holler.\" You can't reach any further even though your life depends on it. And your life *does* depend on it. People need people.",
  },
  {
    kind: "speech",
    text: "Because you need people, you beat out a language that talks louder than you can holler. And you learn to write on the sky in smoke, puff by puff. You've taken your first tiny, tremendous step . Everything to come begins here. Things happen you want remembered. So you go on record with a language you copy from nature. You don't know it but you've just invented history and art.",
  },
  {
    kind: "speech",
    text: 'Being more human than anybody you\'re not satisfied \'till you\'ve squeezed your picture language into shorthand. Into "A B C." Into scrawls and scratches that stand for ideas. Into the biggest thing yet: The Written Word. Chiseled. Chipped. Chopped words. Pounded. Painted. Penned. Parchmented. Papyrused. Papered. Words to read. Words to seal into a private, personal package, a letter, to send only as fast and as far as two feet can go.',
  },
  {
    kind: "speech",
    text: "But hand-made words take forever. Presto! A couple of dozen thousand years: Machine made words pressed out. Printed into books to learn from. To send anywhere and everywhere.",
  },
  {
    kind: "speech",
    text: "Another language coming up. Clue? Count your fingers, one to ten. Got it? Number language. Plus and minus and divide by. Arithmetic. Mathematics to measure the world.",
  },
  {
    kind: "speech",
    text: 'Your letters, love and otherwise, still go only as fast and far as four feet can gallop. You\'re asking nature silly questions like "Why don\'t things fall *up*?" "What color is light?" "Why isn\'t north south?" Foolish questions that invent science.',
  },
  {
    kind: "speech",
    text: "You're hero enough to pull wild lightening down from the sky. And tame it. And teach it. Teach electricity to carry your messages in the language of short and long sounds.",
  },
  {
    kind: "speech",
    text: 'More questions: "How does the voice speak?" "What makes the ear hear?" Answer in just seven words: "Mr. Watson. Come Here! I want you!" By your genius, hard work, and a lucky accident, you\'ve taught electricity to speak your speech over Alexander Graham Bell\'s little box of wires. The tele (Greek for "far off") phone (voice). Telephone.',
  },
  {
    kind: "speech",
    text: "Bell's seven words, seven seeds, sprouting out from home-to-home. From person-to-person. Reaching your neighbor across the street, the store around the corner, the factory way at the other end of town. A growing network growing people together.",
  },
  {
    kind: "speech",
    text: "Changing days to seconds. Miles to inches. A living, breathing, speaking network of cables and microwaves, television, radio and machines talking to machines. A people network that's turned our nation into a neighborhood.",
  },
  {
    kind: "speech",
    text: "Today, Alexander Graham Bell's first short wire stretches under *oceans* to our most distant cousins in the family of man. We're meeting voice to voice in peace. Close as a handshake. Coming closer to the hope of lasting peace.",
  },
  {
    kind: "speech",
    text: "You. You. And you! You have come a long, long way from yesterday. Yes, you have the world at your fingertips. But you can't help reaching for tomorrow. Up to *Telstar* and beyond.",
  },
  { kind: "cue", text: "The Bell System Chorus (sung):" },
  {
    kind: "song",
    lines: [
      "Come, gather the world of voices,",
      "riding out over the sea.",
      "Through time and space and ages",
      "building the golden years.",
      "Sing out! Beyond all the valleys.",
      "Sing out your hymns and songs.",
      "To call all the lands and nations.",
      "To speak with friendly tongue.",
      "To speak with friendly tongue.",
      "",
      "Come up from the valley children",
      "Out of the shadows of night.",
      "Come up with love and longing",
      "into the place of light.",
      "Come up! Come up from the valleys.",
      "Come up from doubt and care.",
      "Come up from the valley children",
      "and breathe the morning air.",
      "And breathe the morning air.",
    ],
  },
  { kind: "cue", text: "Voice of Narrator:" },
  {
    kind: "speech",
    text: "The ruby laser beam may light the way to the future out of the deep, dark valleys of the past. But the end of the human journey is not yet. Is not ever. The heart knows no horizon. Yesterday's mountain peaks become today's valleys. And from this high valley we have gained today we look up toward tomorrow.",
  },
  {
    kind: "speech",
    text: '"Tomorrow" is a promise we make to our children. Given in love. Received in faith. A pledge to give them a better, fuller, richer life than ours. A bright tomorrow for all children.',
  },
  { kind: "cue", text: "The Bell System Chorus (sung):" },
  {
    kind: "song",
    lines: [
      "Oh beautiful, for spacious skies.",
      "For amber waves of grain.",
      "For purple mountains majesty",
      "above the fruited plain.",
      "America! America!",
      "God shed his grace on thee.",
      "And crown thy good",
      "with brotherhood",
      "from sea to shining sea.",
    ],
  },
  { kind: "cue", text: "Voice of Narrator:" },
  {
    kind: "speech",
    text: "Tomorrow's heroes. Tomorrow's heroines. Who's adventures may take them into worlds farther than the stars. Farther than the imagination. May all the days of your journey be filled with happiness.",
  },
  {
    kind: "speech",
    text: "Our story has reached another new beginning. The next chapters of the human journey are being written now. For us in the Bell System the future has already begun. Each new day is a challenge to our science, our technology and our skills. Our only job, however, is to serve you well today and even better tomorrow.",
  },
  { kind: "cue", text: "The Bell System Chorus (sung):" },
  {
    kind: "song",
    lines: [
      "Whoever you are,",
      "Whatever you do,",
      "Sing Oh! Hello!",
      "Hello there. Hello!",
      "Arabia, Guam,",
      "Alaska, Peru.",
      "Hello! Hello there. Hello.",
      "[Greetings are sung in many languages]",
      "Hello. Hello there! Hello!",
      "Yes, Hello.",
      "How are you?",
      "[Greetings are sung in many languages]",
      "Hello!",
    ],
  },
  { kind: "cue", text: "Voice of the Telephone Operator:" },
  {
    kind: "speech",
    text: "There's a lot more to see downstairs where you can watch the magic of today turning into tomorrow right before your eyes. As you get out of your chair and step onto the moving walk, you will reach an escalator that will take you down. Thanks for being with us! We hope you enjoyed your ride.",
  },
];
