import type { Metadata } from "next";
import Image from "next/image";
import { IllinoisTopicPage } from "@/components/IllinoisTopicPage";
import styles from "@/styles/illinoisTopic.module.css";

export const metadata: Metadata = {
  title: "Mr. Lincoln Goes to Disneyland — Illinois — nywf64.com",
  description:
    "Mr. Lincoln Goes to Disneyland — Illinois Pavilion — 1964/1965 New York World’s Fair on nywf64.com.",
};

export default function Illinois13Page() {
  return (
    <IllinoisTopicPage
      titleId="illinois13-title"
      titleNode={
        <>
          <em>Mr. Lincoln Goes to Disneyland</em>{" "}
          <span className={styles.titleBarSub}>... an essay by Eric Paddon</span>
        </>
      }
      previousHref="/illinois12"
      nextHref="/illinoisoverview"
      wide
    >
      <div className={styles.bodyMaroon}>
          <p className={styles.bodyMaroon}>Of the four exhibits that Walt Disney developed for the New York World's Fair, "Great Moments With Mr. Lincoln" was the one most dear to him. It reflected his deep love of American history. Yet, as Paul Anderson has noted, this love of history was anything but a mere starry-eyed reverent nostalgia for the past. "Walt felt that a great deal could be learned from history. He had long held the belief that people should recognize the remarkable influence of historical events in our lives; as he saw it, this was fundamental for the future development of the nation. As a result he was constantly searching for new and inviting ways to help Americans become more aware of history's significance and lessons."</p>
          <p className={styles.bodyMaroon}>Perhaps it was no surprise then that Disney's passion for "Great Moments With Mr. Lincoln" and what it symbolized would make it the first of the Disney World's Fair exhibits to open at the Anaheim theme park. In fact, "Great Moments With Mr. Lincoln" was unique in that the Disneyland version of the show opened on July 17, 1965, even as the Fair's version continued to play in New York! Housed in a handsome new facility on Main Street, the Opera House, the production was not completely identical to the Fair's. A new pre-show, "The Lincoln Story." replaced the Fair's which dealt with Illinois. This featured Royal Dano as Lincoln narrating an autobiographical sketch of himself expanding further on the speech that closed out the original pre-show. A number of newly commissioned murals illustrated the presentation. Guests then entered the theater to see the same main show presentation from the Fair, with Paul Frees narrating the introduction followed by the Audio Animatronic Lincoln figure's speech.</p>
          <p className={styles.bodyMaroon}>As "Great Moments With Mr. Lincoln" entertained audiences in California, advancements in Audio-Animatronic technology made it possible to resurrect the original idea behind the Lincoln show for inclusion in the new Disney World park in Florida which opened in 1971. The "Hall Of Presidents" would, according to the original 1956 Disney vision of the "One Nation Under God" presentation, feature life-size figures of all American presidents for its closing sequence. Royal Dano once again performed the voice of Lincoln and delivered a speech in the climax that incorporated many of the same quotations featured in the "Great Moments" show. "Hall" was an immediate success, ranking as one of the most popular exhibits in the new theme park in its first year of operation. Just as a single Audio Animatronic figure of a great figure in American history had enthralled audiences in 1964, now there were 36 such figures of every President from Washington to Nixon on the stage to show how much Audio Animatronic technology had advanced in just seven years. While the Lincoln figure was the only one that spoke, his colleagues were never static, frequently shifting about and seemingly making asides to each other.</p>
          <p className={styles.bodyMaroon}>Ironically, the immediate success of "Hall Of Presidents" in Florida may have convinced Disney management that the original attraction in California had taken on a dated aura by featuring just one Audio Animatronic figure and would no longer be impressive to a new generation of audiences that would demand something more elaborate. The decision was made to close the attraction in January, 1973, the same year that another Fair transplant, the Carousel Of Progress, played for the last time at Disneyland. But while the Carousel was merely changing locales for a move to Disney World in Florida, the closing of "Great Moments With Mr. Lincoln" was intended to be permanent. The Main Street Opera House would now be the home of "The Walt Disney Story," a movie that used vintage recordings of Walt Disney telling his life story set to family photos and archival film footage. The main building would now house Disney related memorabilia. The Disney company thought so highly of this tribute to the founder that they also opened the attraction in Florida as well in a specially constructed building on Main Street.</p>
          <p className={styles.bodyMaroon}>Disney management was taken completely by surprise when they received a volume of complaints from customers who were furious that "Great Moments With Mr. Lincoln" had been closed. The general tone of these angry complaints was that, in removing the Lincoln show, Disney management was being both unpatriotic and somehow disrespectful of Walt Disney's memory since Walt had been so involved in making the show possible (an ironic charge in light of the fact that the replacement show was about Walt). The complaints continued to the point where Disney executives felt they had to give in and bring "Great Moments With Mr. Lincoln" back. But because so much had been invested in "The Walt Disney Story" it was decided to combine both productions together into a new attraction: "The Walt Disney Story, Featuring Great Moments With Mr. Lincoln." The foyer and pre-show would continue to spotlight Walt and the theater would give viewers both "The Walt Disney Story" movie (cut down from its original 28 minute length) followed by the return of the main Lincoln show which now featured a number of new Lincoln quotations lifted from the "Hall Of Presidents" show in Florida. This somewhat awkward melding of the two shows, which amounted to a lengthy running time, opened in June, 1975.</p>
          <p className={styles.bodyMaroon}>By 1984 "The Walt Disney Story" movie had been eliminated completely from the theater (Disney memorabilia continued to be featured in the main building) while the Lincoln show received an upgrade with a new, more advanced Audio Animatronic Lincoln figure. Less effective was the decision to drop "Battle Hymn Of The Republic" from the climax in favor of the song "Golden Dream" from the American Adventure Pavilion at EPCOT Center in Florida. Another element incorporated into the show from the EPCOT attraction was the song "Two Brothers" which dealt with the saga of brothers fighting on opposite sides of the Civil War. This revised version, which continued to feature the original Paul Frees narration and Royal Dano orations from the World's Fair soundtrack, ran for the next seventeen years.</p>
          <p className={styles.bodyMaroon}>During that time, "Great Moments With Mr. Lincoln" was frequently rumored to be closed down, since by this time attendance levels were anything but high. The Lincoln show was the kind of attraction from an earlier era of Disney history where the guests were expected to have a reasonably long attention span for a program lasting more than ten minutes. Now, with new attractions opening in Disney parks that stressed fast-moving thrill rides, "Great Moments With Mr. Lincoln" was the kind of production that, fairly or not, could easily try the patience of modern-day youth. One rumor in 1990 had the attraction being closed to make way for a show featuring Jim Henson's Muppets. But as was the case in 1973, enough letters of complaint managed to convince Disney management to keep Mr. Lincoln open, low attendance notwithstanding.</p>
          <p className={styles.bodyMaroon}>In 2001, the show was closed, but this time to give it a major overhaul that would hopefully allow a Lincoln attraction to endure in Disneyland for the long-term by appealing to younger viewers. The new program that opened in July, 2001 was a watershed moment because the last links to the attraction's origins at the New York World's Fair were severed for good with the elimination of the remaining Frees and Dano vocals.</p>
          <p className={styles.bodyMaroon}>Instead of focusing on Abraham Lincoln's life, the focus was now more on the Civil War and a number of technological gimmicks were added to make the attraction more interactive for the visitor (especially through the use of headsets designed to create a bigger sound experience). The pre-show greeted visitors to Civil War photographer Matthew Brady who told the audience that for the show they would be taking the identity of a Union private named Cunningham. Then they were taken into a new main show that saw Private Cunningham meeting Lincoln and Frederick Douglass at the White House before being transported to Gettysburg for the battle where Private Cunningham (the viewer) is wounded in action but eventually recovers. The program concluded with Lincoln reciting the Gettysburg Address (which ironically had never been part of any previous Lincoln show, though it had been included on the expanded 1964 LP recording) to the strains of "Battle Hymn Of The Republic." This newest version was so far removed from its predecessors that the program itself was renamed "More Great Moments With Mr. Lincoln."</p>
          <p className={styles.bodyMaroon}><em>This overhaul at the very least has guaranteed that a Lincoln attraction will continue in Disneyland for some time to come. But it is perhaps safe to say that it no longer truly represents an enduring World's Fair legacy in terms of actual program content. It also represents an interesting comment on how tastes and perceptions have changed in the 40 years since the Fair. The original "Great Moments With Mr. Lincoln" was a revolutionary breakthrough for not just the Disney Corporation and the future of their theme park attractions, but Robert Moses had even felt that the talking Lincoln figure represented the greatest single thing to be found at the Fair next to Michelangelo's Pieta. Today though, audience tastes have changed to the point where more elaborate gimmicks are needed to hold their attention along with, unfortunately, a shorter program length which hinders the opportunity to do more justice to the subject matter. Based on a reading of the current Lincoln program script, one doesn't find the care of using Lincoln's words to get audiences to think about how his words still have relevance to the concerns of today. In a day and age where the September 11, 2001 terrorist attacks have left us feeling uneasy about our security as a nation, Lincoln's 1838 words from the "Great Moments" program still have much to offer:</em></p>
          <p className={styles.bodyMaroon}>"Shall we expect some transatlantic military giant, to step the ocean, and crush us at a blow? Never! All the armies of Europe, Asia and Africa combined, could not by force, take a drink from the Ohio or made a track on the Blue Ridge, in a trial of a thousand years. At what point then is the approach of danger to be expected? I answer, if it ever reach us, it must spring up amongst us. It cannot come from abroad. If destruction be our lot, we ourselves must be its author and finisher. As a nation of free men, we must live through all times, or die by suicide."</p>
          <p className={styles.bodyMaroon}>By contrast, "More Great Moments With Mr. Lincoln" ultimately is concerned more with visual flash and razzle-dazzle to bring the past alive, and only offers Lincoln reciting his most eloquent speech, but is nonetheless one that has little relevance to the matters of our present age, which is why Disney avoided using it in the first place. Even one who leaves impressed by the experience is not likely to walk away with any sense of "history's significance and lessons.......for the future development of our nation." Without this critical facet, the forward-thinking impulse of the original attraction, which neatly aligned with the forward-thinking impulse of the New York World's Fair itself, has been lost. For that reason, and not the mere replacement of the last portions of the original soundtrack, the perpetuation of a Lincoln attraction in Disneyland can no longer be seen as a true, enduring legacy of the New York World's Fair itself.</p>
          <figure className={styles.figure}>
            <Image src="/images/illinois13/ill44.jpg" alt="ill44.jpg" width={481} height={410} className={styles.photoImg} unoptimized />
            <p className={styles.source}>SOURCE: 1967 Disneyland Souvenir Book © The Walt Disney Company</p>
          </figure>
          <figure className={styles.figure}>
            <p className={styles.caption}>A scene from "Hall Of Presidents" featuring Abraham Lincoln at Walt Disney World in Florida</p>
            <Image
              src="/images/illinois13/ill45.jpg"
              alt={'A scene from "Hall Of Presidents" featuring Abraham Lincoln at Walt Disney World in Florida'}
              width={400}
              height={261}
              className={styles.photoImg}
              unoptimized
            />
            <p className={styles.source}>SOURCE: Disney World Postcard c. 1971 © The Walt Disney Company</p>
          </figure>
          <figure className={styles.figure}>
            <p className={styles.caption}>A Disneyland poster advertises the attraction, here sponsored by Lincoln Savings.</p>
            <Image src="/images/illinois13/ill46.jpg" alt="A Disneyland poster advertises the attraction, here sponsored by Lincoln Savings." width={202} height={297} className={styles.photoImg} unoptimized />
            <p className={styles.source}>SOURCE: eBay Auction © The Walt Disney Company</p>
          </figure>
      </div>
    </IllinoisTopicPage>
  );
}
