import Image from "next/image";
import styles from "./johwax16.module.css";

export function Johwax16ArticleContent() {
  return (
    <>
      <h2 className={styles.headline}>World&apos;s Fair Jewel Gets a New Setting</h2>
      <p className={styles.subhead}>
        Golden Rondelle Theater will be brought to Racine after successful run at
        the New York Fair in 1964-65
      </p>
      <figure className={`${styles.figure} ${styles.floatRight}`}>
        <Image src="/images/johwax16/johwax36.jpg" alt="" width={221} height={458} className={styles.inlineArt} unoptimized />
      </figure>
      <p className={styles.body}>AFTER FOUR YEARS of planning and two seasons of public exhibition, the New York World's Fair is over. But the fair will long be remembered as one of the greatest spectacles and achievements of this century -- a billion dollar tribute to man's imagination, ingenuity and desire for knowledge and understanding.</p>
      <p className={styles.body}>The bright lights, color, excitement and splendor that attracted more than 51 million persons are gone. Most of the 175 pavilions and structures which dotted the fairgrounds have been demolished. All that remains from the glory of the fair are the stainless steel Unisphere, symbol of the fair, the Port Authority building with its heliport, the New York City pavilion, the Federal building and the New York state pavilion dominated by its giant towers. The 646 acres that comprised the fair are some day to be transformed into a huge park and recreation center for the city of New York.</p>
      <p className={styles.body}>Other buildings have been sold and moved. The Wisconsin state pavilion was brought to Wisconsin where it was sold to a radio station in the northern part of the state. The Austrian A-building and the Lowenbrau Gardens will be used at New England ski resorts. The beautiful Spanish pavilion, considered one of the finest buildings at the fair, is moving to St. Louis where it will be part of the civic center area surrounding the recently completed Westward Arch.</p>
      <p className={styles.body}>Our company also took steps to preserve some of the flavor and excitement of the world's fair when on December 8, 1965, the board of directors authorized bringing the Golden Rondelle theater to Racine.</p>
      <p className={styles.body}>Working with Taliesin Associated Architects, drawings and ideas were worked and reworked until a suitable overall design was selected that will make the theater building compatible with our existing Frank Lloyd Wright structures.</p>
      <p className={styles.body}>The theater building will be constructed on the southwest corner of 14th and Franklin Streets, in Racine, one block north from our Administration and Research Center.</p>
      <figure className={`${styles.figure}`}>
        <Image src="/images/johwax16/johwax38.jpg" alt="" width={456} height={218} className={styles.inlineArt} unoptimized />
      </figure>
      <p className={styles.body}>The masonry facing on the pillars, entrance foyer and exit area will be of the familiar Cherokee red brick to blend in with the existing architectural elements of our Administration and Research Center. The exterior of the theater will be covered with plywood panels and gold anodized aluminum sheeting.</p>
      <p className={styles.body}>The building will be completely self-sufficient of other Racine buildings. It will have its own heating, air-conditioning, water and sewer systems, and will not be connected to our existing buildings in any way.</p>
      <p className={styles.body}>A wide stairway and an elevator will bring visitors to the theater entrance on the second floor of the reception foyer. From the floor of the theater eleven slightly curved rows of comfortable theater seats will rise towards the back giving all visitors a clear, unobstructed view of the screens and stage area. There will be no center aisle. The only access to the seats will be from the two sides.</p>
      <p className={styles.body}>More than 300 tons of specially shaped structural steel will be brought to Racine for use on the new building. Many of these beams were formed specially for the Golden Rondelle to conform to the contour of the curved disk.</p>
      <p className={styles.body}>Just as the outside of the theater will be different than what it was at the fair, the interior also has been changed considerably. Special attention has been given to redesigning elements of the interior to make the theater suitable for a wide variety of employee and civic meetings, including orientation programs, sales meetings, lectures, panel discussions, visual presentations of any kind and even small music groups.</p>
      <p className={styles.body}>Seating capacity will be 319, down from the 550 at the fair. Plans call for replacing the plank seats used at the fair with new upholstered theater type seats. At least half of these will have fold-away writing arms, like those used in schools, to enable persons to write or take notes without difficulty.</p>
      <p className={styles.body}>The projection booth will be equipped with the special 35mm synchronized projectors to show "To Be Alive!" in its original form on a regularly scheduled basis as part of the public relations tour program. The booth also will contain a 16mm movie projector, slide projectors and a variety of other audio-visual aids to make it a complete projection facility geared to handle many assignments.</p>
      <p className={styles.body}>When construction begins, about April, 1966, the three older existing buildings on that block -- the garage, laundry and cooper shop -- will be razed for additional parking and service areas. At the same time, 15th Street between Howe and Franklin Streets, which now has limited access, will be closed completely and the area incorporated into the overall landscaping scheme and parking.</p>
      <p className={styles.body}>Most theaters are all alike. It takes imagination to create one that is modern and functional as well as unusual and distinctive. When work is completed on the Golden Rondelle theater building in late 1966, it will mark the addition of another significant architectural attraction to our Racine headquarters.</p>
      <p className={styles.body}>Our company's fantastic success at the New York World's Fair prompted return of the Golden Rondelle theater to Racine. From a show that began as a question mark, our film "To Be Alive!" became the sleeper of the fair and then the acknowledged hit of the exposition.</p>
      <p className={styles.body}>Before the April 1964 opening, Francis Thompson, the man who created, produced and co-directed the film, told his crew "To Be Alive!" could be a flop. "Ours is just one of the many films at the fair," he said, "Don't be surprised if it isn't a big hit."</p>
      <p className={styles.body}>But success did follow. More than 300 members of the New York press corps gave the film a standing ovation at the special preview. Critic after critic raved about the film's beauty, simplicity and meaningful message depicting the basic joys of simply being alive.</p>
      <figure className={`${styles.figure} ${styles.floatLeft}`}>
        <Image src="/images/johwax16/johwax37.jpg" alt="" width={237} height={250} className={styles.inlineArt} unoptimized />
      </figure>
      <p className={styles.body}>Crowds responded beyond expectations. Except for the initial few weeks, before the word spread, "To Be Alive!" played to capacity audiences every day of the fair. Waiting lines to see the 17 1/2 minute film were often as long as two hours and seldom under one. for the two seasons slightly more than 5 million persons waited to see "To Be Alive!"</p>
      <p className={styles.body}>This tremendous success brought inquiries and requests to see the film from throughout the world. Celebrities came almost every day until our guest register read like an international Who's Who of entertainment, business and government leaders.</p>
      <p className={styles.body}>On seeing "To Be Alive!" at the personal invitation of H. F. Johnson, our Chairman, former President Dwight Eisenhower called it a "most imaginative film and very beautifully done. It shows the world through the children's eyes, where there is no room for prejudice or arrogance. it is a perfect expression of the people-to-people spirit."</p>
      <p className={styles.body}>Our company's decision to enter the New York World's Fair was made in late 1961. It was prompted by a desire to use the fair to emphasize the growing international operations of our company. The fair's basic theme -- Peace Through Understanding -- gave us a remarkable opportunity to demonstrate our world mindedness while, at the same time, stimulating international goodwill for our company and its products on a person-to-person basis.</p>
      <p className={styles.body}>Many reviewers and hundreds of persons who saw the film said that no where else was the fair's theme so dramatically or forcefully presented than in "To Be Alive!"</p>
      <p className={styles.body}>This fine film was presented two outstanding
        awards in 1965. The New York Film Critics voted a special citation
        calling "To Be Alive!" an "outstanding achievement
        in the creative use of the motion picture." this special
        citation was the first bestowed by the group in the past ten
        years. <em>Time</em> magazine called it a citation of unquestionable merit.</p>
      <p className={styles.body}>The film also was presented the top film award of the year by the National Conference of Christians and Jews. The citation called "To Be Alive!" the single most outstanding achievement by a motion picture in the cause of brotherhood and better human relations.</p>
      <p className={styles.body}>The great success and popularity of this film has had a tremendous impact on our company. Every person associated with Johnson, throughout the world, should be proud, not just because of the recognition this film has gained for our company, but because it was an accomplishment of long term value with universal appeal and a theme that stimulated the innermost human emotions.</p>
      <p className={styles.body}>At a time when increased business competition invites advertising and commercial messages in almost anything we do, "To Be Alive!" tells its dramatic story without a single reference to our company or products. This fact in itself generated even more praise and noteworthy comments about Johnson.</p>
      <p className={styles.body}>Speaking of our success in the fair when it closed in October, 1965, Howard M. Packard, President, said, "Our participation in the New York World's Fair, which was conceived by H. F. Johnson, our Chairman, has been an event of major significance in our company's history. During the past two years we brought great pleasure to more than 5 million persons from all over the world who came to see "To Be Alive!" Because of the unique quality and appeal of the theme of the film, our company received widespread recognition through the press, radio and television. The name 'Johnson Wax' became synonymous with 'the best of the fair.' The reputation of our company was notably enhanced through the public goodwill which was generated.</p>
      <p className={styles.body}>"In addition, hundreds of thousands of persons became better acquainted with our product lines through the exhibits, free shoe shines and Home Care Information Center.</p>
      <p className={styles.body}>"While the fair is over, it will have a lasting world-wide impression for many years to come, to the continuing advantage of our company."</p>
      <p className={styles.body}>Even before the fair closed our company was faced with a decision on what to do with the film and our Golden Rondelle after the fair. From the heavy volume of mail that poured into Racine and the tremendous popularity and success of the film at the fair, it was obvious "To Be Alive!" was much too important and valuable to gather dust on some shelf after the fair.</p>
      <p className={styles.body}>And yet there were several serious technical obstacles which prevented drafting any immediate full-scale post-fair plans for the film. "To Be Alive!" was made to be shown only with a special projection system requiring three separate, synchronized 35mm projectors and three slightly separated screens. These characteristics, plus the need for a highly refined sound system, make it impossible to show the film in existing theaters and auditoriums without extensive and expensive modifications to their projection systems.</p>
      <p className={styles.body}>Realizing these technical limitations could curtail future use of the film, our company, late last year, authorized tests to begin on converting "To Be Alive!" to a more universal projection system. Following exacting standards set down by our company and Mr. Thompson, these tests are now underway.</p>
      <p className={styles.source}>
        SOURCE: <em>Johnson Magazine</em>, early 1966(?)
      </p>
    </>
  );
}
