/** Auto-generated from legacy HTML — do not edit by hand unless re-syncing legacy. */

import type { WeshouBlock } from "../weshou/legacyBlockTypes";

export const WESHOU10_BLOCKS: WeshouBlock[] = [
  { type: "h2", text: "COMPLETE LIST OF CONTENTS", variant: "red" },
  {
    type: "dt",
    text: "The contents of the Westinghouse Time Capsule fall into five groups:",
  },
  {
    type: "dt",
    text: "I. SMALL ARTICLES OF COMMON USE that we wear or use, or which contribute to our comfort, convenience, safety, or health. About 35 in number, these articles are separately described and pictured in the microfilm essay. In addition, labels and descriptions are wrapped with each.",
  },
  {
    type: "dt",
    text: "II. TEXTILES AND MATERIALS. About 75 in number, these comprise swatches of various types and weaves of cloth, samples of alloys, plastics, cement, asbestos, coal, etc. Each is described in the microfilm essay, and a further description of the composition, nature and use is wrapped with each sample.",
  },
  {
    type: "dt",
    text: "III. MISCELLANEOUS ITEMS. Seeds, books, money, type, special texts, etc.",
  },
  {
    type: "dt",
    text: "IV. AN ESSAY IN MICROFILM, comprising books, speeches, excerpts from books and encyclopaedias, pictures, critiques, reports, circulars, timetables and other printed or written matter; the whole producing inlogical order a description of our time, our arts, sciences, techniques, sources of information and industries. the essay, divided into fifteen sub-sections, contains the equivalent of more than 100 ordinary books; a total of more than 22,000 pages, more than 10,000,000 words and 1,000 pictures. A microscope is included to enable historians of the future to read the microfilm; also included are instructions for making larger reading machines such as those used with microfilm in modern libraries.",
  },
  {
    type: "dt",
    text: "V. NEWSREEL. Characteristic or significant scenes in sound film prepared by RKO-Pathe Pictures, Inc. for the Time Capsule. Instructions for making a suitable projection machine to use this film are included in the microfilm Micro-File.",
  },
  {
    type: "dt",
    text: "Details appear on the following pages, in the order above described. NOTE: Where several competitive items of equal archaeological value were available, but only one could be included, the item selected was chosen by lot. The name of the maker, when given in the following list, is provided only for type and style identification. Choice of any article for the Time Capsule is not to be interpreted either as a special endorsement of that article or a reflection on the quality of any competing article.",
  },
  { type: "h2", text: "I. ARTICLES OF COMMON USE", variant: "red" },
  { type: "em", text: "Contributing to Convenience, Comfort, Health, Safety" },
  { type: "listRow", text: "Alarm clock" },
  { type: "listRow", text: "Can opener" },
  { type: "listRow", text: "Eyeglasses, bifocals (Bausch & Lomb)" },
  { type: "listRow", text: "Fountain Pen (Waterman)" },
  { type: "listRow", text: "Mazda electric lamp (Westinghouse, 60 watt, 110 volt)" },
  { type: "listRow", text: "Mechanical pencil (Waterman)" },
  { type: "listRow", text: "Miniature camera (Eastman, Bantam K.A. special f.4.5. lens)" },
  { type: "listRow", text: "Nail file" },
  { type: "listRow", text: "Padlock and keys (The Yale & Towne Manufacturing Company)" },
  { type: "listRow", text: "Safety pin" },
  { type: "listRow", text: "Silverware - knife, fork, spoon (Heirloom plate, Grenoble pattern, by Wm. A. Rogers Ltd., Oneida Ltd. Successor)" },
  { type: "listRow", text: "Tape measure (Keuffel & Esser)" },
  { type: "listRow", text: "Tooth brush" },
  { type: "listRow", text: "Tooth powder in small container" },
  { type: "listRow", text: "Transmitter and receiver of ordinary handset telephone" },
  { type: "listRow", text: "Watch (small wrist watch for woman)" },
  { type: "listRow", text: "Westinghouse Sterilamp (bactericidal)" },
  { type: "em", text: "For the Pleasure, Use, and Education of Children" },
  { type: "listRow", text: "Boy's toy - a mechanical, spring propelled automobile" },
  { type: "listRow", text: "Girl's toy - a small doll" },
  { type: "listRow", text: "Mickey-Mouse child's cup of plastic material (Bryant Electric Company)" },
  { type: "listRow", text: "Set of alphabet blocks" },
  { type: "em", text: "Pertaining to the Grooming and Vanity of Women" },
  { type: "listRow", text: "Woman's hat, style of Autumn, 1938 (designed specially by Lilly Dache')" },
  { type: "listRow", text: "Cosmetic make-up kit (Elizabeth Arden Daytime-Cyclamen Color Harmony Box, including two miniature boxes of face-powder, lipstick, rouge, eye shadow)" },
  { type: "listRow", text: "Rhinestone clip (purchased at Woolworth's)" },
  { type: "em", text: "Pertaining Principally to the Grooming, Vanity or Personal Habits of Men" },
  { type: "listRow", text: "Container of tobacco" },
  { type: "listRow", text: "Electric razor and cord (Remington-Rand Close Shaver with Westinghouse motor, General Shaver Corp.)" },
  { type: "listRow", text: "Package of cigarettes" },
  { type: "listRow", text: "Safety razor and blades (Gillette Aristocrat one-piece razor, Gillette Safety Razor Co.)" },
  { type: "listRow", text: "Smoking pipe (Drinkless Kaywoodie, Kaywoodie Company)" },
  { type: "listRow", text: "Tobacco pouch, closed with zipper (Alfred Dunhill of Lundon)" },
  { type: "em", text: "Pertaining to Games pictured and Described in Micro-file:" },
  { type: "listRow", text: "Baseball" },
  { type: "listRow", text: "Deck of cards" },
  { type: "listRow", text: "Golf ball (Kro-flite, A.G. Spalidng & Bros.)" },
  { type: "listRow", text: "Golf tee" },
  { type: "listRow", text: "Poker chips" },
  { type: "h2", text: "II. MATERIALS OF OUR DAY", variant: "red" },
  { type: "em", text: "Fabrics:" },
  { type: "listRow", text: "Asbestos cloth (Johns-Manville)" },
  { type: "listRow", text: "Cotton swatches (Jas. McCutcheon & Co.)" },
  { type: "listRow", text: "Glass fabric samples (Westinghouse glass tape)" },
  { type: "listRow", text: "Linen swatches (Jas. McCutcheon & Co.)" },
  { type: "listRow", text: "Rayon swatches (Du Pont and Celanese)" },
  { type: "listRow", text: "Rubber fabrics (Lastex cloth, United States Rubber Products, Inc.)" },
  { type: "listRow", text: "Silk swatches (Jas. McCutcheon & Co.)" },
  { type: "listRow", text: "Wool swatches (American Woolen Company)" },
  { type: "em", text: "Metals and Metallic Alloys:" },
  { type: "listRow", text: "Hipernik (Westinghouse)" },
  { type: "listRow", text: "Aluminum (Commercially pure sample from Aluminum Company of America)" },
  { type: "listRow", text: "Aluminum high-strength alloy (ST 37 alloy furnished by Aluminum Company of America)" },
  { type: "listRow", text: "Carbon steel (Electro Metallurgical Company)" },
  { type: "listRow", text: "Chromium (Electro Metallurgical Company)" },
  { type: "listRow", text: "Copper (Westinghouse Research Laboratories)" },
  { type: "listRow", text: "Ferromanganese (Electro Metallurgical Company)" },
  { type: "listRow", text: "Ferrosilicon (Electro Metallurgical Company)" },
  { type: "listRow", text: "Ferrovanadium (Electro Metallurgical Company)" },
  { type: "listRow", text: "Iron (Pure sample from Westinghouse Research Laboratories)" },
  { type: "listRow", text: "Magnesium high-strength alloy (Dowmetal, furnished by Dow Chemical Company)" },
  { type: "listRow", text: "Manganese (Electro Metallurgical Comapny)" },
  { type: "listRow", text: "Silicon (Electro Metallurgical Company)" },
  { type: "listRow", text: "Stainless steel (Electro Metallurgical Company" },
  { type: "listRow", text: "Temperable copper (Cupaloy, furnished by Westinghouse)" },
  { type: "listRow", text: "Hipersil (Westinghouse)" },
  { type: "listRow", text: "Tungsten wire (Filament for Westinghouse Mazda electric lamp)" },
  { type: "em", text: "Non-Metallic Materials and Substances:" },
  { type: "listRow", text: "Airplane pulley of laminated phenol plastic Micarta-Westinghouse" },
  { type: "listRow", text: "Anthracite coal (sealed in glass, furnished by Anthracite Institute)" },
  { type: "listRow", text: "Artificial cellulose sponge (E.I. duPont de Nemours & Co., Inc.)" },
  { type: "listRow", text: "Artificial leather" },
  { type: "listRow", text: "Asbestos shingle (furnished by Johns-Manville)" },
  { type: "listRow", text: "Beetleware -- a specimen of urea plastic (Westinghouse)" },
  { type: "listRow", text: "Carborundum (The Carborundum Company)" },
  { type: "listRow", text: "Glass wool" },
  { type: "listRow", text: "Linen packing thread" },
  { type: "listRow", text: "Leather samples --tanned cowhide, genuine morocco (goatskin)" },
  { type: "listRow", text: "Lucite -- a specimen of methyl methacrylate plastic (duPont)" },
  { type: "listRow", text: "Manufactured rubber (tire section furnished by Fisk Tire Co., Inc.)" },
  { type: "listRow", text: "Micarta -- a specimen of phenol plastic (Westinghouse)" },
  { type: "listRow", text: "Noiseless gear of laminated phenol plastic Micarta -- Westinghouse" },
  { type: "listRow", text: "Paper -- four kinds of permanent rag paper used in money, books, permanent ledgers and for special wrapping" },
  { type: "listRow", text: "Portland Cement (Sample furnished by Portland Cement Co., sealed in glass)" },
  { type: "listRow", text: "Raw rubber (Furnished by United States Rubber Products, Inc.)" },
  { type: "listRow", text: "Transite -- a specimen of material made of asbestos and cement (Johns-Manville)" },
  { type: "listRow", text: "Rock wool (Johns-Manville)" },
  { type: "listRow", text: "Synthetic \"rubber\" (Neoprene Chloroprene, furnished by duPont)" },
  { type: "h2", text: "III. MISCELLANEOUS ITEMS", variant: "red" },
  { type: "em", text: "Money of the United States:" },
  { type: "listRow", text: "Dollar bill, silver dollar, half dollar, quarter dollar, dime, nickel, penny" },
  { type: "em", text: "Electrical Items:" },
  { type: "listRow", text: "Electric wall switch (Bryant Electric Company)" },
  { type: "listRow", text: "Electric lamp socket (Bryant Electric Company)" },
  { type: "em", text: "Seeds (Selected and furnished by U.S. Department of Agriculture -- all samples sealed in glass tubes)" },
  { type: "listRow", text: "Wheat, corn, oats, tobacco, cotton, flax, rice, soy beans, alfalfa, sugar beets, carrots, barley" },
  { type: "em", text: "Books (All other books, reports, etc. reduced to microfilm)" },
  { type: "listRow", text: "Selected leather-bound rag-paper copy of the Holy Bible" },
  { type: "listRow", text: "Copy of the Book of Record of the Time Capsule" },
  { type: "em", text: "Type (Supplementary to discussion in Micro-file)" },
  { type: "listRow", text: "Handset type -- Capital and lowercase alphabets of Goudy Village No. 2 type, 14 point" },
  { type: "listRow", text: "Linotype -- 8 point Caslon 13 em slug set on standard Linotype in the shop of the Tuckahoe Record, Tuckahoe, N.Y. The line reads: \"This type set by Linotype Machine\"." },
  { type: "em", text: "Optical Instrument (Other optical instruments described in Micro-File)" },
  { type: "listRow", text: "Magnifier and viewer for use with microfilm and newsreel film." },
  { type: "em", text: "Special Texts (Written on permanent paper in non-fading ink)" },
  { type: "listRow", text: "Special messages from noted men of our time (Albert Einstein, Robert A. Millikan, Karl T. Compton, Thomas Mann)" },
  { type: "listRow", text: "Certificate of Official Witnesses at packing of the Westinghouse Time Capsule" },
  { type: "listRow", text: "Message from Dr. Thornwell Jacobs, President of Oglethorpe University" },
  { type: "listRow", text: "List of Westinghouse men whose suggestions, guidance, engineering and other special skills made the Time Capsule possible." },
  { type: "h2", text: "IV. SCENARIO OF MICROFILM SEQUENCES", variant: "red" },
  { type: "em", text: "Introduction" },
  { type: "listRow", num: "1.", text: "Greetings" },
  { type: "listRow", num: "2.", text: "Directions for making a larger projection machine" },
  { type: "em", text: "I. Aids to Translation" },
  { type: "listRow", num: "3.", text: "Explanation of keys" },
  { type: "listRow", num: "4.", text: "Fable of the North Wind and the Sun in Twenty Languages" },
  { type: "listRow", num: "5.", text: "The Lord's Prayer in 300 Languages" },
  { type: "listRow", num: "6.", text: "The Practical Standard Dictionary: New York: Funk & Wagnalls: 1938" },
  { type: "listRow", num: "7.", text: "Dictionary of Slang and Colloquial English, by John S. Farmer and W.E. Henley: New York: E.P. Dutton & Co.: 6th Impression" },
  { type: "em", text: "II. Where We Live and Work" },
  { type: "listRow", num: "8.", text: "Introduction" },
  { type: "listRow", num: "9.", text: "Individual Homes: Architectural Forum: pages from various 1937-1938 issues" },
  { type: "listRow", num: "10.", text: "Apartments, by Harvey Wiley Corbett: En. Britannica Vol. 20, pp. 870-881" },
  { type: "listRow", num: "11.", text: "The Trailer: catalogue of Kozy Coach, Kalamazoo, Mich., 1938" },
  { type: "listRow", num: "12.", text: "Offices, by Harvey Wiley Corbett: En. Britannica, Vol. 2, pp. 274-287, inc." },
  { type: "listRow", num: "13.", text: "The Story of Rockefeller Center, 1938" },
  { type: "listRow", num: "14.", text: "Office Equipment, by W.H. Leffingwell: En. Britannica; Vol. 16, pp. 712-719 inc." },
  { type: "listRow", num: "15.", text: "Office Machines: catalogue of International Business Machines Corp., 1938" },
  { type: "listRow", num: "16.", text: "Factories: En. Britannica, Vol. 9, pp. 29-31, inc." },
  { type: "listRow", num: "17.", text: "Photograph of Westinghouse East Pittsburgh Works" },
  { type: "listRow", num: "18.", text: "Photograph of Westinghouse Transformer Works, Sharon, Pa." },
  { type: "listRow", num: "19.", text: "Photograph of Westinghouse Elevator Works, Jersey City, N.J." },
  { type: "listRow", num: "20.", text: "Photograph of Headquarters of General Motors Corp., Detroit, Mich." },
  { type: "listRow", num: "21.", text: "Photograph of First stages on assembly belt in General Motors factory" },
  { type: "listRow", num: "22.", text: "Photograph of press that makes automobile tops out of cold steel" },
  { type: "listRow", num: "23.", text: "Photograph of rolling cold steel, American Iron & Steel Institute" },
  { type: "listRow", num: "24.", text: "Photograph of pouring molten iron into a furnace, Amer. Iron & Steel Institute" },
  { type: "em", text: "III. Our Arts and Entertainment" },
  { type: "listRow", num: "25.", text: "Introduction" },
  { type: "listRow", num: "26.", text: "The Arts, by Hendirk Willem van Loon: New York: Simon & Schuster" },
  { type: "listRow", num: "27.", text: "Painting: Encyclopaedia Britannica, Vol. 17, pp 36-65" },
  { type: "listRow", num: "28.", text: "Arozco Frescoes" },
  { type: "listRow", num: "29.", text: "\"Guernica\" - Pablo Picasso" },
  { type: "listRow", num: "30.", text: "\"American Landscape\" - Charles Sheeler" },
  { type: "listRow", num: "31.", text: "\"Summer Wind\" - Alexander Brook" },
  { type: "listRow", num: "32.", text: "\"Promenade\" - Charles Burchfield (1928)" },
  { type: "listRow", num: "33.", text: "\"Lower Manhattan\" - John Marin (1920)" },
  { type: "listRow", num: "34.", text: "\"Persistance of Memory\" - Salvador Dali (Catalan)" },
  { type: "listRow", num: "35.", text: "\"Daughters of the Revolution\" - Grant Wood (American 1932)" },
  { type: "listRow", num: "36.", text: "\"Composition Black, White & Red\" - Piet Mondrian (Dutch)" },
  { type: "listRow", num: "37.", text: "\"Dr. Meyer-Hermann\" - Otto Dix" },
  { type: "listRow", num: "38.", text: "Sculpture: Encyclopaedia Britannica, Vol. 20, pp. 198-231" },
  { type: "listRow", num: "39.", text: "Music: Encyclopaedia Britannica, Vol. 16, pp. 3-24 (with score)" },
  { type: "listRow", num: "40.", text: "Harmony: Encyclopaedia Britannica, Vol. 11, pp. 203-212" },
  { type: "listRow", num: "41.", text: "Finlandia, by Jean Sibelius" },
  { type: "listRow", num: "42.", text: "The Stars and Stripes Forever, by John Philip Sousa" },
  { type: "listRow", num: "43.", text: "The Flat-Foot Floogee, by Slim Gaillard, Slam Steward and Bud Green" },
  { type: "listRow", num: "44.", text: "Photograph of Arturo Toscanini, one of our great directors, conducting a symphony orchestra" },
  { type: "listRow", num: "45.", text: "Photograph of a string quartet" },
  { type: "listRow", num: "46.", text: "Phtograph of a vocal soloist accompanied by orchestra, with audience in foreground" },
  { type: "listRow", num: "47.", text: "Photograph of diners dancing to the accompaniment of an orchestra in a famous New York night club" },
  { type: "listRow", num: "48.", text: "Catalog of instruments, showing constructon, range and how to manipulate" },
  { type: "listRow", num: "49.", text: "Literature: introduction" },
  { type: "listRow", num: "50.", text: "The Essay: Encyclopaedia Brittanica, Vol. 8, pp. 716-717" },
  { type: "listRow", num: "51.", text: "Freud, Goethe, Wagner, by Thomas Mann: New York: Alfred A. Knopf: 1937" },
  { type: "listRow", num: "52.", text: "The Short Story: Encyclopaedia Brittanica, Vol. 20, pp. 580-583" },
  { type: "listRow", num: "53.", text: "Verse: Encyclopaedia Brittanica, Vol. 23, pp. 96-98" },
  { type: "listRow", num: "54.", text: "The Novel: Encyclopaedia Brittanica, Vol. 16, pp. 572-577" },
  { type: "listRow", num: "55.", text: "\"Arrowsmith\" by Sinclair Lewis: New York: Grosset & Dunlap: 1925" },
  { type: "listRow", num: "56.", text: "\"Gone With The Wind\" by Margaret Mitchell: New York: Macmillan: 1938" },
  { type: "listRow", num: "57.", text: "\"The Theater\" by George Jean Nathan: Encyclopaedia Brittanica, Vol. 22, pp. 21-41" },
  { type: "listRow", num: "58.", text: "Best Plays (1936-1937) by Burns Mantle: New York: Dodd, Mead" },
  { type: "listRow", num: "59.", text: "Motion Pictures, by Terry Ramsaye: Encyclopaedia Brittanica, Vol. 15, pp. 854-871" },
  { type: "listRow", num: "60.", text: "Music Hall Program for \"You Can't Take It With You\", Sept. 1, 1938" },
  { type: "listRow", num: "61.", text: "Radio: Encyclopaedia Brittanica, Vol. 23, pp. 663-668" },
  { type: "listRow", num: "62.", text: "The Story of Radio, by Orrin E. Dunlap, Jr.; New York: Dial Press, 1935" },
  { type: "listRow", num: "63.", text: "A radio studio, National Broadcasting Company, New York City" },
  { type: "listRow", num: "64.", text: "Radio Corporation of America Building, Rockefeller Center, New York" },
  { type: "listRow", num: "65.", text: "Master switchboard of the National Broadcasting Comapny" },
  { type: "listRow", num: "66.", text: "Director of radio dramatic program, National Broadcasting Company" },
  { type: "listRow", num: "67.", text: "Radio broadcasting antenna" },
  { type: "listRow", num: "68.", text: "Radio actors \"on the air\"" },
  { type: "listRow", num: "69.", text: "Standard Bridge Rules: R.H. Macy & Co., New York, 1938" },
  { type: "listRow", num: "70.", text: "Photo of a bridge tournament: Acme" },
  { type: "listRow", num: "71.", text: "Hoyle's Card Rules: R.H. Macy & Co., New York, 36th Edition, 1938" },
  { type: "listRow", num: "72.", text: "Typical poker scene: Acme" },
  { type: "listRow", num: "73.", text: "Spalding's Rules of Golf - 1938" },
  { type: "listRow", num: "74.", text: "Typical golf match: Acme" },
  { type: "listRow", num: "75.", text: "Spalding's Football Rules - 1938" },
  { type: "listRow", num: "76.", text: "Scene from football game" },
  { type: "listRow", num: "77.", text: "Spalding Baseball Rules - 1938" },
  { type: "listRow", num: "78.", text: "Scene from baseball game" },
  { type: "em", text: "IV. How Information Is Disseminated Among Us" },
  { type: "listRow", num: "79.", text: "General Introduction" },
  { type: "listRow", num: "80.", text: "Magazines: Introduction" },
  { type: "listRow", num: "81.", text: "Saturday Evening Post, May 7, 1938" },
  { type: "listRow", num: "82.", text: "Collier's, Sept. 3, 1938" },
  { type: "listRow", num: "83.", text: "Ladies Home Journal, September 1938" },
  { type: "listRow", num: "84.", text: "Woman's Home Companion, September 1938" },
  { type: "listRow", num: "85.", text: "Vogue, September 1, 1938" },
  { type: "listRow", num: "86.", text: "McCall's, September 1938" },
  { type: "listRow", num: "87.", text: "Good Housekeeping, September 1938" },
  { type: "listRow", num: "88.", text: "Adventure, September 1938" },
  { type: "listRow", num: "89.", text: "Love Story, September 3, 1938" },
  { type: "listRow", num: "90.", text: "True Confessions, October 1938" },
  { type: "listRow", num: "91.", text: "Complete Western Book Magazine, September 1938" },
  { type: "listRow", num: "92.", text: "Detective Story Magazine, October 1938" },
  { type: "listRow", num: "93.", text: "Amazing Stories, October 1938" },
  { type: "listRow", num: "94.", text: "Weird Tales, September 1938" },
  { type: "listRow", num: "95.", text: "American Mercury, September 1938" },
  { type: "listRow", num: "96.", text: "Time, February 28, 1938" },
  { type: "listRow", num: "97.", text: "Newsweek, July 25, 1938" },
  { type: "listRow", num: "98.", text: "Reader's Digest, September 1938" },
  { type: "listRow", num: "99.", text: "Harper's Magazine, August 1938" },
  { type: "listRow", num: "100.", text: "The Atlantic Monthly, July 1938" },
  { type: "listRow", num: "101.", text: "Scientific American, September 1938" },
  { type: "listRow", num: "102.", text: "Life, May 23, 1938" },
  { type: "listRow", num: "103.", text: "Look, September 13, 1938" },
  { type: "listRow", num: "104.", text: "Your Life, September 1938" },
  { type: "listRow", num: "105.", text: "Fortune, February 1938" },
  { type: "listRow", num: "106.", text: "New Yorker, September 3, 1938" },
  { type: "listRow", num: "107.", text: "Introduction: A Magazine of the pre-halftone era" },
  { type: "listRow", num: "108.", text: "Leslie's Weekly, several issues" },
  { type: "listRow", num: "109.", text: "Newspapers: Introduction" },
  { type: "listRow", num: "110.", text: "New York Herald Tribune, August 24, 1938" },
  { type: "listRow", num: "111.", text: "New York Times, August 19, 1938" },
  { type: "listRow", num: "112.", text: "New York World-Telegram, August 10, 1938" },
  { type: "listRow", num: "113.", text: "New York Sun, January 8, 1938 (complete final)" },
  { type: "listRow", num: "114.", text: "New York Post, September 6, 1938, Sports Extra" },
  { type: "listRow", num: "115.", text: "New York Journal American, July 14, 1938" },
  { type: "listRow", num: "116.", text: "New York Daily News, August 30, 1938" },
  { type: "listRow", num: "117.", text: "New York Mirror, August 29, 1938" },
  { type: "listRow", num: "118.", text: "Daily Worker, August 30, 1938" },
  { type: "listRow", num: "119.", text: "The Cartoon: Introduction" },
  { type: "listRow", num: "120.", text: "Batchelor's \"In the Spring a Young Man's Fancy...\"; Chicago Tribune-New York News Syndicate, 1938" },
  { type: "listRow", num: "121.", text: "Talburt's \"Land of the Rising or Setting Sun?\" New York World-Telegram Syndicate, 1938" },
  { type: "listRow", num: "122.", text: "Kirby's \"Laughter for the Gods\", New York World-Telegram Syndicate, 1938" },
  { type: "listRow", num: "123.", text: "The \"Funny Paper\": Introductions" },
  { type: "listRow", num: "124.", text: "Caniff's \"Terry & The Pirates\"; Link's \"Tiny Tim\"; and \"Dill and Daffy\"; Chicago Tribune -- New York News Syndicate, June 25, 1938" },
  { type: "listRow", num: "125.", text: "Willard's \"Moon Mullins\" and Branning's \"Winnie Winkle the Breadwinner,\" Chicago Tribune -- New York News Syndicate, June 25, 1938" },
  { type: "listRow", num: "126.", text: "Gray's \"Little Orphan Annie\" and Gould's \"Dick Tracy\", Chicago Tribune -- New York News Syndicate, June 25, 1938" },
  { type: "listRow", num: "127.", text: "King's \"Gasoline Alley\" and Edson's \"The Gumps\" Chicago Trib -- NY News Syndicate, June 25, 1938" },
  { type: "listRow", num: "128.", text: "Segar's \"Sappo\" and \"Thimble Theater\", King Features, Sunday, Sept. 18, 1938" },
  { type: "listRow", num: "129.", text: "Knerr's \"Dinglehoofer & His Dog\" and \"The Katzenjammer Kids\", King Features, Spte. 18, 1938" },
  { type: "listRow", num: "130.", text: "Disney's \"Mother Pluto\" and \"Mickey Mouse\", King Features, Sept. 18, 1938" },
  { type: "listRow", num: "131.", text: "DeBeck's \"Bunky\" and \"Barney Google\", King Features, Sept. 18, 1938" },
  { type: "listRow", num: "132.", text: "Cady's \"Peter Rabbit\"; New York Herald Tribune Syndicate, Aug 7, 1938" },
  { type: "listRow", num: "133.", text: "Webster's \"Timid Soul\"; New York Herald Tribune Syndicate, Sept. 4, 1938" },
  { type: "listRow", num: "134.", text: "Webster's \"The Thrill that Comes Once in a Lifetime\": N.Y. Herald Tribune Syndicate, Aug. 27, 1938" },
  { type: "listRow", num: "135.", text: "Our Books: Introduction" },
  { type: "listRow", num: "136.", text: "Methods of Printing, by G. Leonard Gold" },
  { type: "listRow", num: "137.", text: "Design and Beauty in Printing, by Frederic W. Goudy: Press of the Wooly Whale March 8, 1934" },
  { type: "listRow", num: "138.", text: "A History of the Printed Book, by Lawrence C. Wroth: New York: Limited Editions Club, 1938" },
  { type: "listRow", num: "139.", text: "Color in Use: International Printing Ink Corp., copyrighted 1935" },
  { type: "listRow", num: "140.", text: "Color as Light: International Printing Ink Corp., copyrighted 1935" },
  { type: "listRow", num: "141.", text: "Color Chemistry: International Printing Ink Corp., copyrighted 1935" },
  { type: "em", text: "V. Book of General Information About Us" },
  { type: "listRow", num: "142.", text: "A Book of general information about us: Introduction" },
  { type: "listRow", num: "143.", text: "The World Almanac for 1938" },
  { type: "em", text: "VI. Our Religions and Philosphies" },
  { type: "listRow", num: "144.", text: "Introduction" },
  { type: "listRow", num: "145.", text: "The World's Living Religions, by Robert Ernst Hume: New York: Charles Scribner's Sons, 1936" },
  { type: "listRow", num: "146.", text: "A History of Philosophy, by Alfred Weber & Ralph Barton Perry: New York: Charles Scribner's Sons, 1925" },
  { type: "em", text: "VII. Our Education and Educational Systems" },
  { type: "listRow", num: "147.", text: "Introduction" },
  { type: "listRow", num: "148.", text: "Education: Encyclopaedia Britannica, Vol. 7, pp. 964-1005" },
  { type: "listRow", num: "149.", text: "All The Children: 39th Annual Report of the Superintendent of Schools, New York City, School Year 1936-1937" },
  { type: "em", text: "VIII. Our Sciences and Techniques" },
  { type: "listRow", num: "150.", text: "Introduction" },
  { type: "listRow", num: "151.", text: "Science: Encyclopaedia Britannica, Vol. 20, pp. 115-123" },
  { type: "listRow", num: "152.", text: "Scientific Methods: Encyclopaedia Britannica, Vol. 20, pp. 127-133" },
  { type: "listRow", num: "153.", text: "The Story of Science, by David Dietz: Dodd, Mead: 1938" },
  { type: "listRow", num: "154.", text: "The Smithsonian Physical Tables: Washington: Smithsonian Institution, Publications 3171, 1934" },
  { type: "listRow", num: "155.", text: "Meteorology: Encyclopaedia Britannica, Vol. 15, pp. 343-356" },
  { type: "listRow", num: "156.", text: "Mathematics: Encyclopaedia Britannica, Vol. 15, pp. 69-89" },
  { type: "listRow", num: "157.", text: "Portraits of Eminent Mathematicians, by David Eugene Smith: New York: Scripts Mathematica, portfolios 1 and 2" },
  { type: "listRow", num: "158.", text: "Telescopes: Encyclopaedia Britannica, Vol. 15, pp. 904-909" },
  { type: "listRow", num: "159.", text: "Microscopes: Encyclopaedia Britannica, Vol. 15, pp. 433-443" },
  { type: "em", text: "IX. Our Earth, Its Features and Peoples" },
  { type: "listRow", num: "160.", text: "Introduction" },
  { type: "listRow", num: "161.", text: "The World Atlas: New York: Rand McNally" },
  { type: "listRow", num: "162.", text: "Our Races: Introduction" },
  { type: "listRow", num: "163.", text: "The World's Races: Encyclopaedia Britannica, Vol. 2, pp. 41-50" },
  { type: "listRow", num: "164.", text: "Explanation of the Fundamental Triangulation net of the United States (with map)" },
  { type: "listRow", num: "165.", text: "Methods of Surveying: Coast & Geodetic Survey booklets, Nos. 502, 529, 562, 583, Spec. No. 23, Dept. of Commerce" },
  { type: "listRow", num: "166.", text: "Geology: Encyclopaedia Britannica, Vol. 10, pp. 155-173" },
  { type: "listRow", num: "167.", text: "Exploring Down, by Sherwin F. Kelly, reprint from The Explosives Engineer, Sept.-Oct. 1935" },
  { type: "listRow", num: "168.", text: "The Earth: Chester A. Reeds, New York: The University press, First Trade Edition 1935" },
  { type: "em", text: "X. Our Medicine, public health, Dentistry and Pharmacy" },
  { type: "listRow", num: "169.", text: "Introduction" },
  { type: "listRow", num: "170.", text: "Frontiers of Medicine, by Dr. Morris Fishbein: Baltimore: Williams & Wilkins, June 1933" },
  { type: "listRow", num: "171.", text: "Men of Medicine: The March of Time, Issue No. 11, Vol. IV." },
  { type: "listRow", num: "172.", text: "Work of the United States Public Health Service, Reprint 1447" },
  { type: "listRow", num: "173.", text: "Report of the Surgeon General of the United States, June 30, 1937" },
  { type: "listRow", num: "174.", text: "Dentistry: Encyclopaedia Britannica, Vol. 7, pp. 222-225" },
  { type: "listRow", num: "175.", text: "1937 Year Book of Dentistry" },
  { type: "listRow", num: "176.", text: "United States Pharmacopaea" },
  { type: "listRow", num: "177.", text: "X-Ray and Fluoroscopy: catalogues of the Westinghouse X-Ray Company" },
  { type: "em", text: "XI. Our Industries" },
  { type: "listRow", num: "178.", text: "Introduction" },
  { type: "listRow", num: "179.", text: "Explanation of Sears, Roebuck catalog" },
  { type: "listRow", num: "180.", text: "Sears, Roebuck catalog No. 177 - Philadelphia - Fall & Winter 1938-39" },
  { type: "listRow", num: "181.", text: "Inventions and Discoveries: Encyclopaedia Britannica, Vol. 12, pp. 545-547" },
  { type: "listRow", num: "182.", text: "Some basic inventions of modern times: United States Patent Office" },
  { type: "listRow", num: "183.", text: "Industrial Revolution: Encyclopaedia Britannica, Vol. 12, pp. 303-306" },
  { type: "listRow", num: "184.", text: "Industrial Relations: Encyclopaedia Britannica, Vol. 12, pp. 293-303" },
  { type: "listRow", num: "185.", text: "Management's Responsibility to the Public: an address by A.W. Robertson, Chairman of the Board of the Westinghouse Electric & Manufacturing Company, Sept. 19, 1938 before 7th International Management Congress" },
  { type: "listRow", num: "186.", text: "Law and Good Will in Industrial Relations: an address by W.G. Marshall, vice-President of the Westinghouse Electric & Manufacturing Co., before the Committee of One Hundred, Miami, Fla., March 8, 1938" },
  { type: "listRow", num: "187.", text: "Westinghouse Industrial Realtions: a report for 1937" },
  { type: "listRow", num: "188.", text: "The Electrical Industry: Introduction" },
  { type: "listRow", num: "189.", text: "Electricity: Encyclopaedia Britannica, Vol. 8, pp. 182-217" },
  { type: "listRow", num: "190.", text: "Electric Generator: Encyclopaedia Britannica, Vol. 8, pp 174-182" },
  { type: "listRow", num: "191.", text: "Electrical Power: Encyclopaedia Britannica, Vol. 8, pp. 144-174" },
  { type: "listRow", num: "192.", text: "Electric Motor: Encyclopaedia Britannica, Vol. 15, pp. 872-878" },
  { type: "listRow", num: "193.", text: "Electrical Engineering, Fiftieth Anniversary A.I.E.E. 1884-1934, May 1934" },
  { type: "listRow", num: "194.", text: "A Life of George Westinghouse, by Henry G. Prout: New York: Charles Scribner's; 1926" },
  { type: "listRow", num: "195.", text: "Portions of Westinghouse 1939 Catalogue" },
  { type: "listRow", num: "196.", text: "52nd Annual Report of the Westinghouse Electric & Manufacturing Company, Dec. 31, 1937" },
  { type: "listRow", num: "197.", text: "Westinghouse Stockholders' Quarterly for August, 1938" },
  { type: "listRow", num: "198.", text: "Photograph of welding the new office building at the Westinghouse Transformer Works, Sharon, Pa." },
  { type: "listRow", num: "199.", text: "\"Putting in the Throw\" on a 7500 kv-a. synchronous condenser at the Westinghouse East Pittsburgh Works" },
  { type: "listRow", num: "200.", text: "Photograph of tightening a \"steel spider\" at the Westinghouse East Pittsburgh Works" },
  { type: "listRow", num: "201.", text: "Photograph of assembling giant mill motors at the Westinghouse East Pittsburgh Works" },
  { type: "listRow", num: "202.", text: "Photograph of Ignitron tubes in the Westinghouse Research Laboratories" },
  { type: "listRow", num: "203.", text: "Photograph of testing a grid-glow tube in the Westinghouse Research Laboratories." },
  { type: "listRow", num: "204.", text: "Photograph of a lamp machine in the Westinghouse Lamp Works, Bloomfield, N.J." },
  { type: "listRow", num: "205.", text: "Photograph of bottom one-third of 800-foot vertical antenna of Westinghouse radio station KDKA, Pittsburgh, Pa." },
  { type: "listRow", num: "206.", text: "Photograph of a 1938 hostess inspecting complete meal cooking in Westinghouse Automeal Roaster at Merchandise Works, Mansfield, Ohio" },
  { type: "listRow", num: "207.", text: "Agriculture: Introduction" },
  { type: "listRow", num: "208.", text: "Agriculture: Encyclopaedia Britannica, Vol. 1, pp. 391-420" },
  { type: "listRow", num: "209.", text: "Agricultural Machinery and Implements: Encyclopaedia Britannica, Vol. 1, p. 370-378" },
  { type: "listRow", num: "210.", text: "A Graphic summary of Physical Features and Land Utilization in the United States: Dept. of Agri., Misc. Publication No. 20, May 1937" },
  { type: "listRow", num: "211.", text: "A Graphic Summary of Farm Tenure: Dept. of Agri., Misc. Pub. No. 261, Dec. 1936" },
  { type: "listRow", num: "212.", text: "A Graphic Summary of Farm Taxation: Dept. of Agri., Misc. Pub. No. 262, Feb. 1937" },
  { type: "listRow", num: "213.", text: "A Graphic Summary of the Value of Farm property: Dept. of Agri., Misc. Pub. No. 263, July 1937" },
  { type: "listRow", num: "214.", text: "A Graphic Summary of Farm Machinery, Facilities, Roads and Expenditures: Dept. of Agri., Misc. Pub. No. 264, July 1937" },
  { type: "listRow", num: "215.", text: "A Graphic Summary of Farm Labor and Population: Dept. of Agri., Misc. Pub. No. 265, Nov. 1937" },
  { type: "listRow", num: "216.", text: "A Graphic Summary of the Number, Size, and Type of Farm and Value of Products: Dept. of Agri., Misc. Pub. No. 266, Oct. 1937" },
  { type: "listRow", num: "217.", text: "A Graphic summary of Farm Crops: Dept. of Agri., Misc. pub. No. 267, Mar. 1938" },
  { type: "listRow", num: "218.", text: "Automobiles: Introduction" },
  { type: "listRow", num: "219.", text: "Motor Car: Encyclopaedia Britannica, Vol. 15, pp. 880-901" },
  { type: "listRow", num: "220.", text: "Automobile Facts and Figures; Automobile Manufacturers' Association, 1938 editions" },
  { type: "listRow", num: "221.", text: "A Chronicle of the Automotive Industry in America 1892-1936, Eaton Mfg. Co., Cleveland, Ohio" },
  { type: "listRow", num: "222.", text: "Aviation: Introduction" },
  { type: "listRow", num: "223.", text: "Aero Engines: Encyclopaedia Britannica, Vol. 1, pp. 237-242" },
  { type: "listRow", num: "224.", text: "Aeronautics: Encyclopaedia Britannica, Vol. 1, pp. 242-250" },
  { type: "listRow", num: "225.", text: "Aeroplane: Encyclopaedia Britannica, Vol. 1, pp. 250-258" },
  { type: "listRow", num: "226.", text: "Civil Aviation: Encyclopaedia Britannica, Vol. 2, pp. 801-812" },
  { type: "listRow", num: "227.", text: "The aircraft Yearbook for 1938: Aeronautical Chamber of Commerce of America, Inc." },
  { type: "listRow", num: "228.", text: "TWA Timetable, July 1, 1938" },
  { type: "listRow", num: "229.", text: "United Airlines Timetable, July 1, 1938" },
  { type: "listRow", num: "230.", text: "Eastern Air Lines Timetable, August 15, 1938" },
  { type: "listRow", num: "231.", text: "American Airlines Timetable, August 1, 1938" },
  { type: "listRow", num: "232.", text: "Northwest Air Lines Timetable, August 1938" },
  { type: "listRow", num: "233.", text: "Pan American Timetable, July 1, 1938" },
  { type: "listRow", num: "234.", text: "Air France Timetable, Summer 1938, From March 27 to Oct. 1" },
  { type: "listRow", num: "235.", text: "Imperial Airways Timetable, July 1938" },
  { type: "listRow", num: "236.", text: "Swissair Timetable, Summer 1938" },
  { type: "listRow", num: "237.", text: "Swedish Air Lines Timetable, Mar. 27-Oct. 1, 1938" },
  { type: "listRow", num: "238.", text: "Canadian Colonial Airways, July 1, 1938" },
  { type: "listRow", num: "239.", text: "Ships and Shipping: Encyclopaedia Britannica, Vol. 20, pp. 505-563" },
  { type: "listRow", num: "240.", text: "Chemical Industry: Introduction" },
  { type: "listRow", num: "241.", text: "The Chemical Elements and Their Discoveries, Fisher Scientific Co., Jan. 1936" },
  { type: "listRow", num: "242.", text: "Chemistry: Encyclopaedia Britannica, Vol. 5, pp. 355-410" },
  { type: "listRow", num: "243.", text: "Applied Chemistry: Encyclopaedia Britannica, Vol. 5. 410-412" },
  { type: "listRow", num: "244.", text: "A World of Change: an address by Dr. Edward R. Weidlein as President of the American Chemical Society, Rochester meeting, Sept. 9, 1937" },
  { type: "listRow", num: "245.", text: "Industrial Chemistry, by William Thronton Read: New York: John Wiley & Sons, 1933" },
  { type: "listRow", num: "246.", text: "Coal and Coal Mining: Introduction" },
  { type: "listRow", num: "247.", text: "Coal and Coal Mining: Encyclopaedia Britannica, Vol. 5, pp. 868-912" },
  { type: "listRow", num: "248.", text: "The Formation and Characteristics of Pennsylvania Anthracite: The Anthracite Institute" },
  { type: "listRow", num: "249.", text: "Communications: Introduction" },
  { type: "listRow", num: "250.", text: "Telegraph: Encyclopaedia Britannica, Vol. 21, pp. 880-893" },
  { type: "listRow", num: "251.", text: "Telephone: Encyclopaedia Britannica, Vol. 21, pp. 894-904" },
  { type: "listRow", num: "252.", text: "Food Industries: Introduction" },
  { type: "listRow", num: "253.", text: "Food Preservation, Service and Supply: Encyclopaedia Britannica, Vol. 9, pp. 457-460" },
  { type: "listRow", num: "254.", text: "Canning: Encyclopaedia Britannica, Vol. 4, pp. 748-751" },
  { type: "listRow", num: "255.", text: "The Story of Frosted Foods: Birdseye Company, 1938" },
  { type: "listRow", num: "256.", text: "Nutritive Aspects of Canned Foods: The American Can Company, 1937" },
  { type: "listRow", num: "257.", text: "More About Canned Foods, a pamphlet: American Can Company" },
  { type: "listRow", num: "258.", text: "Representative menus, 1938. (Fall, Winter, Spring and Summer menus furnished by Childs Restaurant)" },
  { type: "listRow", num: "259.", text: "Metals and Mining: Introduction" },
  { type: "listRow", num: "260.", text: "Metals: Encyclopaedia Britannica, Vol. 15, pp. 323-325" },
  { type: "listRow", num: "261.", text: "Metallurgy: Encyclopaedia Britannica, Vol. 15, pp. 310-323" },
  { type: "listRow", num: "262.", text: "Metallography: Encyclopaedia Britannica, Vol. 15, pp. 308-310" },
  { type: "listRow", num: "263.", text: "Iron, Iron and Steel, Iron in Art: Encyclopaedia Britannica, Vol. 12, pp. 645-682 incl." },
  { type: "listRow", num: "264.", text: "Aluminum: Encyclopaedia Britannica, Vol. 1, pp. 713-720" },
  { type: "listRow", num: "265.", text: "Copper: Encyclopaedia Britannica, Vol. 6, pp. 401-409" },
  { type: "listRow", num: "266.", text: "Metalliferous Mining: Encyclopaedia Britannica, Vol. 15, pp. 544-551" },
  { type: "listRow", num: "267.", text: "Petroleum: Introduction" },
  { type: "listRow", num: "268.", text: "Petroleum: Encyclopaedia Britannica, Vol. 17, pp. 662-669" },
  { type: "listRow", num: "269.", text: "The Rise of American Oil, by Leonard M. Fanning: New York: Harper & Brother, 1936" },
  { type: "listRow", num: "270.", text: "Railroads: Introduction" },
  { type: "listRow", num: "271.", text: "Railways: Encyclopaedia Britannica, Vol. 18, pp. 916-952" },
  { type: "listRow", num: "272.", text: "New York Central Timetable, Form 1001, July 25, 1938" },
  { type: "listRow", num: "273.", text: "Pennsylvania Railroad Timetable, Aug. 28, 1938" },
  { type: "listRow", num: "274.", text: "Baltimore & Ohio Timetable, July 17, 1938 (East and West)" },
  { type: "listRow", num: "275.", text: "Union Pacific Timetable, Revised to June 12, 1938" },
  { type: "listRow", num: "276.", text: "Northern Pacific timetable, Corrected to June 20, 1938, F. 5111" },
  { type: "listRow", num: "277.", text: "Southern Pavific timetable, Aug. 15-Sept. 1938, Form A" },
  { type: "listRow", num: "278.", text: "Sante Fe Timeable, Corrected to August 7, 1938" },
  { type: "listRow", num: "279.", text: "Streamlined Pennsylvania train" },
  { type: "listRow", num: "280.", text: "Textiles: Introduction" },
  { type: "listRow", num: "281.", text: "Textiles and Embroideries: Encyclopaedia Britannica, Vol. 22, pp. 1-6" },
  { type: "listRow", num: "282.", text: "Weaving: Encyclopaedia Britannica, Vol. 23, pp. 455-466" },
  { type: "listRow", num: "283.", text: "Dyeing: Encyclopaedia Britannica, Vol. 7, pp. 789-795" },
  { type: "listRow", num: "284.", text: "Synthetic Dyes: Encyclopaedia Britannica, Vol. 7, pp. 796-807" },
  { type: "listRow", num: "285.", text: "Designing Women, by Margaretta Byers with Consuelo Kamholz: New York: Simon & Schuster: 1938" },
  { type: "listRow", num: "286.", text: "Women's Wear Style Sheet, 1938" },
  { type: "listRow", num: "287.", text: "Women's Wear for September 1, 1938" },
  { type: "listRow", num: "288.", text: "Fall Textures in duPont Rayon (swatches included in Capsule as objects) 1938" },
  { type: "em", text: "XII. New York World's Fair 1939" },
  { type: "listRow", num: "289.", text: "Introduction" },
  { type: "listRow", num: "290.", text: "Message from Grover Whalen, President of the World's Fair" },
  { type: "listRow", num: "291.", text: "New York, the World's Fair City" },
  { type: "listRow", num: "292.", text: "World's Fair Bulletin A Year from Today" },
  { type: "listRow", num: "293.", text: "World's Fair Bulletin: Participation Issue" },
  { type: "listRow", num: "294.", text: "World's Fair Bulletin for June, 1938" },
  { type: "listRow", num: "295.", text: "List of Officers and Department Heads of the World's Fair" },
  { type: "em", text: "XIII. The Objects in the Capsule" },
  { type: "listRow", num: "296.", text: "Introduction and List" },
  { type: "em", text: "XIV. The men Who Made the Capsule" },
  { type: "listRow", num: "297.", text: "List" },
  { type: "em", text: "XV. How We Appear, Talk and Act; and Scenes of Our Day" },
  { type: "listRow", num: "298.", text: "Introduction" },
  { type: "listRow", num: "299.", text: "Technology of Amateur and Professional Motion Pictures: Encyclopaedia Britannica, Vol. 15, pp. 867-871" },
  { type: "listRow", num: "300.", text: "Motion Picture Technology: Encyclopaedia Britannica, Vol. 15, pp. 854-867" },
  { type: "listRow", num: "301.", text: "Photoelectricity: Encyclopaedia Britannica, Vol. 17, pp. 788-793" },
  { type: "listRow", num: "302.", text: "Production and Projection of the Motion Picture, by Terry Ramsaye, Editor, Motion Picture Herald" },
  { type: "listRow", num: "303.", text: "How to Build a Projection Machine: (diagrams and photos)" },
  { type: "listRow", num: "304.", text: "A projection machine." },
  { type: "h2", text: "V. NEWSREEL", variant: "red" },
  { type: "em", text: "Characteristic or Significant Scenes in Sound Film, Prepared for the Time Capsule by RKO-Pathe Pictures. Instructions for making a Suitable Projection Machine for Use of This Film are Included in the Micro-File. The newsreel runs about 15 minutes. it comprises the following scenes:" },
  { type: "listRow", num: "1.", text: "Franklin D. Roosevelt, President of the United States, speaking at Gettysburg, Pennsylvania, July 3, 1938, on occasion of the 75th anniversary of the celebrated battle of the United States Civil War. Veterans of both sides, attending their final reunion, are present." },
  { type: "listRow", num: "2.", text: "Howard Huges, celebrated aviator, who made \"Around-the-World Flight\" as \"Air Ambassador\" for New York World's Fair 1939, in three days, 19 1/4 hours, July 1938." },
  { type: "dd", text: "a. Plane flying over New York City's skyscrapers as Hughes sets out on first lap. b. Hughes' return at Floyd Bennett Field, New York City, after completing flight. c. Hughes' New York reception , showing enthusiastic crowds lining the streets and paper showering down from skyscrapers." },
  { type: "dd", text: "b. Hughes' return at Floyd Bennett Field, New York City, after completing flight. c. Hughes' New York reception , showing enthusiastic crowds lining the streets and paper showering down from skyscrapers." },
  { type: "dd", text: "c. Hughes' New York reception , showing enthusiastic crowds lining the streets and paper showering down from skyscrapers." },
  { type: "listRow", num: "3.", text: "Jessey owens, American negro athlete, winning 100 meter dash in 1936 Olympic games." },
  { type: "listRow", num: "4.", text: "Collegiate football: Harvard-Yale, November 1936 at \"Yale Bowl,\" New Haven, Conn. Yale wins 14-13." },
  { type: "listRow", num: "5.", text: "Baseball: Big League -- All-Star Game at Crosley Field in Cincinnati, Ohio. 28,000 spectators -- July 1938. nationals defeat Americans 4-1." },
  { type: "listRow", num: "6.", text: "United States Pacific Fleet setting out for six weeks of maneuvers, showing battleships in formation off Long Beach, California, in March 1938." },
  { type: "listRow", num: "7.", text: "Soviets celebrate International Labor Day, May 1938, in Red Square, Moscow, Russia. Two shots of soldiers marching." },
  { type: "listRow", num: "8.", text: "Greatest demonstration of military prowess in the United States since the World War, at Fort Benning, Georgia, April 1938, showing tanks and other war machines." },
  { type: "listRow", num: "9.", text: "Bombing of Canton, typical episode in the undeclared war between China and Japan. Canton, China, June 1938." },
  { type: "dd", text: "a. Pathe cameramn, A.T. Hull, wearing helmet in cockpit of plane, about to take-off to make pictures. b. Smoke rising from explosions off in distance c. Terror-stricken civilians in street d. Red Cross men and women, many of whom are injured while ministering to the victims." },
  { type: "dd", text: "b. Smoke rising from explosions off in distance c. Terror-stricken civilians in street d. Red Cross men and women, many of whom are injured while ministering to the victims." },
  { type: "dd", text: "c. Terror-stricken civilians in street d. Red Cross men and women, many of whom are injured while ministering to the victims." },
  { type: "dd", text: "d. Red Cross men and women, many of whom are injured while ministering to the victims." },
  { type: "listRow", num: "10.", text: "Fashion Show at Miami, Florida, April 1938." },
  { type: "dd", text: "a. General view of luxurious scene in which the audience is seated around a swimming pool, watching models displaying advance summer fashions. b. Two girls in long beach coats c. Two girls in long beach coats opened to reveal bathing suits, wearing enormous straw hats. d. Afternoon dress e. Flowered print afternoon dress with large hat. f. Another afternoon dress with brilliantly colored accessories, and large hat." },
  { type: "dd", text: "b. Two girls in long beach coats c. Two girls in long beach coats opened to reveal bathing suits, wearing enormous straw hats. d. Afternoon dress e. Flowered print afternoon dress with large hat. f. Another afternoon dress with brilliantly colored accessories, and large hat." },
  { type: "dd", text: "c. Two girls in long beach coats opened to reveal bathing suits, wearing enormous straw hats. d. Afternoon dress e. Flowered print afternoon dress with large hat. f. Another afternoon dress with brilliantly colored accessories, and large hat." },
  { type: "dd", text: "d. Afternoon dress e. Flowered print afternoon dress with large hat. f. Another afternoon dress with brilliantly colored accessories, and large hat." },
  { type: "dd", text: "e. Flowered print afternoon dress with large hat. f. Another afternoon dress with brilliantly colored accessories, and large hat." },
  { type: "dd", text: "f. Another afternoon dress with brilliantly colored accessories, and large hat." },
  { type: "listRow", num: "11.", text: "Preview of World's Fair -- 1939: May, 1938" },
  { type: "dd", text: "a. Motorcade of nearly 500 vehicles and floats, including the prize-winnng Westinghouse float, going up a street in downtown Manhattan between sidewalks lined with crowds, under shower of paper. b. Sports float with Babe Ruth, baseball hero. c. Motorcade entering partially completed Fair grounds. d. Fiorello LaGuardia, Mayor of New York City, and Grover A. Whalen, President of the Fair, in reviewing stand at Fair grounds. e. \"Theme Float\" bearing replica of Trylon and Perisphere." },
  { type: "dd", text: "b. Sports float with Babe Ruth, baseball hero. c. Motorcade entering partially completed Fair grounds. d. Fiorello LaGuardia, Mayor of New York City, and Grover A. Whalen, President of the Fair, in reviewing stand at Fair grounds. e. \"Theme Float\" bearing replica of Trylon and Perisphere." },
  { type: "dd", text: "c. Motorcade entering partially completed Fair grounds. d. Fiorello LaGuardia, Mayor of New York City, and Grover A. Whalen, President of the Fair, in reviewing stand at Fair grounds. e. \"Theme Float\" bearing replica of Trylon and Perisphere." },
  { type: "dd", text: "d. Fiorello LaGuardia, Mayor of New York City, and Grover A. Whalen, President of the Fair, in reviewing stand at Fair grounds. e. \"Theme Float\" bearing replica of Trylon and Perisphere." },
  { type: "dd", text: "e. \"Theme Float\" bearing replica of Trylon and Perisphere." },
  { type: "note", text: "NOTE: Whenever reference is made to the Encyclopaedia Britannica, we have used the 14th Edition -- 1937" },
  { type: "figure", src: "/images/weshou10/weshou03.jpg", width: 150, height: 187, alt: "Westinghouse Pavilion 1939", caption: "The Time Capsule under the 1939/1940 Westinghouse World's Fair Building. Latitude 40° 44' 34\" .089 north of the Equator; Longitude 73° 50' 43\" .842 west of Greenwich", captionEm: true },
  { type: "source", text: "SOURCE: The Story of the Westinghouse Time Capsule, © Copyright 1939: Westinghouse Electric & Manufacturing Company East Pittsburgh, PA" },
];
