/** Auto-generated from legacy HTML — do not edit by hand unless re-syncing legacy. */

import type { WeshouBlock } from "../weshou/legacyBlockTypes";

export const WESHOU13_BLOCKS: WeshouBlock[] = [
  { type: "twoFigures", figures: [{"src": "/images/weshou13/weshou37.jpg", "width": 200, "height": 248, "alt": "Capsule contents", "caption": "Objects to be included in Westinghouse Time Capsule II (left) include 50-star flag, a Beatles record and Birth Control pills. Stack of telephone books represents the number of pages of microfilmed information."}, {"src": "/images/weshou13/weshou34.jpg", "width": 200, "height": 284, "alt": "Packing the Capsule", "caption": "Westinghouse technicians load contents into the inner glass crypt of Time Capsule II (right). Plaid bikini swimsuit is shown in the lower right portion of this photo. Capsule design is similar to the capsule buried in 1938."}] },
  { type: "strong", text: "OBJECTS TO BE INCLUDED IN WESTINGHOUSE TIME CAPSULE II" },
  { type: "p", text: "The strides civilization has taken in the past 25 years are reflected in the objects which will be buried for 5,000 years in Westinghouse Time Capsule II. Some of the 45 articles were unheard-of a quarter of a century ago while others represent radical changes since Time Capsule I was entombed in 1938. Citizens 25 years ago would have been startled to learn that part of a space ship -- a piece of the re-entry heat shield from Lt. Cmdr. M. Scott Carpenter's Mercury spacecraft Aurora 7 -- would be included in today's Time Capsule. On the other hand, eye glasses were a commonly used article in 1938. But the advanced development and wide acceptance of contact lenses has accomplished a major advance in this field. Similarly, ball point pens, automatic cameras and electric toothbrushes represent significant refinements of common articles not foreseen a quarter century ago. A complete list of objects that will be buried in Time Capsule II on October 16, 1965, follows:" },
  { type: "em", text: "Articles in Common Use" },
  { type: "listRow3", num: "1.", mid: "A 50-star U.S. Flag --", rest: "reflecting admission to the Union of Hawaii and Alaska." },
  { type: "listRow3", num: "2.", mid: "Bible --", rest: "new revised edition in modern English provided by the American Bible Society." },
  { type: "listRow3", num: "3.", mid: "Credit cards --", rest: "Diner's Club and American Express." },
  { type: "listRow3", num: "4.", mid: "Electronic watch --", rest: "employing principle of natural vibration to tell time electrically. Provided by Bulova Watch Company." },
  { type: "listRow3", num: "5.", mid: "Automatic camera --", rest: "provided by Polaroid Corporation." },
  { type: "listRow3", num: "6.", mid: "Contact lenses --", rest: "provided by Wesley-Jessen, Chicago." },
  { type: "listRow3", num: "7.", mid: "Freeze-dried food --", rest: "beef meat packed in nitrogen atmosphere by Campbell Soup Company." },
  { type: "listRow3", num: "8.", mid: "Plastic wrap --", rest: "used chiefly in preserving foods." },
  { type: "listRow3", num: "9.", mid: "Bikini bathing suit --", rest: "provided by Jantzen, Inc." },
  { type: "listRow3", num: "10.", mid: "Long-playing record --", rest: "The Beatles rendition of \"A Hard Day's Night.\"" },
  { type: "listRow3", num: "11.", mid: "Rechargeable flashlight --", rest: "replaces conventional throw-away cells with type which can be recharged over and over from ordinary electric socket." },
  { type: "listRow3", num: "12.", mid: "Ball point pen --", rest: "provided by Parker Pen Company." },
  { type: "listRow3", num: "13.", mid: "Detergent --", rest: "provided by Lever Brothers." },
  { type: "listRow3", num: "14.", mid: "Transistor radio", rest: "" },
  { type: "listRow3", num: "15.", mid: "Tranquilizer pills", rest: "" },
  { type: "listRow3", num: "16.", mid: "World's Fair Guidebook", rest: "" },
  { type: "listRow3", num: "17.", mid: "Electric toothbrush", rest: "" },
  { type: "listRow3", num: "18.", mid: "Pack of filter cigarettes", rest: "" },
  { type: "em", text: "Atomic Energy" },
  { type: "listRow3", num: "19.", mid: "Film badge --", rest: "measures low level of radiation accumulated over a long period. Provided by the Atomic Energy Commission." },
  { type: "listRow3", num: "20.", mid: "Pocket radiation monitor --", rest: "provides immediate warning of radiation by an audible tone and flashing light. Provided by Oak Ridge National Laboratory." },
  { type: "listRow3", num: "21.", mid: "Sample of Carbon 14 --", rest: "a standardized radioactive isotope, especially useful in geological dating up to 25,000 years. Provided by Westinghouse." },
  { type: "listRow3", num: "22.", mid: "Fermi reactor graphite --", rest: "from world's first nuclear reactor built under West Stands, Stagg Field, University of Chicago. On December 2, 1942, the first self-sustaining chain reaction proved that man could harness the energy of the atom. Provided by the Atomic Energy Commission." },
  { type: "listRow3", num: "23.", mid: "Nautilus film history --", rest: "world's first atomic-powered submarine. Film strip provided by Westinghouse and U.S. Navy." },
  { type: "listRow3", num: "24.", mid: "Calder Hall film --", rest: "film of Queen Elizabeth II opening the world's first nuclear power station at Calder Hall, England, October 1956, provided by the United Kingdom Atomic Energy Authority." },
  { type: "em", text: "Scientific Developments" },
  { type: "listRow3", num: "25.", mid: "Antibiotics --", rest: "representing a family of drugs that combats many diseases more effectively than any others previously in existence. Provided by Lederle Laboratories, Inc." },
  { type: "listRow3", num: "26.", mid: "Synthetic fibers --", rest: "samples of Orlon, Dacron and Lycra. Provided by E.I. duPont de Nemours & Co." },
  { type: "listRow3", num: "27.", mid: "Pyroceram --", rest: "a partially crystallized glass that has unusual resistance to cracking or breaking due to extreme changes in temperature. Provided by Corning Glass Works." },
  { type: "listRow3", num: "28.", mid: "Computer memory unit --", rest: "an electronic means of storing information in a computer so that it can be quickly recovered at any time. Provided by Univac Division, Sperry Rand Corporation." },
  { type: "listRow3", num: "29.", mid: "Plastic heart valve --", rest: "man-made product that can replace a malfunctioning part of the human body. Provided by Edwards Laboratories, Inc., Santa Ana, Calif." },
  { type: "listRow3", num: "30.", mid: "Superconducting wire --", rest: "a special alloy that shows no electrical resistance at temperatures near absolute zero; made possible super-strength magnets. Provided by Westinghouse." },
  { type: "listRow3", num: "31.", mid: "Ruby laser rod --", rest: "makes possible the amplification of light by millions of times in the form of a coherent beam. Provided by the Linde Company." },
  { type: "listRow3", num: "32.", mid: "Normal and irradiated seeds of grain --", rest: "seeds that have been exposed to varying degrees of radiation which may cause basic changes in the plants' growth. Provided by Brookhaven National Laboratory, Upton, Long Island, N.Y." },
  { type: "listRow3", num: "33.", mid: "\"Fresh\" seawater --", rest: "Pacific Ocean water that was converted into pure drinking water at Point Loma, Calif., seawater conversion plant." },
  { type: "listRow3", num: "34.", mid: "Permanent magnet --", rest: "made of particles of ceramic materials which exhibit magnetic properties superior to those found in metals." },
  { type: "listRow3", num: "35.", mid: "Birth control pills --", rest: "" },
  { type: "listRow3", num: "36.", mid: "Molecular blocks", rest: "which integrate into small solid blocks of material the functions usually performed by an entire assembly of electronic components. Provided by Westinghouse." },
  { type: "listRow3", num: "37.", mid: "Sequoia wood sample --", rest: "material which shows the natural radiation level in the atmosphere over long periods of time. Provided by the Redwood Empire Association, Calif." },
  { type: "em", text: "Space" },
  { type: "listRow3", num: "38.", mid: "Re-entry heat shield --", rest: "a piece from the Mercury Aurora 7 spacecraft flown by Lt. Cmdr. M. Scott Carpenter on his three-orbital flight, May 24, 1962. Provided by National Aeronautics and Space Administration's Manned Space Center, Houston, Texas." },
  { type: "listRow3", num: "39.", mid: "Vanguard I parts --", rest: "solar cell powering a microminiaturized radio transmitter of satellite. Provided by Goddard Space Flight Center." },
  { type: "listRow3", num: "40.", mid: "Echo II material --", rest: "outside \"skin\" from balloon satellite. Provided by Langley Research Center, NASA." },
  { type: "listRow3", num: "41.", mid: "Fuel cells --", rest: "device which chemically generates electricity without moving parts. Provided by Westinghouse" },
  { type: "listRow3", num: "42.", mid: "Fiber-reinforced metal --", rest: "experimental material for space applications requiring extreme strengths and low weights." },
  { type: "listRow3", num: "43.", mid: "Tektite --", rest: "material similar to granite believed to have come from the moon and thought to be between 600,000 and 30,000,000 years old. Provided by Goddard Space Flight Center, NASA." },
  { type: "em", text: "Other" },
  { type: "listRow3", num: "44.", mid: "16 mm. microfilm --", rest: "approximately twelve 200-foot reels of microfilm containing more than 50,000 pages of information, including National Geographic Atlas of the World, World Almanac, United Nations Statistical Yearbook, Statistical Abstract of the United States, National Industrial Conference Board Economic Almanac and numerous other encyclopedic works." },
  { type: "listRow3", num: "45.", mid: "Sounds of our times --", rest: "tape recording of famous sounds and voices of the past 25 years." },
  { type: "source", text: "SOURCE: Westinghouse Press Release, undated" },
  { type: "twoFigures", figures: [{"src": "/images/weshou13/weshou36.jpg", "width": 200, "height": 268, "alt": "Pin-back Souvenir", "caption": "A popular souvenir of the Fair. Visitors received these pin-backs after signing their names in a book to be microfilmed and included with the contents of Time Capsule II for burial."}, {"src": "/images/weshou13/weshou35.jpg", "width": 200, "height": 148, "alt": "Capsule II burial", "caption": "Time Capsule II is lowered to its final resting place on \"Time Capsule Day\" at the Fair -- October 16, 1965 -- to be unearthed again in A.D 6939."}] },
  { type: "source", text: "SOURCE: (all) Westinghouse Promotional Photos." },
  { type: "h2", text: "The Supplement to The Book of Record", variant: "red" },
  { type: "p", text: "With the advent of Time Capsule II, Westinghouse had to update The Book of Record with the fact that a new Time Capsule was buried ten feet from the original Capsule at the close of the 1964/1965 New York World's Fair. The supplement, shown below, gives a description of the purpose and location of Time Capsule II." },
  { type: "figure", src: "/images/weshou13/weshou45.jpg", width: 335, height: 500, alt: "Supplement to Book of Record", border: true, caption: "" },
  { type: "source", text: "SOURCE: Richard Post Collection" },
  { type: "figure", src: "/images/weshou13/weshou38.jpg", width: 400, height: 284, alt: "Replica Capsule", caption: "In 1989 the Queens Museum at Flushing Meadows presented a retrospective exhibit on the 50th and 25th anniversaries of the New York World's Fairs. Among the exhibits they displayed were the cut-away models of the Time Capsules on loan from Westinghouse. Photos of the exhibit, taken then, show how the capsules were packed. (photos courtesy of Bradd Schiffman © 2002 Bradd Schiffman, all rights reserved)" },
  { type: "figure", src: "/images/weshou13/weshou39.jpg", width: 400, height: 205, alt: "Contents cutaway", caption: "Round containers in the front of the Capsule hold the microfilm update of 25 years of events that occurred after the first Time Capsule was buried in 1938." },
  { type: "figure", src: "/images/weshou13/weshou40.jpg", width: 400, height: 241, alt: "Contents cutaway", caption: "The Beatles \"A Hard Day's Night\" 45-rpm record can be seen at the back of the capsule. The red light tipped Radiation Detector is near the top." },
  { type: "figure", src: "/images/weshou13/weshou41.jpg", width: 400, height: 284, alt: "Contents cutaway", caption: "Plaid Bikini is discernible in the background. Transistor radio is to the right. Photo also shows the World's Fair Guidebook, American Express credit card and the 50-star US Flag. It is interesting to note that American Express thought to VOID their credit card! Looking ahead, perhaps they didn't want anyone making unauthorized charges in 6939?" },
  { type: "figure", src: "/images/weshou13/weshou42.jpg", width: 400, height: 206, alt: "Contents cutaway", caption: "Artificial Heart Valve is silvery round object with white front in the center of the photo." },
];
