/** Sub-exhibitor names from legacy trantrav02.html (1964 & 1965 manuals). */

export const EXHIBITORS_1964_LEFT = [
  "Allied Van Lines",
  "American Export Isbrandtsen Lines",
  "American Girl Services",
  "Barberio Sales Company",
  "Barrettes of Cape Cod Travel Candies",
  "Birthdates Associates, Inc.",
  "Brother International Corp.",
  "Canadian Pacific",
  "Cape Coral",
  "Carriage Room Cocktail Lounge",
  "Cavalcade of Custom Cars",
  'Cinerama - "To the Moon and Beyond"',
  "Collier's Encyclopedia",
  "Consolidated Forming Company",
  "Constitutional Exhibits, Inc.",
  "Courtesy Club Sales Corp",
  "Data Patterns Inc.",
  "The Diner's Club",
  "Electro-Golf",
  "Ennis Hearing Aid Institute, Inc.",
  "Fair Pictures International",
  "Famous Artist Group",
  "Fleet Messenger Service",
  "Fugazy Travel Bureau",
  "Galaxy Restaurant",
  "Gulf American Land Corp.",
  "Hermes Distributing Co.",
  "House of Gallo",
  "Hollywood Hed-Topper Manufacturing Co.",
  "Hotel Corp. of  New York, Inc.",
  "Imperial 400",
  "Insurance Company of North America",
] as const;

export const EXHIBITORS_1964_RIGHT = [
  "K.L.M. Royal Dutch Airlines",
  "Leburn & Company",
  "Marriot Motor Hotels, Inc.",
  "New York Telephone Co.",
  "Niagara Therapy Manufacturing Corp.",
  "Northwest Airlines (Delta & Braniff)",
  "Oxford Furniture Dist. Co.",
  "Pavilion Hobby & Souvenir Center, Inc.",
  "Raybam Ltd.",
  "Reno Lake Tahoe/Puritan Sportswear",
  "Richmond Hotels, Inc.",
  "Richards Aqua Lung Center",
  "R.S. Concessions & Vending Inc.",
  "Sea Hunt",
  "Space Art Ltd.",
  "Sheraton Corporation of America",
  "Shell Oil Company",
  "Schine Industries",
  "Time, Inc.",
  "Traditional European Imports Limited",
  "Trans World Airlines",
  "Translux",
  "Travel Club of America",
  "Travel Gift Center",
  "Tyrolean Loden Company",
  "United Airlines",
  "United States Army",
  "United States Navy/Marine Corps",
  "United States Power Squadrons",
  "Virginia Travel Council",
  "Western Gems Inc.",
  "World of Ancient Gold",
  "World Wide Productions Inc.",
] as const;

export const EXHIBITORS_1965_LEFT = [
  "Afro-Asian Imports",
  "Allied Van Lines, Inc.",
  "Alva Pen Company",
  "American Export Lines",
  "American Girl Services, Inc.",
  "Birthdate Associates, Inc.",
  "Block Engineering, Inc.",
  "Brother International Corp.",
  "Canadian Pacific Railway Company",
  "Cinerama, Inc.",
  "P.F. Collier",
  "Conate Sales Company",
  "Congress International, Inc.",
  "Consolidated Forming Corp.",
  "The Diners Club",
  "Alex DeGonslar & Paul Kruger",
  "Elmar Trading",
  "Ennis Hearing Aid Institute, Inc.",
  "Exposition Advertising Associates, Inc.",
  "Fair Pictures International",
  "Fleet Messenger Service, Inc.",
  "Fugazy Travel Bureau, Inc.",
  "J.V. Garcia's Homecraft",
  "Gulf American Land Corp.",
  "Hermes Distributing Company",
  "Hotel Travel & Information Center",
  "Hotel Corp. of New York, Inc.",
  "House of Gallo",
  "Insurance Company of North America",
  "KLM Royal Dutch Airlines",
  "Leburn & Company",
  "Mold-A-Rama, Inc.",
  "New York Telephone Company",
] as const;

export const EXHIBITORS_1965_RIGHT = [
  "Niagara Therapy Mfg. Corp.",
  "Northwest, Braniff & Delta",
  "Oxford Furniture Distributing Co.",
  "Pan-Max Imports",
  "Pavilion Hobby & Souvenir Center, Inc.",
  "Porta-Cycle of America",
  "Push-A-Button, Inc.",
  "Raybam, Ltd.",
  "Reno-Lake Tahoe/Puritan Sportswear",
  "Richard's Aqua-Lung Center",
  "Richmond Hotels, Inc.",
  "Schine Industries, Inc.",
  "Sea Presentations, Inc.",
  "Shell Oil Company",
  "Hong Kong Silk Mills",
  "Sil La Trading Company, Ltd.",
  "Space Art, Ltd.",
  "Stephens-Adamson Mfg. Co.",
  "Time, Inc.",
  "Traditional European Imports, Ltd.",
  "Trans World Airlines",
  "Travel Club of America",
  "Tyrolean Loden Co.",
  "United Airlines",
  "U.S. Army",
  "U.S. Coin Corporation",
  "U.S. Navy & Marine",
  "U.S. Rubber Company",
  "Western Gemstones, Inc.",
  "Vallee Limited Partnership",
  "Virginia Travel Council",
  "Turkish Shop",
  "Artco",
  "Gen Tonemaster Associates",
] as const;
