/* Generated by scripts/build-johwax-assets.mjs — do not edit by hand */

export const JOHWAX_07_SCANS = [
  {
    "src": "/images/johwax07/johwax09.01.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax09.01.jpg"
  },
  {
    "src": "/images/johwax07/johwax09.02.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax09.02.jpg"
  },
  {
    "src": "/images/johwax07/johwax09.03.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax09.03.jpg"
  },
  {
    "src": "/images/johwax07/johwax09.04.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax09.04.jpg"
  },
  {
    "src": "/images/johwax07/johwax09.05.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax09.05.jpg"
  },
  {
    "src": "/images/johwax07/johwax09.06.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax09.06.jpg"
  },
  {
    "src": "/images/johwax07/johwax09.07.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax09.07.jpg"
  },
  {
    "src": "/images/johwax07/johwax09.08.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax09.08.jpg"
  },
  {
    "src": "/images/johwax07/johwax09.09.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax09.09.jpg"
  },
  {
    "src": "/images/johwax07/johwax10.01.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax10.01.jpg"
  },
  {
    "src": "/images/johwax07/johwax10.02.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax10.02.jpg"
  },
  {
    "src": "/images/johwax07/johwax10.03.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax10.03.jpg"
  },
  {
    "src": "/images/johwax07/johwax10.04.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax10.04.jpg"
  },
  {
    "src": "/images/johwax07/johwax10.05.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax10.05.jpg"
  },
  {
    "src": "/images/johwax07/johwax10.06.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax10.06.jpg"
  },
  {
    "src": "/images/johwax07/johwax10.07.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax10.07.jpg"
  },
  {
    "src": "/images/johwax07/johwax10.08.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax10.08.jpg"
  },
  {
    "src": "/images/johwax07/johwax10.09.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax10.09.jpg"
  },
  {
    "src": "/images/johwax07/johwax11.01.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax11.01.jpg"
  },
  {
    "src": "/images/johwax07/johwax11.02.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax11.02.jpg"
  },
  {
    "src": "/images/johwax07/johwax11.03.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax11.03.jpg"
  },
  {
    "src": "/images/johwax07/johwax11.04.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax11.04.jpg"
  },
  {
    "src": "/images/johwax07/johwax11.05.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax11.05.jpg"
  },
  {
    "src": "/images/johwax07/johwax11.06.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax11.06.jpg"
  },
  {
    "src": "/images/johwax07/johwax11.07.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax11.07.jpg"
  },
  {
    "src": "/images/johwax07/johwax11.08.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax11.08.jpg"
  },
  {
    "src": "/images/johwax07/johwax11.09.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax11.09.jpg"
  },
  {
    "src": "/images/johwax07/johwax12.01.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax12.01.jpg"
  },
  {
    "src": "/images/johwax07/johwax12.02.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax12.02.jpg"
  },
  {
    "src": "/images/johwax07/johwax12.03.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax12.03.jpg"
  },
  {
    "src": "/images/johwax07/johwax12.04.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax12.04.jpg"
  },
  {
    "src": "/images/johwax07/johwax12.05.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax12.05.jpg"
  },
  {
    "src": "/images/johwax07/johwax12.06.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax12.06.jpg"
  },
  {
    "src": "/images/johwax07/johwax12.07.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax12.07.jpg"
  },
  {
    "src": "/images/johwax07/johwax12.08.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax12.08.jpg"
  },
  {
    "src": "/images/johwax07/johwax12.09.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax12.09.jpg"
  },
  {
    "src": "/images/johwax07/johwax13.01.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax13.01.jpg"
  },
  {
    "src": "/images/johwax07/johwax13.02.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax13.02.jpg"
  },
  {
    "src": "/images/johwax07/johwax13.03.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax13.03.jpg"
  },
  {
    "src": "/images/johwax07/johwax13.04.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax13.04.jpg"
  },
  {
    "src": "/images/johwax07/johwax13.05.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax13.05.jpg"
  },
  {
    "src": "/images/johwax07/johwax13.06.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax13.06.jpg"
  },
  {
    "src": "/images/johwax07/johwax13.07.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax13.07.jpg"
  },
  {
    "src": "/images/johwax07/johwax13.08.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax13.08.jpg"
  },
  {
    "src": "/images/johwax07/johwax13.09.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax13.09.jpg"
  },
  {
    "src": "/images/johwax07/johwax19.01.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax19.01.jpg"
  },
  {
    "src": "/images/johwax07/johwax19.02.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax19.02.jpg"
  },
  {
    "src": "/images/johwax07/johwax19.03.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax19.03.jpg"
  },
  {
    "src": "/images/johwax07/johwax19.04.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax19.04.jpg"
  },
  {
    "src": "/images/johwax07/johwax19.05.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax19.05.jpg"
  },
  {
    "src": "/images/johwax07/johwax19.06.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax19.06.jpg"
  },
  {
    "src": "/images/johwax07/johwax19.07.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax19.07.jpg"
  },
  {
    "src": "/images/johwax07/johwax19.08.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax19.08.jpg"
  },
  {
    "src": "/images/johwax07/johwax19.09.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax19.09.jpg"
  },
  {
    "src": "/images/johwax07/johwax20.01.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax20.01.jpg"
  },
  {
    "src": "/images/johwax07/johwax20.02.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax20.02.jpg"
  },
  {
    "src": "/images/johwax07/johwax20.03.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax20.03.jpg"
  },
  {
    "src": "/images/johwax07/johwax20.04.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax20.04.jpg"
  },
  {
    "src": "/images/johwax07/johwax20.05.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax20.05.jpg"
  },
  {
    "src": "/images/johwax07/johwax20.06.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax20.06.jpg"
  },
  {
    "src": "/images/johwax07/johwax20.07.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax20.07.jpg"
  },
  {
    "src": "/images/johwax07/johwax20.08.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax20.08.jpg"
  },
  {
    "src": "/images/johwax07/johwax20.09.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax20.09.jpg"
  },
  {
    "src": "/images/johwax07/johwax21.01.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax21.01.jpg"
  },
  {
    "src": "/images/johwax07/johwax21.02.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax21.02.jpg"
  },
  {
    "src": "/images/johwax07/johwax21.03.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax21.03.jpg"
  },
  {
    "src": "/images/johwax07/johwax21.04.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax21.04.jpg"
  },
  {
    "src": "/images/johwax07/johwax21.05.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax21.05.jpg"
  },
  {
    "src": "/images/johwax07/johwax21.06.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax21.06.jpg"
  },
  {
    "src": "/images/johwax07/johwax21.07.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax21.07.jpg"
  },
  {
    "src": "/images/johwax07/johwax21.08.jpg",
    "width": 301,
    "height": 234,
    "alt": "johwax21.08.jpg"
  },
  {
    "src": "/images/johwax07/johwax21.09.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax21.09.jpg"
  }
] as const;
