/* Generated by scripts/build-johwax-assets.mjs — do not edit by hand */

export const JOHWAX_09_SCANS = [
  {
    "src": "/images/johwax09/johwax29.01.jpg",
    "width": 351,
    "height": 203,
    "alt": "johwax29.01.jpg"
  },
  {
    "src": "/images/johwax09/johwax29.02.jpg",
    "width": 350,
    "height": 203,
    "alt": "johwax29.02.jpg"
  },
  {
    "src": "/images/johwax09/johwax29.03.jpg",
    "width": 351,
    "height": 202,
    "alt": "johwax29.03.jpg"
  },
  {
    "src": "/images/johwax09/johwax29.04.jpg",
    "width": 350,
    "height": 202,
    "alt": "johwax29.04.jpg"
  },
  {
    "src": "/images/johwax09/johwax29.05.jpg",
    "width": 351,
    "height": 203,
    "alt": "johwax29.05.jpg"
  },
  {
    "src": "/images/johwax09/johwax29.06.jpg",
    "width": 350,
    "height": 203,
    "alt": "johwax29.06.jpg"
  },
  {
    "src": "/images/johwax09/johwax29.07.jpg",
    "width": 351,
    "height": 202,
    "alt": "johwax29.07.jpg"
  },
  {
    "src": "/images/johwax09/johwax29.08.jpg",
    "width": 350,
    "height": 202,
    "alt": "johwax29.08.jpg"
  },
  {
    "src": "/images/johwax09/johwax30.01.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax30.01.jpg"
  },
  {
    "src": "/images/johwax09/johwax30.02.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax30.02.jpg"
  },
  {
    "src": "/images/johwax09/johwax30.03.jpg",
    "width": 300,
    "height": 234,
    "alt": "johwax30.03.jpg"
  },
  {
    "src": "/images/johwax09/johwax30.04.jpg",
    "width": 300,
    "height": 233,
    "alt": "johwax30.04.jpg"
  },
  {
    "src": "/images/johwax09/johwax30.05.jpg",
    "width": 300,
    "height": 233,
    "alt": "johwax30.05.jpg"
  },
  {
    "src": "/images/johwax09/johwax30.06.jpg",
    "width": 300,
    "height": 233,
    "alt": "johwax30.06.jpg"
  },
  {
    "src": "/images/johwax09/johwax30.07.jpg",
    "width": 300,
    "height": 233,
    "alt": "johwax30.07.jpg"
  },
  {
    "src": "/images/johwax09/johwax30.08.jpg",
    "width": 300,
    "height": 233,
    "alt": "johwax30.08.jpg"
  },
  {
    "src": "/images/johwax09/johwax30.09.jpg",
    "width": 300,
    "height": 233,
    "alt": "johwax30.09.jpg"
  },
  {
    "src": "/images/johwax09/johwax31.01.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax31.01.jpg"
  },
  {
    "src": "/images/johwax09/johwax31.02.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax31.02.jpg"
  },
  {
    "src": "/images/johwax09/johwax31.03.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax31.03.jpg"
  },
  {
    "src": "/images/johwax09/johwax31.04.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax31.04.jpg"
  }
] as const;
