/* Generated by scripts/build-johwax-assets.mjs — do not edit by hand */

export const JOHWAX_11_SCANS = [
  {
    "src": "/images/johwax11/johwax39.01.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax39.01.jpg"
  },
  {
    "src": "/images/johwax11/johwax39.02.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax39.02.jpg"
  },
  {
    "src": "/images/johwax11/johwax39.03.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax39.03.jpg"
  },
  {
    "src": "/images/johwax11/johwax39.04.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax39.04.jpg"
  },
  {
    "src": "/images/johwax11/johwax39.05.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax39.05.jpg"
  },
  {
    "src": "/images/johwax11/johwax39.06.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax39.06.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.01.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.01.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.02.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.02.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.03.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.03.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.04.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.04.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.05.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.05.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.06.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.06.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.07.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.07.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.08.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.08.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.09.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.09.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.10.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.10.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.11.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.11.jpg"
  },
  {
    "src": "/images/johwax11/johwax40.12.jpg",
    "width": 300,
    "height": 225,
    "alt": "johwax40.12.jpg"
  }
] as const;
