/* Generated by scripts/build-johwax-assets.mjs — do not edit by hand */

export const JOHWAX_06_SCANS = [
  {
    "src": "/images/johwax06/johwax45.01.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax45.01.jpg"
  },
  {
    "src": "/images/johwax06/johwax45.02.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax45.02.jpg"
  },
  {
    "src": "/images/johwax06/johwax45.03.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax45.03.jpg"
  },
  {
    "src": "/images/johwax06/johwax45.04.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax45.04.jpg"
  },
  {
    "src": "/images/johwax06/johwax45.05.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax45.05.jpg"
  },
  {
    "src": "/images/johwax06/johwax45.06.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax45.06.jpg"
  },
  {
    "src": "/images/johwax06/johwax45.07.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax45.07.jpg"
  },
  {
    "src": "/images/johwax06/johwax45.08.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax45.08.jpg"
  },
  {
    "src": "/images/johwax06/johwax45.09.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax45.09.jpg"
  },
  {
    "src": "/images/johwax06/johwax53.01.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax53.01.jpg"
  },
  {
    "src": "/images/johwax06/johwax53.02.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax53.02.jpg"
  },
  {
    "src": "/images/johwax06/johwax53.03.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax53.03.jpg"
  },
  {
    "src": "/images/johwax06/johwax53.04.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax53.04.jpg"
  },
  {
    "src": "/images/johwax06/johwax53.05.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax53.05.jpg"
  },
  {
    "src": "/images/johwax06/johwax53.06.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax53.06.jpg"
  },
  {
    "src": "/images/johwax06/johwax53.07.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax53.07.jpg"
  },
  {
    "src": "/images/johwax06/johwax53.08.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax53.08.jpg"
  },
  {
    "src": "/images/johwax06/johwax53.09.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax53.09.jpg"
  },
  {
    "src": "/images/johwax06/johwax52.01.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax52.01.jpg"
  },
  {
    "src": "/images/johwax06/johwax52.02.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax52.02.jpg"
  },
  {
    "src": "/images/johwax06/johwax52.03.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax52.03.jpg"
  },
  {
    "src": "/images/johwax06/johwax52.04.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax52.04.jpg"
  },
  {
    "src": "/images/johwax06/johwax52.05.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax52.05.jpg"
  },
  {
    "src": "/images/johwax06/johwax52.06.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax52.06.jpg"
  },
  {
    "src": "/images/johwax06/johwax52.07.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax52.07.jpg"
  },
  {
    "src": "/images/johwax06/johwax52.08.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax52.08.jpg"
  },
  {
    "src": "/images/johwax06/johwax52.09.jpg",
    "width": 156,
    "height": 200,
    "alt": "johwax52.09.jpg"
  },
  {
    "src": "/images/johwax06/johwax54.09.jpg",
    "width": 200,
    "height": 156,
    "alt": "johwax54.09.jpg"
  },
  {
    "src": "/images/johwax06/johwax54.08.jpg",
    "width": 200,
    "height": 156,
    "alt": "johwax54.08.jpg"
  },
  {
    "src": "/images/johwax06/johwax54.07.jpg",
    "width": 200,
    "height": 156,
    "alt": "johwax54.07.jpg"
  },
  {
    "src": "/images/johwax06/johwax54.06.jpg",
    "width": 200,
    "height": 156,
    "alt": "johwax54.06.jpg"
  },
  {
    "src": "/images/johwax06/johwax54.05.jpg",
    "width": 200,
    "height": 156,
    "alt": "johwax54.05.jpg"
  },
  {
    "src": "/images/johwax06/johwax54.04.jpg",
    "width": 200,
    "height": 156,
    "alt": "johwax54.04.jpg"
  },
  {
    "src": "/images/johwax06/johwax54.03.jpg",
    "width": 200,
    "height": 156,
    "alt": "johwax54.03.jpg"
  },
  {
    "src": "/images/johwax06/johwax54.02.jpg",
    "width": 200,
    "height": 156,
    "alt": "johwax54.02.jpg"
  },
  {
    "src": "/images/johwax06/johwax54.01.jpg",
    "width": 200,
    "height": 156,
    "alt": "johwax54.01.jpg"
  },
  {
    "src": "/images/johwax06/johwax55.01.jpg",
    "width": 200,
    "height": 127,
    "alt": "johwax55.01.jpg"
  },
  {
    "src": "/images/johwax06/johwax55.02.jpg",
    "width": 200,
    "height": 127,
    "alt": "johwax55.02.jpg"
  },
  {
    "src": "/images/johwax06/johwax55.03.jpg",
    "width": 200,
    "height": 127,
    "alt": "johwax55.03.jpg"
  },
  {
    "src": "/images/johwax06/johwax55.04.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax55.04.jpg"
  },
  {
    "src": "/images/johwax06/johwax55.05.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax55.05.jpg"
  },
  {
    "src": "/images/johwax06/johwax55.06.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax55.06.jpg"
  },
  {
    "src": "/images/johwax06/johwax55.07.jpg",
    "width": 200,
    "height": 120,
    "alt": "johwax55.07.jpg"
  },
  {
    "src": "/images/johwax06/johwax55.08.jpg",
    "width": 200,
    "height": 120,
    "alt": "johwax55.08.jpg"
  },
  {
    "src": "/images/johwax06/johwax55.09.jpg",
    "width": 200,
    "height": 120,
    "alt": "johwax55.09.jpg"
  },
  {
    "src": "/images/johwax06/johwax56.01.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax56.01.jpg"
  },
  {
    "src": "/images/johwax06/johwax56.02.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax56.02.jpg"
  },
  {
    "src": "/images/johwax06/johwax56.03.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax56.03.jpg"
  },
  {
    "src": "/images/johwax06/johwax56.04.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax56.04.jpg"
  },
  {
    "src": "/images/johwax06/johwax56.05.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax56.05.jpg"
  },
  {
    "src": "/images/johwax06/johwax56.06.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax56.06.jpg"
  },
  {
    "src": "/images/johwax06/johwax56.07.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax56.07.jpg"
  },
  {
    "src": "/images/johwax06/johwax56.08.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax56.08.jpg"
  },
  {
    "src": "/images/johwax06/johwax56.09.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax56.09.jpg"
  },
  {
    "src": "/images/johwax06/johwax57.01.jpg",
    "width": 201,
    "height": 126,
    "alt": "johwax57.01.jpg"
  },
  {
    "src": "/images/johwax06/johwax57.02.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax57.02.jpg"
  },
  {
    "src": "/images/johwax06/johwax57.03.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax57.03.jpg"
  },
  {
    "src": "/images/johwax06/johwax57.04.jpg",
    "width": 201,
    "height": 126,
    "alt": "johwax57.04.jpg"
  },
  {
    "src": "/images/johwax06/johwax57.05.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax57.05.jpg"
  },
  {
    "src": "/images/johwax06/johwax57.06.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax57.06.jpg"
  },
  {
    "src": "/images/johwax06/johwax57.07.jpg",
    "width": 201,
    "height": 126,
    "alt": "johwax57.07.jpg"
  },
  {
    "src": "/images/johwax06/johwax57.08.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax57.08.jpg"
  },
  {
    "src": "/images/johwax06/johwax57.09.jpg",
    "width": 200,
    "height": 126,
    "alt": "johwax57.09.jpg"
  },
  {
    "src": "/images/johwax06/johwax41.jpg",
    "width": 297,
    "height": 432,
    "alt": "johwax41.jpg"
  },
  {
    "src": "/images/johwax06/johwax42.jpg",
    "width": 358,
    "height": 135,
    "alt": "johwax42.jpg"
  },
  {
    "src": "/images/johwax06/johwax43.jpg",
    "width": 358,
    "height": 101,
    "alt": "johwax43.jpg"
  },
  {
    "src": "/images/johwax06/johwax44.jpg",
    "width": 284,
    "height": 159,
    "alt": "johwax44.jpg"
  }
] as const;
