/* Generated by scripts/build-johwax-assets.mjs — do not edit by hand */

export const JOHWAX_15_SCANS = [
  {
    "src": "/images/johwax15/jw00.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw00.01.jpg"
  },
  {
    "src": "/images/johwax15/jw00.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw00.02.jpg"
  },
  {
    "src": "/images/johwax15/jw00.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw00.03.jpg"
  },
  {
    "src": "/images/johwax15/jw00.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw00.04.jpg"
  },
  {
    "src": "/images/johwax15/jw00.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw00.05.jpg"
  },
  {
    "src": "/images/johwax15/jw00.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw00.06.jpg"
  },
  {
    "src": "/images/johwax15/jw01.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw01.01.jpg"
  },
  {
    "src": "/images/johwax15/jw01.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw01.02.jpg"
  },
  {
    "src": "/images/johwax15/jw01.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw01.03.jpg"
  },
  {
    "src": "/images/johwax15/jw01.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw01.04.jpg"
  },
  {
    "src": "/images/johwax15/jw01.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw01.05.jpg"
  },
  {
    "src": "/images/johwax15/jw01.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw01.06.jpg"
  },
  {
    "src": "/images/johwax15/jw02.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw02.01.jpg"
  },
  {
    "src": "/images/johwax15/jw02.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw02.02.jpg"
  },
  {
    "src": "/images/johwax15/jw02.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw02.03.jpg"
  },
  {
    "src": "/images/johwax15/jw02.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw02.04.jpg"
  },
  {
    "src": "/images/johwax15/jw02.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw02.05.jpg"
  },
  {
    "src": "/images/johwax15/jw02.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw02.06.jpg"
  },
  {
    "src": "/images/johwax15/jw03.01.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw03.01.jpg"
  },
  {
    "src": "/images/johwax15/jw03.02.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw03.02.jpg"
  },
  {
    "src": "/images/johwax15/jw03.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw03.03.jpg"
  },
  {
    "src": "/images/johwax15/jw03.04.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw03.04.jpg"
  },
  {
    "src": "/images/johwax15/jw03.05.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw03.05.jpg"
  },
  {
    "src": "/images/johwax15/jw03.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw03.06.jpg"
  },
  {
    "src": "/images/johwax15/jw04.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw04.01.jpg"
  },
  {
    "src": "/images/johwax15/jw04.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw04.02.jpg"
  },
  {
    "src": "/images/johwax15/jw04.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw04.03.jpg"
  },
  {
    "src": "/images/johwax15/jw04.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw04.04.jpg"
  },
  {
    "src": "/images/johwax15/jw04.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw04.05.jpg"
  },
  {
    "src": "/images/johwax15/jw04.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw04.06.jpg"
  },
  {
    "src": "/images/johwax15/jw05.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw05.01.jpg"
  },
  {
    "src": "/images/johwax15/jw05.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw05.02.jpg"
  },
  {
    "src": "/images/johwax15/jw05.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw05.03.jpg"
  },
  {
    "src": "/images/johwax15/jw05.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw05.04.jpg"
  },
  {
    "src": "/images/johwax15/jw05.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw05.05.jpg"
  },
  {
    "src": "/images/johwax15/jw05.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw05.06.jpg"
  },
  {
    "src": "/images/johwax15/jw06.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw06.01.jpg"
  },
  {
    "src": "/images/johwax15/jw06.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw06.02.jpg"
  },
  {
    "src": "/images/johwax15/jw06.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw06.03.jpg"
  },
  {
    "src": "/images/johwax15/jw06.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw06.04.jpg"
  },
  {
    "src": "/images/johwax15/jw06.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw06.05.jpg"
  },
  {
    "src": "/images/johwax15/jw06.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw06.06.jpg"
  },
  {
    "src": "/images/johwax15/jw07.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw07.01.jpg"
  },
  {
    "src": "/images/johwax15/jw07.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw07.02.jpg"
  },
  {
    "src": "/images/johwax15/jw07.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw07.03.jpg"
  },
  {
    "src": "/images/johwax15/jw07.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw07.04.jpg"
  },
  {
    "src": "/images/johwax15/jw07.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw07.05.jpg"
  },
  {
    "src": "/images/johwax15/jw07.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw07.06.jpg"
  },
  {
    "src": "/images/johwax15/jw08.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw08.01.jpg"
  },
  {
    "src": "/images/johwax15/jw08.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw08.02.jpg"
  },
  {
    "src": "/images/johwax15/jw08.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw08.03.jpg"
  },
  {
    "src": "/images/johwax15/jw08.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw08.04.jpg"
  },
  {
    "src": "/images/johwax15/jw08.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw08.05.jpg"
  },
  {
    "src": "/images/johwax15/jw08.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw08.06.jpg"
  },
  {
    "src": "/images/johwax15/jw09.01.jpg",
    "width": 301,
    "height": 166,
    "alt": "jw09.01.jpg"
  },
  {
    "src": "/images/johwax15/jw09.02.jpg",
    "width": 301,
    "height": 166,
    "alt": "jw09.02.jpg"
  },
  {
    "src": "/images/johwax15/jw09.03.jpg",
    "width": 300,
    "height": 166,
    "alt": "jw09.03.jpg"
  },
  {
    "src": "/images/johwax15/jw09.04.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw09.04.jpg"
  },
  {
    "src": "/images/johwax15/jw09.05.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw09.05.jpg"
  },
  {
    "src": "/images/johwax15/jw09.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw09.06.jpg"
  },
  {
    "src": "/images/johwax15/jw10.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw10.01.jpg"
  },
  {
    "src": "/images/johwax15/jw10.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw10.02.jpg"
  },
  {
    "src": "/images/johwax15/jw10.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw10.03.jpg"
  },
  {
    "src": "/images/johwax15/jw10.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw10.04.jpg"
  },
  {
    "src": "/images/johwax15/jw10.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw10.05.jpg"
  },
  {
    "src": "/images/johwax15/jw10.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw10.06.jpg"
  },
  {
    "src": "/images/johwax15/jw11.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw11.01.jpg"
  },
  {
    "src": "/images/johwax15/jw11.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw11.02.jpg"
  },
  {
    "src": "/images/johwax15/jw11.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw11.03.jpg"
  },
  {
    "src": "/images/johwax15/jw11.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw11.04.jpg"
  },
  {
    "src": "/images/johwax15/jw11.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw11.05.jpg"
  },
  {
    "src": "/images/johwax15/jw11.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw11.06.jpg"
  },
  {
    "src": "/images/johwax15/jw12.01.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw12.01.jpg"
  },
  {
    "src": "/images/johwax15/jw12.02.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw12.02.jpg"
  },
  {
    "src": "/images/johwax15/jw12.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw12.03.jpg"
  },
  {
    "src": "/images/johwax15/jw12.04.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw12.04.jpg"
  },
  {
    "src": "/images/johwax15/jw12.05.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw12.05.jpg"
  },
  {
    "src": "/images/johwax15/jw12.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw12.06.jpg"
  },
  {
    "src": "/images/johwax15/jw13.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw13.01.jpg"
  },
  {
    "src": "/images/johwax15/jw13.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw13.02.jpg"
  },
  {
    "src": "/images/johwax15/jw13.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw13.03.jpg"
  },
  {
    "src": "/images/johwax15/jw13.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw13.04.jpg"
  },
  {
    "src": "/images/johwax15/jw13.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw13.05.jpg"
  },
  {
    "src": "/images/johwax15/jw13.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw13.06.jpg"
  },
  {
    "src": "/images/johwax15/jw14.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw14.01.jpg"
  },
  {
    "src": "/images/johwax15/jw14.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw14.02.jpg"
  },
  {
    "src": "/images/johwax15/jw14.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw14.03.jpg"
  },
  {
    "src": "/images/johwax15/jw14.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw14.04.jpg"
  },
  {
    "src": "/images/johwax15/jw14.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw14.05.jpg"
  },
  {
    "src": "/images/johwax15/jw14.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw14.06.jpg"
  },
  {
    "src": "/images/johwax15/jw15.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw15.01.jpg"
  },
  {
    "src": "/images/johwax15/jw15.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw15.02.jpg"
  },
  {
    "src": "/images/johwax15/jw15.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw15.03.jpg"
  },
  {
    "src": "/images/johwax15/jw15.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw15.04.jpg"
  },
  {
    "src": "/images/johwax15/jw15.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw15.05.jpg"
  },
  {
    "src": "/images/johwax15/jw15.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw15.06.jpg"
  },
  {
    "src": "/images/johwax15/jw16.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw16.01.jpg"
  },
  {
    "src": "/images/johwax15/jw16.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw16.02.jpg"
  },
  {
    "src": "/images/johwax15/jw16.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw16.03.jpg"
  },
  {
    "src": "/images/johwax15/jw16.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw16.04.jpg"
  },
  {
    "src": "/images/johwax15/jw16.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw16.05.jpg"
  },
  {
    "src": "/images/johwax15/jw16.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw16.06.jpg"
  },
  {
    "src": "/images/johwax15/jw17.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw17.01.jpg"
  },
  {
    "src": "/images/johwax15/jw17.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw17.02.jpg"
  },
  {
    "src": "/images/johwax15/jw17.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw17.03.jpg"
  },
  {
    "src": "/images/johwax15/jw17.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw17.04.jpg"
  },
  {
    "src": "/images/johwax15/jw17.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw17.05.jpg"
  },
  {
    "src": "/images/johwax15/jw17.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw17.06.jpg"
  },
  {
    "src": "/images/johwax15/jw18.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw18.01.jpg"
  },
  {
    "src": "/images/johwax15/jw18.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw18.02.jpg"
  },
  {
    "src": "/images/johwax15/jw18.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw18.03.jpg"
  },
  {
    "src": "/images/johwax15/jw18.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw18.04.jpg"
  },
  {
    "src": "/images/johwax15/jw18.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw18.05.jpg"
  },
  {
    "src": "/images/johwax15/jw18.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw18.06.jpg"
  },
  {
    "src": "/images/johwax15/jw19.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw19.01.jpg"
  },
  {
    "src": "/images/johwax15/jw19.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw19.02.jpg"
  },
  {
    "src": "/images/johwax15/jw19.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw19.03.jpg"
  },
  {
    "src": "/images/johwax15/jw19.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw19.04.jpg"
  },
  {
    "src": "/images/johwax15/jw19.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw19.05.jpg"
  },
  {
    "src": "/images/johwax15/jw19.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw19.06.jpg"
  },
  {
    "src": "/images/johwax15/jw20.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw20.01.jpg"
  },
  {
    "src": "/images/johwax15/jw20.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw20.02.jpg"
  },
  {
    "src": "/images/johwax15/jw20.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw20.03.jpg"
  },
  {
    "src": "/images/johwax15/jw20.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw20.04.jpg"
  },
  {
    "src": "/images/johwax15/jw20.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw20.05.jpg"
  },
  {
    "src": "/images/johwax15/jw20.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw20.06.jpg"
  },
  {
    "src": "/images/johwax15/jw21.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw21.01.jpg"
  },
  {
    "src": "/images/johwax15/jw21.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw21.02.jpg"
  },
  {
    "src": "/images/johwax15/jw21.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw21.03.jpg"
  },
  {
    "src": "/images/johwax15/jw21.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw21.04.jpg"
  },
  {
    "src": "/images/johwax15/jw21.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw21.05.jpg"
  },
  {
    "src": "/images/johwax15/jw21.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw21.06.jpg"
  },
  {
    "src": "/images/johwax15/jw22.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw22.01.jpg"
  },
  {
    "src": "/images/johwax15/jw22.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw22.02.jpg"
  },
  {
    "src": "/images/johwax15/jw22.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw22.03.jpg"
  },
  {
    "src": "/images/johwax15/jw22.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw22.04.jpg"
  },
  {
    "src": "/images/johwax15/jw22.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw22.05.jpg"
  },
  {
    "src": "/images/johwax15/jw22.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw22.06.jpg"
  },
  {
    "src": "/images/johwax15/jw23.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw23.01.jpg"
  },
  {
    "src": "/images/johwax15/jw23.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw23.02.jpg"
  },
  {
    "src": "/images/johwax15/jw23.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw23.03.jpg"
  },
  {
    "src": "/images/johwax15/jw23.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw23.04.jpg"
  },
  {
    "src": "/images/johwax15/jw23.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw23.05.jpg"
  },
  {
    "src": "/images/johwax15/jw23.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw23.06.jpg"
  },
  {
    "src": "/images/johwax15/jw24.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw24.01.jpg"
  },
  {
    "src": "/images/johwax15/jw24.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw24.02.jpg"
  },
  {
    "src": "/images/johwax15/jw24.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw24.03.jpg"
  },
  {
    "src": "/images/johwax15/jw24.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw24.04.jpg"
  },
  {
    "src": "/images/johwax15/jw24.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw24.05.jpg"
  },
  {
    "src": "/images/johwax15/jw24.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw24.06.jpg"
  },
  {
    "src": "/images/johwax15/jw25.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw25.01.jpg"
  },
  {
    "src": "/images/johwax15/jw25.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw25.02.jpg"
  },
  {
    "src": "/images/johwax15/jw25.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw25.03.jpg"
  },
  {
    "src": "/images/johwax15/jw25.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw25.04.jpg"
  },
  {
    "src": "/images/johwax15/jw25.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw25.05.jpg"
  },
  {
    "src": "/images/johwax15/jw25.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw25.06.jpg"
  },
  {
    "src": "/images/johwax15/jw26.01.jpg",
    "width": 301,
    "height": 166,
    "alt": "jw26.01.jpg"
  },
  {
    "src": "/images/johwax15/jw26.02.jpg",
    "width": 301,
    "height": 166,
    "alt": "jw26.02.jpg"
  },
  {
    "src": "/images/johwax15/jw26.03.jpg",
    "width": 300,
    "height": 166,
    "alt": "jw26.03.jpg"
  },
  {
    "src": "/images/johwax15/jw26.04.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw26.04.jpg"
  },
  {
    "src": "/images/johwax15/jw26.05.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw26.05.jpg"
  },
  {
    "src": "/images/johwax15/jw26.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw26.06.jpg"
  },
  {
    "src": "/images/johwax15/jw27.01.jpg",
    "width": 301,
    "height": 166,
    "alt": "jw27.01.jpg"
  },
  {
    "src": "/images/johwax15/jw27.02.jpg",
    "width": 301,
    "height": 166,
    "alt": "jw27.02.jpg"
  },
  {
    "src": "/images/johwax15/jw27.03.jpg",
    "width": 300,
    "height": 166,
    "alt": "jw27.03.jpg"
  },
  {
    "src": "/images/johwax15/jw27.04.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw27.04.jpg"
  },
  {
    "src": "/images/johwax15/jw27.05.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw27.05.jpg"
  },
  {
    "src": "/images/johwax15/jw27.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw27.06.jpg"
  },
  {
    "src": "/images/johwax15/jw28.01.jpg",
    "width": 301,
    "height": 166,
    "alt": "jw28.01.jpg"
  },
  {
    "src": "/images/johwax15/jw28.02.jpg",
    "width": 301,
    "height": 166,
    "alt": "jw28.02.jpg"
  },
  {
    "src": "/images/johwax15/jw28.03.jpg",
    "width": 300,
    "height": 166,
    "alt": "jw28.03.jpg"
  },
  {
    "src": "/images/johwax15/jw28.04.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw28.04.jpg"
  },
  {
    "src": "/images/johwax15/jw28.05.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw28.05.jpg"
  },
  {
    "src": "/images/johwax15/jw28.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw28.06.jpg"
  },
  {
    "src": "/images/johwax15/jw29.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw29.01.jpg"
  },
  {
    "src": "/images/johwax15/jw29.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw29.02.jpg"
  },
  {
    "src": "/images/johwax15/jw29.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw29.03.jpg"
  },
  {
    "src": "/images/johwax15/jw29.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw29.04.jpg"
  },
  {
    "src": "/images/johwax15/jw29.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw29.05.jpg"
  },
  {
    "src": "/images/johwax15/jw29.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw29.06.jpg"
  },
  {
    "src": "/images/johwax15/jw30.01.jpg",
    "width": 301,
    "height": 166,
    "alt": "jw30.01.jpg"
  },
  {
    "src": "/images/johwax15/jw30.02.jpg",
    "width": 301,
    "height": 166,
    "alt": "jw30.02.jpg"
  },
  {
    "src": "/images/johwax15/jw30.03.jpg",
    "width": 300,
    "height": 166,
    "alt": "jw30.03.jpg"
  },
  {
    "src": "/images/johwax15/jw30.04.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw30.04.jpg"
  },
  {
    "src": "/images/johwax15/jw30.05.jpg",
    "width": 301,
    "height": 165,
    "alt": "jw30.05.jpg"
  },
  {
    "src": "/images/johwax15/jw30.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw30.06.jpg"
  },
  {
    "src": "/images/johwax15/jw31.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw31.01.jpg"
  },
  {
    "src": "/images/johwax15/jw31.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw31.02.jpg"
  },
  {
    "src": "/images/johwax15/jw31.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw31.03.jpg"
  },
  {
    "src": "/images/johwax15/jw31.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw31.04.jpg"
  },
  {
    "src": "/images/johwax15/jw31.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw31.05.jpg"
  },
  {
    "src": "/images/johwax15/jw31.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw31.06.jpg"
  },
  {
    "src": "/images/johwax15/jw32.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw32.01.jpg"
  },
  {
    "src": "/images/johwax15/jw32.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw32.02.jpg"
  },
  {
    "src": "/images/johwax15/jw32.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw32.03.jpg"
  },
  {
    "src": "/images/johwax15/jw32.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw32.04.jpg"
  },
  {
    "src": "/images/johwax15/jw32.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw32.05.jpg"
  },
  {
    "src": "/images/johwax15/jw32.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw32.06.jpg"
  },
  {
    "src": "/images/johwax15/jw33.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw33.01.jpg"
  },
  {
    "src": "/images/johwax15/jw33.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw33.02.jpg"
  },
  {
    "src": "/images/johwax15/jw33.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw33.03.jpg"
  },
  {
    "src": "/images/johwax15/jw33.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw33.04.jpg"
  },
  {
    "src": "/images/johwax15/jw33.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw33.05.jpg"
  },
  {
    "src": "/images/johwax15/jw33.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw33.06.jpg"
  },
  {
    "src": "/images/johwax15/jw34.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw34.01.jpg"
  },
  {
    "src": "/images/johwax15/jw34.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw34.02.jpg"
  },
  {
    "src": "/images/johwax15/jw34.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw34.03.jpg"
  },
  {
    "src": "/images/johwax15/jw34.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw34.04.jpg"
  },
  {
    "src": "/images/johwax15/jw34.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw34.05.jpg"
  },
  {
    "src": "/images/johwax15/jw34.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw34.06.jpg"
  },
  {
    "src": "/images/johwax15/jw35.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw35.01.jpg"
  },
  {
    "src": "/images/johwax15/jw35.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw35.02.jpg"
  },
  {
    "src": "/images/johwax15/jw35.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw35.03.jpg"
  },
  {
    "src": "/images/johwax15/jw35.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw35.04.jpg"
  },
  {
    "src": "/images/johwax15/jw35.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw35.05.jpg"
  },
  {
    "src": "/images/johwax15/jw35.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw35.06.jpg"
  },
  {
    "src": "/images/johwax15/jw36.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw36.01.jpg"
  },
  {
    "src": "/images/johwax15/jw36.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw36.02.jpg"
  },
  {
    "src": "/images/johwax15/jw36.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw36.03.jpg"
  },
  {
    "src": "/images/johwax15/jw36.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw36.04.jpg"
  },
  {
    "src": "/images/johwax15/jw36.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw36.05.jpg"
  },
  {
    "src": "/images/johwax15/jw36.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw36.06.jpg"
  },
  {
    "src": "/images/johwax15/jw37.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw37.01.jpg"
  },
  {
    "src": "/images/johwax15/jw37.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw37.02.jpg"
  },
  {
    "src": "/images/johwax15/jw37.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw37.03.jpg"
  },
  {
    "src": "/images/johwax15/jw37.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw37.04.jpg"
  },
  {
    "src": "/images/johwax15/jw37.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw37.05.jpg"
  },
  {
    "src": "/images/johwax15/jw37.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw37.06.jpg"
  },
  {
    "src": "/images/johwax15/jw38.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw38.01.jpg"
  },
  {
    "src": "/images/johwax15/jw38.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw38.02.jpg"
  },
  {
    "src": "/images/johwax15/jw38.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw38.03.jpg"
  },
  {
    "src": "/images/johwax15/jw38.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw38.04.jpg"
  },
  {
    "src": "/images/johwax15/jw38.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw38.05.jpg"
  },
  {
    "src": "/images/johwax15/jw38.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw38.06.jpg"
  },
  {
    "src": "/images/johwax15/jw39.01.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw39.01.jpg"
  },
  {
    "src": "/images/johwax15/jw39.02.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw39.02.jpg"
  },
  {
    "src": "/images/johwax15/jw39.03.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw39.03.jpg"
  },
  {
    "src": "/images/johwax15/jw39.04.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw39.04.jpg"
  },
  {
    "src": "/images/johwax15/jw39.05.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw39.05.jpg"
  },
  {
    "src": "/images/johwax15/jw39.06.jpg",
    "width": 300,
    "height": 165,
    "alt": "jw39.06.jpg"
  },
  {
    "src": "/images/johwax15/jw41.01.jpg",
    "width": 300,
    "height": 222,
    "alt": "jw41.01.jpg"
  },
  {
    "src": "/images/johwax15/jw41.02.jpg",
    "width": 300,
    "height": 222,
    "alt": "jw41.02.jpg"
  },
  {
    "src": "/images/johwax15/jw41.03.jpg",
    "width": 300,
    "height": 222,
    "alt": "jw41.03.jpg"
  },
  {
    "src": "/images/johwax15/jw41.04.jpg",
    "width": 300,
    "height": 221,
    "alt": "jw41.04.jpg"
  },
  {
    "src": "/images/johwax15/jw41.05.jpg",
    "width": 300,
    "height": 221,
    "alt": "jw41.05.jpg"
  },
  {
    "src": "/images/johwax15/jw41.06.jpg",
    "width": 300,
    "height": 221,
    "alt": "jw41.06.jpg"
  },
  {
    "src": "/images/johwax15/jw41.07.jpg",
    "width": 300,
    "height": 221,
    "alt": "jw41.07.jpg"
  },
  {
    "src": "/images/johwax15/jw41.08.jpg",
    "width": 300,
    "height": 221,
    "alt": "jw41.08.jpg"
  },
  {
    "src": "/images/johwax15/jw41.09.jpg",
    "width": 300,
    "height": 221,
    "alt": "jw41.09.jpg"
  },
  {
    "src": "/images/johwax15/jw42.01.jpg",
    "width": 300,
    "height": 272,
    "alt": "jw42.01.jpg"
  },
  {
    "src": "/images/johwax15/jw42.02.jpg",
    "width": 300,
    "height": 272,
    "alt": "jw42.02.jpg"
  },
  {
    "src": "/images/johwax15/jw42.03.jpg",
    "width": 300,
    "height": 272,
    "alt": "jw42.03.jpg"
  },
  {
    "src": "/images/johwax15/jw42.04.jpg",
    "width": 300,
    "height": 272,
    "alt": "jw42.04.jpg"
  },
  {
    "src": "/images/johwax15/jw42.05.jpg",
    "width": 300,
    "height": 272,
    "alt": "jw42.05.jpg"
  },
  {
    "src": "/images/johwax15/jw42.06.jpg",
    "width": 300,
    "height": 272,
    "alt": "jw42.06.jpg"
  },
  {
    "src": "/images/johwax15/jw42.07.jpg",
    "width": 300,
    "height": 272,
    "alt": "jw42.07.jpg"
  },
  {
    "src": "/images/johwax15/jw42.08.jpg",
    "width": 300,
    "height": 272,
    "alt": "jw42.08.jpg"
  },
  {
    "src": "/images/johwax15/jw42.09.jpg",
    "width": 300,
    "height": 272,
    "alt": "jw42.09.jpg"
  },
  {
    "src": "/images/johwax15/jw40.01.jpg",
    "width": 221,
    "height": 330,
    "alt": "jw40.01.jpg"
  },
  {
    "src": "/images/johwax15/jw40.02.jpg",
    "width": 221,
    "height": 330,
    "alt": "jw40.02.jpg"
  }
] as const;
