/* Generated by scripts/build-johwax-assets.mjs — do not edit by hand */

export const JOHWAX_14_SCANS = [
  {
    "src": "/images/johwax14/jw52.01.jpg",
    "width": 301,
    "height": 288,
    "alt": "jw52.01.jpg"
  },
  {
    "src": "/images/johwax14/jw52.02.jpg",
    "width": 301,
    "height": 288,
    "alt": "jw52.02.jpg"
  },
  {
    "src": "/images/johwax14/jw52.03.jpg",
    "width": 300,
    "height": 288,
    "alt": "jw52.03.jpg"
  },
  {
    "src": "/images/johwax14/jw52.04.jpg",
    "width": 301,
    "height": 287,
    "alt": "jw52.04.jpg"
  },
  {
    "src": "/images/johwax14/jw52.05.jpg",
    "width": 301,
    "height": 287,
    "alt": "jw52.05.jpg"
  },
  {
    "src": "/images/johwax14/jw52.06.jpg",
    "width": 300,
    "height": 287,
    "alt": "jw52.06.jpg"
  },
  {
    "src": "/images/johwax14/jw52.07.jpg",
    "width": 301,
    "height": 288,
    "alt": "jw52.07.jpg"
  },
  {
    "src": "/images/johwax14/jw52.08.jpg",
    "width": 301,
    "height": 288,
    "alt": "jw52.08.jpg"
  },
  {
    "src": "/images/johwax14/jw52.09.jpg",
    "width": 300,
    "height": 288,
    "alt": "jw52.09.jpg"
  },
  {
    "src": "/images/johwax14/jw52.10.jpg",
    "width": 301,
    "height": 287,
    "alt": "jw52.10.jpg"
  },
  {
    "src": "/images/johwax14/jw52.11.jpg",
    "width": 301,
    "height": 287,
    "alt": "jw52.11.jpg"
  },
  {
    "src": "/images/johwax14/jw52.12.jpg",
    "width": 300,
    "height": 287,
    "alt": "jw52.12.jpg"
  }
] as const;
