/* Generated by scripts/build-johwax-assets.mjs — do not edit by hand */

export const JOHWAX_13_SCANS = [
  {
    "src": "/images/johwax13/jw50.01.jpg",
    "width": 201,
    "height": 372,
    "alt": "jw50.01.jpg"
  },
  {
    "src": "/images/johwax13/jw50.02.jpg",
    "width": 201,
    "height": 372,
    "alt": "jw50.02.jpg"
  },
  {
    "src": "/images/johwax13/jw50.03.jpg",
    "width": 200,
    "height": 372,
    "alt": "jw50.03.jpg"
  },
  {
    "src": "/images/johwax13/jw50.04.jpg",
    "width": 201,
    "height": 372,
    "alt": "jw50.04.jpg"
  },
  {
    "src": "/images/johwax13/jw50.05.jpg",
    "width": 201,
    "height": 372,
    "alt": "jw50.05.jpg"
  },
  {
    "src": "/images/johwax13/jw50.06.jpg",
    "width": 200,
    "height": 372,
    "alt": "jw50.06.jpg"
  },
  {
    "src": "/images/johwax13/jw50.07.jpg",
    "width": 201,
    "height": 372,
    "alt": "jw50.07.jpg"
  },
  {
    "src": "/images/johwax13/jw50.08.jpg",
    "width": 201,
    "height": 372,
    "alt": "jw50.08.jpg"
  },
  {
    "src": "/images/johwax13/jw50.09.jpg",
    "width": 200,
    "height": 372,
    "alt": "jw50.09.jpg"
  },
  {
    "src": "/images/johwax13/jw50.10.jpg",
    "width": 201,
    "height": 372,
    "alt": "jw50.10.jpg"
  },
  {
    "src": "/images/johwax13/jw50.11.jpg",
    "width": 201,
    "height": 372,
    "alt": "jw50.11.jpg"
  },
  {
    "src": "/images/johwax13/jw50.12.jpg",
    "width": 200,
    "height": 372,
    "alt": "jw50.12.jpg"
  },
  {
    "src": "/images/johwax13/jw51.01.jpg",
    "width": 301,
    "height": 294,
    "alt": "jw51.01.jpg"
  },
  {
    "src": "/images/johwax13/jw51.02.jpg",
    "width": 301,
    "height": 294,
    "alt": "jw51.02.jpg"
  },
  {
    "src": "/images/johwax13/jw51.03.jpg",
    "width": 300,
    "height": 294,
    "alt": "jw51.03.jpg"
  },
  {
    "src": "/images/johwax13/jw51.04.jpg",
    "width": 301,
    "height": 294,
    "alt": "jw51.04.jpg"
  },
  {
    "src": "/images/johwax13/jw51.05.jpg",
    "width": 301,
    "height": 294,
    "alt": "jw51.05.jpg"
  },
  {
    "src": "/images/johwax13/jw51.06.jpg",
    "width": 300,
    "height": 294,
    "alt": "jw51.06.jpg"
  },
  {
    "src": "/images/johwax13/jw51.07.jpg",
    "width": 301,
    "height": 294,
    "alt": "jw51.07.jpg"
  },
  {
    "src": "/images/johwax13/jw51.08.jpg",
    "width": 301,
    "height": 294,
    "alt": "jw51.08.jpg"
  },
  {
    "src": "/images/johwax13/jw51.09.jpg",
    "width": 300,
    "height": 294,
    "alt": "jw51.09.jpg"
  },
  {
    "src": "/images/johwax13/jw51.10.jpg",
    "width": 301,
    "height": 294,
    "alt": "jw51.10.jpg"
  },
  {
    "src": "/images/johwax13/jw51.11.jpg",
    "width": 301,
    "height": 294,
    "alt": "jw51.11.jpg"
  },
  {
    "src": "/images/johwax13/jw51.12.jpg",
    "width": 300,
    "height": 294,
    "alt": "jw51.12.jpg"
  }
] as const;
