/* Generated by scripts/build-johwax-assets.mjs — do not edit by hand */

export const JOHWAX_12_SCANS = [
  {
    "src": "/images/johwax12/johwax32.01.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax32.01.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.02.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax32.02.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.03.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax32.03.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.04.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax32.04.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.05.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax32.05.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.06.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax32.06.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.07.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax32.07.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.08.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax32.08.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.09.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax32.09.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.10.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax32.10.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.11.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax32.11.jpg"
  },
  {
    "src": "/images/johwax12/johwax32.12.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax32.12.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.01.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax33.01.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.02.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax33.02.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.03.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax33.03.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.04.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax33.04.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.05.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax33.05.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.06.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax33.06.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.07.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax33.07.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.08.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax33.08.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.09.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax33.09.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.10.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax33.10.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.11.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax33.11.jpg"
  },
  {
    "src": "/images/johwax12/johwax33.12.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax33.12.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.01.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax34.01.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.02.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax34.02.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.03.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax34.03.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.04.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax34.04.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.05.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax34.05.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.06.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax34.06.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.07.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax34.07.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.08.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax34.08.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.09.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax34.09.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.10.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax34.10.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.11.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax34.11.jpg"
  },
  {
    "src": "/images/johwax12/johwax34.12.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax34.12.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.01.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax15.01.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.02.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax15.02.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.03.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax15.03.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.04.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax15.04.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.05.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax15.05.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.06.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax15.06.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.07.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax15.07.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.08.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax15.08.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.09.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax15.09.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.10.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax15.10.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.11.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax15.11.jpg"
  },
  {
    "src": "/images/johwax12/johwax15.12.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax15.12.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.01.jpg",
    "width": 302,
    "height": 309,
    "alt": "johwax14.01.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.02.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax14.02.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.03.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax14.03.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.04.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax14.04.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.05.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax14.05.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.06.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax14.06.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.07.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax14.07.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.08.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax14.08.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.09.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax14.09.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.10.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax14.10.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.11.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax14.11.jpg"
  },
  {
    "src": "/images/johwax12/johwax14.12.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax14.12.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.01.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax16.01.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.02.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax16.02.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.03.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax16.03.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.04.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax16.04.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.05.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax16.05.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.06.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax16.06.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.07.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax16.07.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.08.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax16.08.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.09.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax16.09.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.10.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax16.10.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.11.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax16.11.jpg"
  },
  {
    "src": "/images/johwax12/johwax16.12.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax16.12.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.01.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax17.01.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.02.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax17.02.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.03.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax17.03.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.04.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax17.04.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.05.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax17.05.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.06.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax17.06.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.07.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax17.07.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.08.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax17.08.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.09.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax17.09.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.10.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax17.10.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.11.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax17.11.jpg"
  },
  {
    "src": "/images/johwax12/johwax17.12.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax17.12.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.01.jpg",
    "width": 302,
    "height": 310,
    "alt": "johwax18.01.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.02.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax18.02.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.03.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax18.03.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.04.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax18.04.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.05.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax18.05.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.06.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax18.06.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.07.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax18.07.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.08.jpg",
    "width": 301,
    "height": 310,
    "alt": "johwax18.08.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.09.jpg",
    "width": 300,
    "height": 310,
    "alt": "johwax18.09.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.10.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax18.10.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.11.jpg",
    "width": 301,
    "height": 309,
    "alt": "johwax18.11.jpg"
  },
  {
    "src": "/images/johwax12/johwax18.12.jpg",
    "width": 300,
    "height": 309,
    "alt": "johwax18.12.jpg"
  }
] as const;
