/* Generated by scripts/build-johwax-assets.mjs — do not edit by hand */

export const JOHWAX_08_SCANS = [
  {
    "src": "/images/johwax08/johwax26.01.jpg",
    "width": 350,
    "height": 207,
    "alt": "johwax26.01.jpg"
  },
  {
    "src": "/images/johwax08/johwax26.02.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax26.02.jpg"
  },
  {
    "src": "/images/johwax08/johwax26.03.jpg",
    "width": 350,
    "height": 207,
    "alt": "johwax26.03.jpg"
  },
  {
    "src": "/images/johwax08/johwax26.04.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax26.04.jpg"
  },
  {
    "src": "/images/johwax08/johwax27.01.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax27.01.jpg"
  },
  {
    "src": "/images/johwax08/johwax27.02.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax27.02.jpg"
  },
  {
    "src": "/images/johwax08/johwax27.03.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax27.03.jpg"
  },
  {
    "src": "/images/johwax08/johwax27.04.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax27.04.jpg"
  },
  {
    "src": "/images/johwax08/johwax27.05.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax27.05.jpg"
  },
  {
    "src": "/images/johwax08/johwax27.06.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax27.06.jpg"
  },
  {
    "src": "/images/johwax08/johwax27.07.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax27.07.jpg"
  },
  {
    "src": "/images/johwax08/johwax27.08.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax27.08.jpg"
  },
  {
    "src": "/images/johwax08/johwax28.01.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax28.01.jpg"
  },
  {
    "src": "/images/johwax08/johwax28.02.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax28.02.jpg"
  },
  {
    "src": "/images/johwax08/johwax28.03.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax28.03.jpg"
  },
  {
    "src": "/images/johwax08/johwax28.04.jpg",
    "width": 350,
    "height": 206,
    "alt": "johwax28.04.jpg"
  }
] as const;
