/* Generated by scripts/build-johwax-assets.mjs — do not edit by hand */

export const JOHWAX_10_SCANS = [
  {
    "src": "/images/johwax10/jw53.01.jpg",
    "width": 350,
    "height": 191,
    "alt": "jw53.01.jpg"
  },
  {
    "src": "/images/johwax10/jw53.02.jpg",
    "width": 350,
    "height": 192,
    "alt": "jw53.02.jpg"
  },
  {
    "src": "/images/johwax10/jw53.03.jpg",
    "width": 350,
    "height": 191,
    "alt": "jw53.03.jpg"
  },
  {
    "src": "/images/johwax10/jw53.04.jpg",
    "width": 350,
    "height": 191,
    "alt": "jw53.04.jpg"
  },
  {
    "src": "/images/johwax10/jw55.01.jpg",
    "width": 300,
    "height": 156,
    "alt": "jw55.01.jpg"
  },
  {
    "src": "/images/johwax10/jw55.02.jpg",
    "width": 300,
    "height": 156,
    "alt": "jw55.02.jpg"
  },
  {
    "src": "/images/johwax10/jw55.03.jpg",
    "width": 300,
    "height": 156,
    "alt": "jw55.03.jpg"
  },
  {
    "src": "/images/johwax10/jw55.04.jpg",
    "width": 300,
    "height": 156,
    "alt": "jw55.04.jpg"
  },
  {
    "src": "/images/johwax10/jw55.05.jpg",
    "width": 300,
    "height": 156,
    "alt": "jw55.05.jpg"
  },
  {
    "src": "/images/johwax10/jw55.06.jpg",
    "width": 300,
    "height": 156,
    "alt": "jw55.06.jpg"
  },
  {
    "src": "/images/johwax10/jw55.07.jpg",
    "width": 300,
    "height": 156,
    "alt": "jw55.07.jpg"
  },
  {
    "src": "/images/johwax10/jw55.08.jpg",
    "width": 300,
    "height": 156,
    "alt": "jw55.08.jpg"
  },
  {
    "src": "/images/johwax10/jw55.09.jpg",
    "width": 300,
    "height": 156,
    "alt": "jw55.09.jpg"
  },
  {
    "src": "/images/johwax10/jw54.01.jpg",
    "width": 350,
    "height": 191,
    "alt": "jw54.01.jpg"
  },
  {
    "src": "/images/johwax10/jw54.02.jpg",
    "width": 350,
    "height": 192,
    "alt": "jw54.02.jpg"
  },
  {
    "src": "/images/johwax10/jw54.03.jpg",
    "width": 350,
    "height": 191,
    "alt": "jw54.03.jpg"
  },
  {
    "src": "/images/johwax10/jw54.04.jpg",
    "width": 350,
    "height": 191,
    "alt": "jw54.04.jpg"
  }
] as const;
