/* Generated by scripts/build-johwax-assets.mjs — stitched cohesive photographs */

export const JOHWAX_06_SCANS = [
  {
    "src": "/images/johwax06/johwax45.jpg",
    "width": 468,
    "height": 600,
    "alt": "johwax45.jpg"
  },
  {
    "src": "/images/johwax06/johwax53.jpg",
    "width": 468,
    "height": 600,
    "alt": "johwax53.jpg"
  },
  {
    "src": "/images/johwax06/johwax52.jpg",
    "width": 468,
    "height": 600,
    "alt": "johwax52.jpg"
  },
  {
    "src": "/images/johwax06/johwax54.jpg",
    "width": 600,
    "height": 468,
    "alt": "johwax54.jpg"
  },
  {
    "src": "/images/johwax06/johwax55.jpg",
    "width": 600,
    "height": 373,
    "alt": "johwax55.jpg"
  },
  {
    "src": "/images/johwax06/johwax56.jpg",
    "width": 600,
    "height": 378,
    "alt": "johwax56.jpg"
  },
  {
    "src": "/images/johwax06/johwax57.jpg",
    "width": 601,
    "height": 378,
    "alt": "johwax57.jpg"
  },
  {
    "src": "/images/johwax06/johwax41.jpg",
    "width": 297,
    "height": 432,
    "alt": "johwax41.jpg"
  },
  {
    "src": "/images/johwax06/johwax42.jpg",
    "width": 358,
    "height": 135,
    "alt": "johwax42.jpg"
  },
  {
    "src": "/images/johwax06/johwax43.jpg",
    "width": 358,
    "height": 101,
    "alt": "johwax43.jpg"
  },
  {
    "src": "/images/johwax06/johwax44.jpg",
    "width": 284,
    "height": 159,
    "alt": "johwax44.jpg"
  }
] as const;
